ukhsa-collaboration/ntbs_Beta

ntbs-service/Pages/Patients/Edit.cshtml
ntbs-service/Pages/_ViewImports.cshtml
ntbs-service/ntbs-service.csproj
ntbs-service/wwwroot/source/Components/ValidateInput.ts

I've found an nhs-maintained library of "[tag helpers](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro?view=aspnetcore-2.2)" for the nhs frontend: https://github.com/nhsuk/frontend-dotnetcore
I've applied it to half the patient details page as an example of what using it would be like. It still exposes a lot of the structure of the html to us, so it seems like we can use other helpers (`asp-for` etc), as well as vue bindings (`v-bind`, `ref`).
Curious to find out what you guys think. It doesn't completely cut out the boilerplate, but seems to reduce it a little. We might get better IDE support for it too.
BTW, lib is better documented than it looks at first glance, it's got READMEs on individual components, e.g. …

Integrate nhs frontend core library

---

.github/pull_request_template.md
ntbs-service/Pages/Shared/_Layout.cshtml
ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/webpack.common.js
ntbs-service/wwwroot/source/app.ts
package-lock.json

This fixes ie11 failing to parse the js bundle, which also killed css, as it was being delivered by js.
I've removed the offending es6 script coming from the nhs uk library. We weren't using it anyways, and if we need to add it back, there's a compiled, minified version that's es5 compliant. Ideally, we'll only pull in the components we need, too, as opposed to the whole thing.
While here, I've also split out the css into own file and stopped it being provided by js. I've also added cache busting on both assets.
Hot-reload verified to still be in tact :)

NTBS-356 ie11 issues

---

ntbs-service/Models/ContactTracing.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ContactTracingOverviewPartial.cshtml
ntbs-service/wwwroot/css/notificationView.scss

Display empty space on Overview page when value doesn't exist
Overview page was omitting empty values and therefore shifting some values. Fixed the bug by displaying empty space.
Also overview page was not displaying Total when one of the values is missing

NTBS-438: Display empty space on Overview page when value doesn't exist

---

ntbs-service-unit-tests/Pages/SearchPageTest.cs
ntbs-service/Pages/Search/Index.cshtml.cs
ntbs-service/Services/SearchService.cs

Fix search ordering to show draft notifications ordered by date first then notified/denotified notifications ordered by date

Fix search ordering

---

ntbs-service/wwwroot/source/Components/ConditionalEntryYear.ts

Last minute small refactor (to use Array.prototype.includes) with a false assumption that we were using babel, followed by not retesting in IE, meant that the component only partially worked in IE.

NTBS-190: Make component IE friendly

---

ntbs-integration-tests/NotificationPages/PatientPageTests.cs
ntbs-service/Models/PatientDetails.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml.cs

Issues in the intersection between having an `int?` field, and the field requiring data not available during post...
The thoroughly discussed workaround is to strip out values that don't match the validation requirement, thus rendering the validation moot. Added benefit of this option is to allow default validation to exist (no requirement to `clearValidationState`) so a 'fish' input can receive a validation message.
Sneaky change to add validation message tag-helper to some of the missing fields in Patient.cshtml.
**Below not tested as this changeset is a superficial front-end change**
- [] Test with one screen reader (e.g. [NVDA](https://www.nvaccess.org/): see [getting started](https://webaim.org/articles/nvda/)) - logical flow, no unexpected content. 
- [] Passes automated checker …

NTBS-190: Adjust validation approach for year of uk entry

---

ntbs-integration-tests/Helpers/TestDocumentExtensions.cs
ntbs-integration-tests/Helpers/TestDocumentHelpers.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/EpisodesPageTests.cs
ntbs-integration-tests/TestRunnerBase.cs
ntbs-service/Models/Episode.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Create.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/UserService.cs

Validate the selected hospital is part of the tbservice. Also ensure notifications are created with default service (part of that was already implemented by @lbbethke's recent changes, but more rounding out).  General cleanup of the hospital page included, going commit by commit might be helpful to contain the noise.

NTBS-130 default notification service to its creating users service

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

Renamed variables in tests and on overview page to the new names (IsDOT -> DotStatus and IsEnhancedCaseManagement -> EnhancedCaseManagementStatus)

NTBS-527 fix renaming for new names of clinicalDetails fields

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/wwwroot/source/Components/DateComparison.ts

This bulk of this change involves using this.$set over manually setting the date warnings so that a new array is created and Vue can pick up the change and realise a rerender is needed.

Ntbs 429 hide date warning if symptomatic false

---

ntbs-integration-tests/Helpers/TestDocumentExtensions.cs
ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/DeletePageTests.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/EpisodesPageTests.cs
ntbs-integration-tests/NotificationPages/ImmunosuppressionPageTests.cs
ntbs-integration-tests/NotificationPages/PatientPageTests.cs
ntbs-integration-tests/SearchPage/SearchPageTests.cs
ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/PatientDetails.cs
ntbs-service/Models/Validations/ValidationAttributes.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml

Fix "today" getting cached in the date range validation to value from server startup
Separate commit bring the error message assertion helper to all places that need it.

NTBS-640 fix cached date range validation

---

Dockerfile
Jenkinsfile
ntbs-service/Program.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.Test.json

* Make docker build only copy the files it actually needs
* Run tests in parallel
I've tried out the change to parallel in https://jenkins2.softwire.com/job/phe-ntbs/job/master/414/, which took ages - seemingly the move to parallel has made all intermediate image caches invalid (as a result of running on different slaves perhaps??). I assume these will now be sourcable from the cache and will actually speed up once merged, but if not i'm ready to take the parallel bit out

Speed up jenkins

---

ntbs-service/Pages/Notifications/Edit/Episode.cshtml

Simple change to add disabled dropdown to show locked TB service - the hidden input is kept in as a disabled select won't send it's information in the form (which is needed for validation). Another approach would be to make the select component "readonly" and style it as if it is disabled (give it grey text instead of black).

NTBS-210 use disabled dropdown to show locked TB service

---

ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/wwwroot/css/site.scss
ntbs-service/wwwroot/source/Components/DateComparison.ts
ntbs-service/wwwroot/source/Components/NhsNumberDuplicateWarning.ts
ntbs-service/wwwroot/source/Components/ValidateDate.ts

Fix issue with nhs-duplicate component
Additionally roll out warning component to other warnings (clinical dates) and recolour to `orangered`.

NTBS-451: Post-qa markups

---

ntbs-service/Program.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.Production.json
ntbs-service/appsettings.json
ntbs-service/ntbs-service.csproj

Logs should now have timestamps and request ids on them consistently.
Serilog seems more flexible then the default logger so we can tweak it further as needed.

Use serilog for better request logs

---

ntbs-service/Services/SearchService.cs

Search by notification date (and if that is not available use creation date).
I have left a comment on the ticket to check that this is intended behaviour and that we don't want to separate out drafts that do and don't have a notification date (will update this PR with the result of that conversation).
Local tests pass [X]

NTBS-684 Order search results by notification date

---

ntbs-service/Services/AlertService.cs

Originally was going to provide it as part of the alert passed to the method but think this is unnecessary

NTBS-370 add alert creation date into alertService

---

ntbs-service-unit-tests/Pages/SearchPageTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Pages/Search/Index.cshtml.cs

This simplifies the query, which has a chance of improving the results. Unfortunately the timeout-inducing performance is not consistently reproducible (perhaps db spec influences this), but a comparison of the query plans reported for the before and after query can be found on the ticket.
In particular, it removes:
- an inter-query sort
- table spool
- preserves left join approach to the table joins, which got turned into outer right joins before
(also includes deleting some unused code in the repository)

NTBS-712 Simplify notification query used for homepage lists

---

ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/Pages/Alerts/Dismiss.cshtml.cs

Routing was providing `{ id = notificationId }` rather than the new autobound `{ notificationId }`

NTBS-376: Fix notification routing

---

ntbs-integration-tests/NotificationPages/PatientPageTests.cs
ntbs-service/Pages/Notifications/Edit/_SinglePageErrorSummaryPartial.cshtml
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs

Added test to check it renders on patient details page as well.
A code base clean up/merge had removed a couple of lines last week but this should fix it :)

NTBS-328 add error summary back in 

---

ntbs-service/package-lock.json
ntbs-service/package.json

Reverts PublicHealthEngland/ntbs_Beta#259
Needs manual check: https://jenkins2.softwire.com/job/phe-ntbs/job/master/549/console

Revert "Bump mini-css-extract-plugin from 0.8.2 to 0.9.0 in /ntbs-service"

---

ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs

We were defaulting the case manager twice over - once at creation time,
and then again at render time. The latter is the more confusing behaviour,
as indicated by this bug, and as recorded on this comment:
https://github.com/PublicHealthEngland/ntbs_Beta/pull/150/files/8fff34895e70dfb2d97738d79ec3f6076ec2a769#r346286846
The case manager will still default correctly at creation:
https://github.com/PublicHealthEngland/ntbs_Beta/blob/50f219f154d7b912e2642b61a8261e122e95c774/ntbs-service/Services/NotificationService.cs#L334

NTBS-781 Remove volatile case manager defaulting

---

ntbs-service/Pages/Reports/Index.cshtml
ntbs-service/Pages/Reports/Index.cshtml.cs
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/appsettings.Development.json
ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

Adds a new header in the top of the page for `/Reports`.
This navigates to a placeholder page if an env variables is not set. If it is set, then performs a redirect to that site.

NTBS-378: Add functionality for linking to report page

---

EFAuditer-tests/UnitTests/Services/EFAuditServiceExtensionsTest.cs
EFAuditer/AuditDatabaseContext.cs
EFAuditer/EFAuditServiceExtensions.cs
ntbs-service/Middleware/AuditGetRequestMiddleware.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Services/AuditService.cs

Add logic for nicely auditing inserts and reads.
Additional sneaky change to move call to `ufn.GetNotificationCulture...` on overview to after the redirect to `PatientDetails` for draft notifications.

NTBS-723: Audit qa markups

---

ntbs-service/DataMigration/NotificationMapper.cs

After discussing it with Alex we came to conclusion that views in migration does not clean the data but just display it. And we do have "bad_data" queries that highlight issues. So the easiest way would be not to pull total number of countries when visitor/travel is 0/null.

NTBS-792: Do not pull total number of countries in when visitor/travel is 0

---

ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/DataMigration/NotificationImportHelper.cs
ntbs-service/Program.cs
ntbs-service/Services/LegacySearchService.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/deployments/int.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

Use environment name as a prefix for creating and inserting into importedNotifications table

NTBS-793: Use environment name as a prefix for imported notifications table

---

.idea/.idea.ntbs/.idea/sqldialects.xml
ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/DataMigration/NotificationMapper.cs

Follow up review from #298. Covers adding SocialRiskFactors to the NotificationMapper
Ran the migration against 3 different notifications with various statuses and checked the 4 affected tables (SocialRiskFactors, RiskFactorHomelessness, RiskFactorImprisonment, RiskFactorDrugs) were all populated correctly.
**One thing that didn't work was the INSERT into the ntbs-migration table DevImportedNotifications as the credentials have read-only access. Do we want to change this?**

NTBS-680: Add SocialRiskFactors to NotificationMapper

---

ntbs-service/Pages/Search/Index.cshtml.cs

The dynamic objects that came from migration database were causing the enum to be an ordered partition at run time instead of an enum. They also weren't being mapped properly until later in the code (after access was calculated) and were discarding the results of the authorise function.

NTBS-NONE enumerate notificationsToDisplay

---

ntbs-service/Models/Entities/Alert.cs
ntbs-service/Models/Entities/TransferAlert.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Alerts/TransferRequest.cshtml
ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/Pages/Alerts/_CancelTransferConfirmation.cshtml
ntbs-service/Pages/Alerts/_TransferPendingPartial.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Services/AlertService.cs
ntbs-service/Services/AuthorizationService.cs
ntbs-service/wwwroot/source/Components/CascadingDropdown.ts
ntbs-service/wwwroot/source/Components/FilteredDropdown.ts
ntbs-service/wwwroot/source/Components/NhsNumberDuplicateWarning.ts
ntbs-service/wwwroot/source/Components/ValidatePostcode.ts
ntbs-service/wwwroot/source/helpers.ts

List of QA markups to fix:
If no case manager is selected, the alert is displayed on the homepage with ‘System’ showing as the case manager. (Likewise when the user opens the alert). Should just display nothing.
On the ‘pending transfer’ screen (i.e. on the view of the alert), the free text associated with the reason ‘other’ is not displayed.
The receiving case manager cannot view the transfer alert on the notification overview, unless they happen to be able to edit the notification already.
The case manager can set up a transfer into the service that the case is already in.  This was not excluded in the requirements, i.e. it’s my fault.
After cancelling a transfer, the user is only able to go back to the home page. This is what the sketch said, but isn’t consist with the behaviour when …

NTBS-398 qa mark ups

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

Hide "new notification for this patient" button for notifications under a year old.

NTBS-726 hide button when notification under year old

---

ntbs-service/Models/Entities/SpecimenPotentialMatch.cs
ntbs-service/Pages/LabResults/Index.cshtml.cs
ntbs-service/Pages/LabResults/_labResultsDemographics.cshtml
ntbs-service/Services/SpecimenQueryHelper.cs
ntbs-service/Services/SpecimenService.cs

Add TB Service 'field' to demographics view to give a pre-match indicator that the match might fail for permissions - this was raised by developer during dev cycle but decided not to implement, then requested as QA.
Correct audit messages.

NTBS-381: Fix audit and add TbService name to potential match partial

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Pages/Alerts/TransferRejected.cshtml
ntbs-service/Pages/Index.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml.cs
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs

Remove Group on modelBase and use NotificationGroup where possible
Filter alerts on home page

NTBS 742 and 296 markups

---

ntbs-service-unit-tests/Pages/SearchPageTest.cs
ntbs-service/Helpers/NotificationExtensionMethods.cs
ntbs-service/Models/NotificationBannerModel.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Notifications/UnauthorizedWarning.cshtml
ntbs-service/Pages/Search/Index.cshtml.cs
ntbs-service/Pages/Shared/_NotificationBanner.cshtml
ntbs-service/Services/AuthorizationService.cs

Await changes to banner models which need to be completed before rendering the page.
Flip 'ShowPadlock' logic to accurately reflect the naming convention.
Add missing 'tab title' for unauthorised page which was originally showing ~"- ntbs service" .

NTBS-812: Search/padlock issues

---

ntbs-service/Properties/launchSettings.json

@conorsheehansw @ffarmanov @ChristianMcc how would you feel about this change? It would stop the browser from auto-launching on each service restart.
(I have a vague recollection of doing this once before, so not sure if those changes got wiped or actually never merged, or whatnot)

Stop browser from launching on service start in dev

---

ntbs-service/Models/Entities/Alert.cs
ntbs-service/Models/Entities/TransferAlert.cs
ntbs-service/Models/Entities/TransferRejectedAlert.cs
ntbs-service/Models/Entities/UnmatchedLabResultAlert.cs
ntbs-service/Models/Enums/AlertType.cs
ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/LabResults/Index.cshtml

Give display name to alert type.
Unroll 'nhs-panel' tag helper, to allow anchoring to an awkwardly absolutely positioned (outside of the parent div) heading.
Revise alert description to new proposed text
Change default alert rendering of empty case manager as per Nancy's request - confirmed via slack.

NTBS-428: Unmatched lab result alerts QA markups

---

ntbs-service-unit-tests/Models/Entities/TravelAndVisitorDeatilsTest.cs
ntbs-service/Models/Entities/TravelDetails.cs
ntbs-service/Models/Entities/VisitorDetails.cs
ntbs-service/Models/Validations/ValidationHelper.cs

Post migration trial the validation was found to be overly scrutinous. The requested changes:
Yes followed by everything else blank is valid. In particular, total number of countries and first country are not strictly required
If any country is supplied, then total number of countries becomes required
Yes + Total number of countries as the only filled in field is valid
Each duration is optional, but can only by supplied together with a corresponding country

NTBS-857 relax travel validation

---

ntbs-service/DataAccess/AlertRepository.cs

Draft alerts were normally hidden  - draft data quality alerts want to not be hidden and are an exception to this rule.

NTBS-377 make draft quality alerts visible on homepage

---

ntbs-migration-tests/NotificationImportTest.cs
ntbs-service-unit-tests/Models/Entities/PatientDetailsTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/ManualTestResult.cs
ntbs-service/Models/Entities/ModelBase.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/PatientDetails.cs
ntbs-service/Models/Entities/SocialContextBase.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Models/Validations/ValidationAttributes.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/ManualTestResult.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/SocialContextBase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Services/ValidationService.cs

Make dates older than 2010 valid for legacy notifications.
Relax Legacy notifications' postcode validation to regex only, instead of enforcing a match with current list.
Dynamic validation included for both.

NTBS-854 relax validation for legacy notifications

---

ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

This change is done in response to the scenario of calling `kubectl apply uat.yml` directly,
rather than through the release script (which follows it up with `kubectl set image ...`). It had the following adverse effects:
- the newest version of code got released to uat
- from that point onwards uat auto-updated to the newest image, until the release script got used again
This was caused by the fact that:
- `ntbscontainerregistry.azurecr.io/ntbs-service` implicitly described the tag `ntbs-service:latest`
- we have `imagePullPolicy: Always` set on the definitions (and it is also the default behaviour for `latest` tags)
The change in this commit should stop this behaviour by giving each environment a non-existent image to pull in as the baseline. That way if `apply` is called, the new …

Set deployment definition images away from `latest`

---

ntbs-service/Models/Entities/ModelBase.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Services/ValidationService.cs

The shadowing, rather than overriding the property, was causing the validation to work wrongly on the notification model directly
On-screen approved by @conorsheehansw

NTBS-854 Fix dynamic validation for Notification date

---

ntbs-service/Startup.cs

Add event handler to handle stale logins more cleanly. 
If login is stale and user is authenticated this will navigate to the landing page (unfortunately couldn't route to their original intended location).
If login is stale and user is not authenticated this will attempt to navigate to the landing page and force them through another challenge.

NTBS-674: Correlation error fix

---

ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

As a late change in working of my previous ticket... I swapped v-on:click to :click which not only is the correct shorthand for v-on (being @click), but even the correct shorthand doesn't work for some reason.
This is reverting that change.

NTBS-359: Remove incorrect non-working vue shorthand

---

ntbs-service/Services/NotificationClusterService.cs

As missing comma to query.
Would have been tricky to pick up in local testing due to the int-reporting view not having notifications that match with my local version e.g. 1007 etc.
For anyone's interest it considered the second 'select field' as an alias for the first in the absence of a comma.

NTBS-835: Add missing comma

---

ntbs-service/Pages/LegacyNotifications/Index.cshtml.cs

NTBS-565: Navigate to notification view from legacy view if imported

---

ntbs-service/DataAccess/DrugResistanceProfileRepository.cs

Use vwChangesToDRPSpecies view instead of Reusable notifications table

NTBS-368: Use View instead of Reusable notifications table

---

ntbs-service/Pages/Shared/_Footer.cshtml
ntbs-service/wwwroot/css/fonts/_govukFontHandler.scss
ntbs-service/wwwroot/css/site.scss

Add govuk font handler to prevent gets to font woff files which we aren't using.
Remove govuk-footer class with crest background preventing unnecessary get (and 404).

NTBS-910: Fix css sourced network 404 issues

---

ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/LabResults/Index.cshtml
ntbs-service/ntbs-service.csproj
ntbs-service/wwwroot/css/_colors.scss
ntbs-service/wwwroot/css/labResults.scss
ntbs-service/wwwroot/css/search.scss
ntbs-service/wwwroot/css/site.scss
ntbs-service/wwwroot/css/table.scss
ntbs-service/wwwroot/css/testResults.scss

Adjust selectors to be more page specific and add styling for a full width container for the draft section on the landing page.

NTBS-590: Add full width background for drafts on landing page

---

ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_TreatmentEvent.cshtml

Added hidden inputs for TbServiceCode and CaseManagerUsername on treatment event page so that the data is persisted through saves.

NTBS-400 persist TbServiceCode and CaseManagerUsername on treatment events

---

ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-service/wwwroot/source/Components/DateComparison.ts

Also make the clinical date warnings display on mount

NTBS-779 remove clinical date warnings for death date

---

ntbs-service/Models/Entities/RiskFactorDetails.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/Edit/_RiskFactorPartial.cshtml

Backing value now being nullable could not be represented by a checkbox.
Resulting behaviour is tricky to explain concisely, but it was very non-working. Not sure how it got past my manual testing, but it did.
Adding the coalesced property is the neatest solution we could come up with.

NTBS-772: Use a coalesced view property for risk factors

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/ComorbidityPageTests.cs
ntbs-integration-tests/NotificationPages/DeletePageTests.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/HospitalDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/ManualTestResultEditPagesTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-integration-tests/NotificationPages/PatientPageTests.cs
ntbs-integration-tests/NotificationPages/PreviousHistoryPageTests.cs
ntbs-integration-tests/NotificationPages/SocialContextAddressEditPageTests.cs
ntbs-integration-tests/NotificationPages/SocialContextVenueEditPageTests.cs
ntbs-integration-tests/NotificationPages/SocialRiskFactorPageTests.cs
ntbs-integration-tests/NotificationPages/TestResultsPageTests.cs
ntbs-integration-tests/NotificationPages/TravelPageTests.cs
ntbs-integration-tests/NotificationPages/TreatmentEventsEditPageTests.cs
ntbs-integration-tests/TestRunnerBase.cs
ntbs-integration-tests/TransferPages/ActionTransferPageTests.cs
ntbs-integration-tests/TransferPages/RejectTransferPageTests.cs
ntbs-integration-tests/TransferPages/TransferPageTests.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_HospitalDetailsOverviewPartial.cshtml

Include dropdown menus for hospital and case manager that the notification will be sent to upon transfer. Hospital cannot be null while case manager can.

NTBS-865 allow user to specify target hospital and case manager for transfers

---

ntbs-integration-tests/SearchPage/SearchPageTests.cs
ntbs-service-unit-tests/Services/NtbsSearchBuilderTest.cs
ntbs-service/Models/SearchParameters.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Services/LegacySearchBuilder.cs
ntbs-service/Services/NtbsSearchBuilder.cs

Description
Allow spaces when searching by id in the frontend but remove them before searching by ids/nhs number
Checklist:
[X] Automated tests are passing locally.
[X] Sanity checked new EF-generated queries for performance.

NTBS-747 allow spaces when esraching by id and nhs number

---

ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Migrations/20200217110606_RenameCaseManagerTbServiceString.Designer.cs
ntbs-service/Migrations/20200217110606_RenameCaseManagerTbServiceString.cs
ntbs-service/Models/Entities/TransferRejectedAlert.cs
ntbs-service/Pages/Alerts/TransferRejected.cshtml
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs

Add a function to search userByUsername, fix transfer rejection alerts to use current user (and not current case manager as the user isn't necessarily a case manager).

NTBS-865 fix declining transfer alerts for non case managers

---

ntbs-service/Pages/Notifications/NotificationEditModelBase.cs

Simple fix to not use RedirectAfterSaveForNotified for submission so that an anchor isn't added to the redirect.

NTBS-929 fix routing to not use anchor when submitting a notification

---

ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Index.cshtml

Okay'd with Nancy to just add the column and not fiddle with any min-width styling on columns to stop any wrapping. Idea is to reduce the longer TB service names in the future
- [Z] Check the feature looks and works correctly in IE11

NTBS-888 add patient name to the notifications table on home page

---

ntbs-service/Models/Entities/MBovisExposureToKnownCase.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/Items/MBovisExposureToKnownCase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/NewMBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/MBovisExposureToKnownCases.cshtml
ntbs-service/Pages/Shared/_MBovisExposureToKnownCaseTable.cshtml

Ensure casing of M. bovis is consistent (and to spec).
Collapse m. bovis other cases table into a single body row.
Add validation to prevent adding the current notification as the mbovis exposing notification.

NTBS-931: QA markups

---

ntbs-service/Program.cs
ntbs-service/appsettings.json
ntbs-service/ntbs-service.csproj

Add a sentry project integration to capture issues long term and not have to rely on logs being present in the containers.
Verified to capture issues in hangfire jobs, too

Add Sentry and configure it cooperating with Serilog

---

ntbs-integration-tests/NtbsWebApplicationFactory.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.CI.json
ntbs-service/appsettings.Test.json
ntbs-ui-tests/SeleniumServerFactory.cs

Also rename the environment variable from Test to CI to make it clearly distinct from the running TEST environment

Disable Sentry in CI

---

ntbs-integration-tests/Helpers/WebApplicationExtensions.cs

This is in response to integration tests getting flaky on the Jenkins build, following a suggestion on https://github.com/dotnet/aspnetcore/issues/12998#issuecomment-557330077
If this doesn't help, we might be facing some sort of deadlock between the tests..
(or jenkins just slow)

Increase integration tests client timeout

---

ntbs-service/Startup.cs

Lower logging level of request logging to information, in order to prevent Sentry being inundated with duplicate exceptions.

NTBS-NONE: Adjust logging level of request logging

---

ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml

Fix how treatment outcomes are shown on overview page (show if age eligible)

NTBS-936 show treatment outcomes with correct logic regarding age

---

EFAuditer/EFAuditServiceExtensions.cs

Audit logs save enums as strings

NTBS-957: Use EnumToStringConverter for Audit logs

---

ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-service/wwwroot/source/Components/DateComparison.ts

Only show "X is earlier than Y" date warnings instead of both that and "Y is later than X" warnings.

Ntbs 733 only show date warnings in one direction

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Pages/Search/Index.cshtml.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/SearchService.cs

Use base queryable for retrieving NTBS notification ids - as the include statements are completely redundant if the final select statement is `n => n.NotificationId`.
Explicitly locally load notification sites as some of the expressions are not translatable, so are running locally anyway.

NTBS-983 & NTBS-982: Fix LINQ warnings

---

ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Services/ValidationService.cs

Directly solves an issue where a value of "1.5" was failing with an argument exception when attempting to convert to an integer.

NTBS-984: Adjust validation logic to allow for non-convertible types

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Services/TreatmentOutcomeService.cs

Order treatment events on the same day so that non outcomes are more recent than outcome events.

NTBS-454 order treatment events on the same day 

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/TransferPages/ActionTransferPageTests.cs
ntbs-integration-tests/TransferPages/RejectTransferPageTests.cs

I couldn't find any 'generated id' style flaws in our testing but did have a problem with a transfer rejection test - this has now been fixed.
Also changed some of the basicEditPages to not be async as they are no longer using await but .Result in a foreach loop.

Ntbs 961 integration tests clean up

---

ntbs-service/Helpers/TreatmentEventsExtensionMethods.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs
ntbs-service/Pages/Shared/_TreatmentEventTable.cshtml

Fix ordering of treatment events again.
allow death events before notification date for post mortem cases

Ntbs 936 death event and ordering

---

ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Models/SeedData/TreatmentOutcomes.cs

Fix adding death events for post-mortem legacy notifications

Ntbs 1017 qa markups

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20200326150653_FixRelationshipTypeToPostcodes.Designer.cs
ntbs-service/Migrations/20200326150653_FixRelationshipTypeToPostcodes.cs
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml.cs
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs

NTBS-1061 Make notification->postcode mapping many to one
This was implicitly creating a uniqueness expectation, which was creating issues on notifications which shared the same postcode.

Ntbs 1061 fix postcode mapping issue

---

ntbs-service/Pages/Notifications/LinkedNotifications.cshtml
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml.cs
ntbs-service/Pages/Shared/_NotificationUnderBannerNav.cshtml

NTBS-1060: Allow navigate to draft notifications on LinkedNotifications page

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataAccess/NtbsContextDesignTimeFactory.cs
ntbs-service/Migrations/20200402094217_moveReferenceDataToOwnSchema.Designer.cs
ntbs-service/Migrations/20200402094217_moveReferenceDataToOwnSchema.cs
ntbs-service/Migrations/20200402095659_removeUnusedRegionModel.Designer.cs
ntbs-service/Migrations/20200402095659_removeUnusedRegionModel.cs
ntbs-service/Models/ReferenceEntities/Region.cs
ntbs-service/Program.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/deployments/int.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml
ntbs.sln.DotSettings

This change is best described by the comment I added to the ntbsContext:
> Note: we've adopted a convention where reference data lives in a separate schema to the main tables.
This allows us to set different permissions easily, to avoid accidental reference data interference.
We define reference data as data not directly manipulated by the application. It wants to be authored by the
business rules, rather than by the users.
In practice it mainly correlates with tables for which we seed code-first values through the HasData mechanism
Whilst here I've also moved to a more manageable secrets model, where kubernetes will have a single secret object for all connection strings (per env), differentiated by keys.

NTBS-1066 move reference data to own schema

---

ntbs-service/Services/NotificationCloningService.cs

NTBS-1281: Set GroupId to null on cloned notification

---

ntbs-integration-tests/NotificationPages/TravelPageTests.cs
ntbs-service-unit-tests/Models/Entities/TravelAndVisitorDeatilsTest.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs

I've taken this opportunity to shift some of the validation tests from integration to unit.
I think this is a reasonable scheme to follow going forwards:
- unit tests for different validation cases that the models should support
- one test in integration suit to ensure errors get wired up correctly in the html
- otherwise integration tests covering only areas that unit tests can't, such as direct controller behaviour (e.g. here, clearing the validation state correctly)
@ffarmanov let me know what you think! :)
P.S. The shift of tests and the actual bug fix (together with its new test) are in separate commits!

NTBS-1007 clear travel visitor data bug

---

ntbs-service/Helpers/NotificationExtensionMethods.cs
ntbs-service/Pages/Alerts/TransferRejected.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/LabResults/Index.cshtml.cs
ntbs-service/Pages/Messages.cs
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisAnimalExposure.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisExposureToKnownCase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisOccupationExposure.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisUnpasteurisedMilkConsumption.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/ManualTestResult.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/SocialContextBase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml.cs
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/UnauthorizedWarning.cshtml
ntbs-service/Pages/Shared/_NotificationOverviewLayout.cshtml
ntbs-service/Services/AuthorizationService.cs
ntbs-service/wwwroot/css/notification.scss
ntbs.sln.DotSettings

(Commit-by-commit might be useful, as one of them is quite noisy!)

NTBS-1054 Surface reason for edit restrictions

---

ntbs-integration-tests/NotificationPages/NotificationSummaryTests.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Admin/CloneNotification.cshtml
ntbs-service/Pages/NotificationSummary.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MDRDetailsOverviewPartial.cshtml
ntbs-service/wwwroot/source/Components/NotificationWarning.ts
ntbs-service/wwwroot/source/Components/ValidateRelatedNotification.ts
ntbs-service/wwwroot/source/app.ts

Display Notification Not found information when ntbs id is not found for related notification id.

NTBS-1062: Display Notification Not found information when ntbs id is not found

---

ntbs-integration-tests/NotificationPages/MBovisExposureToKnownCasesPageTests.cs
ntbs-integration-tests/NotificationPages/NotificationSummaryTests.cs
ntbs-service/Models/Entities/MBovisExposureToKnownCase.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisExposureToKnownCase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_MDRDetailsOverviewPartial.cshtml

NTBS-1045: Allow to save MdrDetails and Mbovis with valid related notification ID but in NTBS

---

ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Models/Validations/ValidationHelper.cs

There `IsLegacy` attribute helps control validation for items where we've relaxed it a little bit for legacy items.
It is set by `SetValidationContext`, which works properly in the case of editing pages, but it actually hasn't been called for models during the validation for import. This attempts to fix that.

Ntbs 1064 fix setting is legacy during import

---

ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml

NTBS-1265: Show Treatment outcome subtype in Notification Overview page

---

ntbs-service-unit-tests/Services/TreatmentOutcomeServiceTest.cs
ntbs-service/Services/TreatmentOutcomeService.cs

The changes in this codebase are only one part of the review!
See also:
* Commit in the reporting DB: https://github.com/PublicHealthEngland/ntbs-reporting/commit/a34a0d582ac4f941e39faf6d799bf5cfb109ecb1
* New section about the order of events in the documentation: https://airelogic-nis.atlassian.net/wiki/spaces/R2/pages/599687169/Outcomes+logic#Events-order
@aptemus I was hoping in particular you could review the documentation, to make sure that you're happy with the new order. All of the previously established examples were turned into unit tests, and everything is passing, but not many of them considered events on the same day. I want to make sure we don't need this ordering to be any more nuanced.

NTBS-1347 Set order of treatment events on the same day

---

ntbs-service/Pages/Notifications/OverviewPartials/_PatientOverviewPartial.cshtml

NTBS-1439: Display both ets and ltbr Id as legacy ids

---

ntbs-service/Services/LegacySearchBuilder.cs

The lack of parenthesis in the correct place for the search parameters meant that in a situation where:
- an LTBR record, say 123-1 was imported ...
- ... and correctly marked as imported in the migration db
- by searching for id '123-1' the legacy record would (correctly) not show up
- but by searching for id '123' both the imported and the legacy record would be returned

NTBS-1441 Fix wrong filtering of legacy cases in search

---

ntbs-migration-tests/NotificationImportTest.cs
ntbs-service/DataMigration/MigratedNotificationsMarker.cs
ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/DataMigration/NotificationImportHelper.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Jobs/HangfireJobScheduler.cs
ntbs-service/Jobs/MarkImportedNotificationsAsImportedJob.cs
ntbs-service/Pages/Health.cshtml
ntbs-service/Properties/ScheduledJobsConfig.cs
ntbs-service/Services/LegacySearchService.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.json

The main aim of this ticket is to provide a way to update the importedNotifications table(s) after the actual import process. It tries to solve the problem of a notification importing correctly, but failing to make a record of that fact in the migration db. There's not really a way to *prevent* that as such without having a cross-db transaction! So, instead, we're providing a clean-up job, that can:
a) be run at the end of the bulk migration at cutover; and
b) be scheduled to run periodically.
Because it's not actually possible to run this job locally (see comments in code for what causes this limitation), I've only tested the actually SQL query by hand so far. So there are a few more things to finish off - see checklist below - but I think it's a good point to have the code reviewed! …

Ntbs 1440 migration cleanup job

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataMigration/ImportLogger.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Migrations/20200708110716_AddUniquenessIndeciesOnLegacyIds.Designer.cs
ntbs-service/Migrations/20200708110716_AddUniquenessIndeciesOnLegacyIds.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Admin/Migration.cshtml
ntbs-service/Pages/Admin/Migration.cshtml.cs
ntbs-service/Properties/MigrationConfig.cs
ntbs-service/appsettings.json
ntbs-service/deployments/dev.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/uat-phe.yml
scripts/migration/README.md

Fixes amounted to:
- eliminating overlap from the dates looked at by the jobs created by date-based bulk migration. Thus reducing the risk that two jobs will even attempt to import the same value in
- Reducing the responsibility of jobs from 2-month periods to single days. This should make the jobs much less long-running, reducing the risk of unfortunate timing of uniqueness checks whislt things are held in-memory.
- setting up uniqueness indexes on the legacy id columns (a belts-and-braces approach)

Ntbs 1633 fix duplicates being pulled in

---

ntbs-service/DataAccess/NtbsContextDesignTimeFactory.cs
ntbs-service/Properties/AdfsOptions.cs
ntbs-service/Properties/AzureAdOptions.cs
ntbs-service/README.md
ntbs-service/Services/AzureAdDirectoryService.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.json
ntbs-service/deployments/int.yml

Added support for Azure AD authentication for int.

Ntbs 1858 - Added support for Azure AD to NTBS

---

ntbs-service-unit-tests/Helpers/NameFormattingHelperTest.cs
ntbs-service/Helpers/NameFormattingHelper.cs
ntbs-service/Services/AzureAdDirectoryService.cs
ntbs-service/Services/UserService.cs

Changes for NTBS-2055
* Add a display name formatting helper to remove long trust names from display names retrieved from Azure AD
* Add some unit tests for this helper
* Use this when formatting the user name in the website header
* Use this when populating the User table in the regular sync job
* Add a fallback to use given and family names as a display name if there is no display name present (which is the case for some legacy users)

NTBS-2055 Update display name formatting

---

ntbs-service-unit-tests/Services/DrugResistanceProfileServiceTest.cs
ntbs-service/Helpers/DrugResistanceHelper.cs
ntbs-service/Jobs/DrugResistanceProfileUpdateJob.cs
ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs
ntbs-service/Services/DrugResistanceProfileService.cs

Set a limit on the number of notifications that will be processed on one run of the drug resistance profile import.
If there are more updates required than this then log a warning in sentry.

NTBS-2034 Limit the number of Notifications updated per run

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-service-unit-tests/Services/CaseManagerSearchServiceTest.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/DataAccess/UserRepository.cs
ntbs-service/Models/Entities/Alerts/Alert.cs
ntbs-service/Models/Entities/HospitalDetails.cs
ntbs-service/Models/Entities/User.cs
ntbs-service/Pages/Admin/CloneNotification.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/Pages/ContactDetails/Edit.cshtml
ntbs-service/Pages/ContactDetails/Index.cshtml
ntbs-service/Pages/ContactDetails/Index.cshtml.cs
ntbs-service/Pages/ContactDetails/_CaseManagerDetailsPartial.cshtml
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml
ntbs-service/Pages/ServiceDirectory/Region.cshtml
ntbs-service/Pages/ServiceDirectory/SearchResults.cshtml
ntbs-service/Services/CaseManagerSearchService.cs

* Use the display name field from the User table in all situations that a case manager name is required on the front end.
* Update service directory to search display names, and tolerate null given or family names.
* Update alert testing to use case manager display name.

NTBS-2054 Use display name instead of given and family names

---

ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Jobs/DataQualityAlertsJob.cs
ntbs-service/Models/QueryEntities/NotificationAndDuplicateIds.cs

Update the notification duplicate check to use raw sql for performance reasons.
There were not any existing tests for this job, and because our 'integration' tests use an in-memory database we wouldn't be able to test the relevant logic here, so I haven't added any :-(

NTBS-2107 Use explicit SQL in duplicate notification check

---

ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Pages/ServiceDirectory/Region.cshtml.cs

Use `User.DisplayName` to order lists of case managers instead of `User.FamilyName` which might be `null` when using Azure AD.

NTBS-2054 Use display name for case manager sorting

---

ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/webpack.common.js
ntbs-service/wwwroot/css/site.scss

CSS loader does not seem to be working with public paths for CSS
url(...) functions, so instead use a local path at build time (so
assets are inlined into the CSS at build time by url-loader, unless
they are larger than 10 KB where they are then served by file-loader).

NTBS-1768 Fix CSS loading of asset URLs

---

ntbs-service-unit-tests/Services/NtbsSearchBuilderTest.cs
ntbs-service/Services/LegacySearchBuilder.cs
ntbs-service/Services/NtbsSearchBuilder.cs

Trim the name inputs when searching for a notification (ntbs and legacy) and added matching tests.
We already do this for other fields where we input text (postcode and ID) by removing all whitespace.

NTBS-1642: Trim name inputs when searching

---

ntbs-service/wwwroot/source/app.ts

Because the hot reloading module has been removed the app.ts script was throwing with a "function is undefined" error. This meant that the subsequent call to initialise the govuk javascript was not happening, and all of the responsive components were not working.

NTBS-1768 Fix js loading issue

---

ntbs-service/Middleware/ActivityDetectionMiddleware.cs
ntbs-service/Middleware/AuditGetRequestMiddleware.cs

When comparing request paths, do so in a case insensitive way.

NTBS-2093 Compare paths case-insensitively

---

ntbs-service-unit-tests/DataMigration/ClusterImportTest.cs
ntbs-service/DataAccess/NotificationClusterRepository.cs
ntbs-service/DataMigration/ClusterImportService.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Jobs/NotificationClusterUpdateJob.cs
ntbs-service/Services/MockNotificationClusterService.cs
ntbs-service/Services/NotificationClusterService.cs
ntbs-service/Startup.cs

When importing a notification:
- Check in the reporting database to see if there is a cluster assigned to the ETS ID of the notification
- If there is:
- Add the cluster to the notification
- Update the entry in the reporting database to refer to the new Notification ID rather than the ETS ID

Ntbs 2049 import cluster data

---

ntbs-integration-tests/LabResultsPage/LabResultsPageTests.cs
ntbs-service/Pages/LabResults/Index.cshtml
ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/webpack.common.js
ntbs-service/wwwroot/css/_colors.scss
ntbs-service/wwwroot/css/labResults.scss
ntbs-service/wwwroot/css/site.scss

Upgrade to NHS frontend version 4. Also included are fixes for a couple of minor bugs produced by the NPM package upgrade (NTBS-1768) which were spotted during testing this
* Upgrade to NHS frontend v4: Replace the unmatched specimen panel in the lab results page with a similar care card, because panels were removed in the NHS frontend v3 -> v4 upgrade.
* Update the forked NHS frontend tag helper submodule to use the version updated for v4.
* Fix header fonts after changing CSS loader version 
* Fix webpack builds for IE11 (the way that we tell it to target IE11 has changed, though the transpilation mechanism itself wasn't really affected by the webpack v4 -> v5 upgrade). 
For the new specimen card

NTBS-2091 NHS Frontend upgrade

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-service-unit-tests/Services/AlertServiceTest.cs
ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Jobs/DataQualityAlertsJob.cs
ntbs-service/Migrations/20210223122109_MoveTbServiceAndCaseManagerToTransferAlert.Designer.cs
ntbs-service/Migrations/20210223122109_MoveTbServiceAndCaseManagerToTransferAlert.cs
ntbs-service/Models/Entities/Alerts/Alert.cs
ntbs-service/Models/Entities/Alerts/AlertWithTbServiceForDisplay.cs
ntbs-service/Models/Entities/Alerts/TransferAlert.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/Alerts/_TransferPendingPartial.cshtml
ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/Index.cshtml.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Services/AlertService.cs
ntbs-service/Services/AuthorizationService.cs

- The filtering of alerts is now fixed, we check that the alert is either: not a transfer and for a notification in our service OR is a transfer to our service. The logic for this and for whether a user has permission to manage a notification has been moved to one place.
- The Alert model no longer contains TB Service or Case Manager, these are only used in the case of a Transfer Alert (where we store the new TB Service/Case Manager we are transferring to). This means that the information in the alert table on the dashboard now comes from the related notification.

NTBS-2111: Show alerts to new TB Service users for transferred notification

---

ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml
ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml
ntbs-service/Pages/Shared/_TreatmentEventTable.cshtml
ntbs-service/wwwroot/css/table.scss

Use the new [NHS responsive tables](https://service-manual.nhs.uk/design-system/components/table#3-or-more-column-table) added in v4 for tables with more than 3 columns, as recommended by the design system.
* Fix table captions from NHS v4 update: captions are no longer hidden in NHS v4. We were basically using them as aria-labels, so switch them to be aria-labels. 
* Use responsive tables for tables with more than 3 columns.
* Tweak the table padding CSS to make the table row hover highlighting look nice for narrow-viewport tables.
* Add an updated version of the NHS frontend fork, with responsive table templating added.
<details>
<summary>Dashboard page</summary>
</details>
<details>
<summary>Test results in …

NTBS-2119 Use responsive tables

---

ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml
ntbs-service/Pages/Notifications/Edit/_TravelDetailsPartial.cshtml
ntbs-service/Pages/Search/Index.cshtml
ntbs-service/wwwroot/css/search.scss

Fixing NTBS-2082 and 2085 together because the problems are fairly intertwined, both to do with making sure that semantic HTML is used properly in forms.
Form tweaks to improve accessibility: making sure every form input has
a label, and that subgroups of inputs are in fieldsets, and all
fieldsets have a legend.
This led to some styling tweaks for the search page, because the dates
and sex input groups needed to be put in a form field, but making a
fieldset legend appear inline with its inputs is not as trivial as you
would hope (in particular, flex boxes and form legends do not seem to
play nicely together).

NTBS-2082 and NTBS-2085 field accessibility fixes

---

ntbs-service/Pages/Notifications/Edit/_SpecimenDetails.cshtml
ntbs-service/wwwroot/css/labResults.scss
ntbs-service/wwwroot/css/testResults.scss

Use the new care card introduced in NHS v4 for reference lab specimens on the edit test result page, matching the lab results page formatting for specimens from the reference lab.
This was suggested in QA where the lab result page had been updated to use this new care card formatting.

NTBS-2091 QA fix: Use new specimen care card on test results page

---

ntbs-service/Services/NotificationCloningService.cs

Not sure why this didn't show up before the merge into master, looks like a change in tracking means we needed to detach the notification after navigating to it's properties.

NTBS-2074: Fix notification cloning service for dotnet 5.0

---

ntbs-service/Pages/Index.cshtml

Benji accidentally removed alert type and action from the alert table on index. Not sure how this didn't break any tests - maybe something to look into.

NTBS-2119: Re-add accidentally removed alert details on index

---

ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml

Change to it having its own section header (h2) instead of a small (p)
(p) question label as it was before.
This is such a trivial change (just wrapping a small amount of text in a `<h2>` tag it didn't need a full set of accessibility testing.

NTBS-2085 QA - Fix heading size for post mortem question

---

ntbs-service-unit-tests/Services/UserServiceTest.cs
ntbs-service/Authentication/DummyAuthHandler.cs
ntbs-service/Constants.cs
ntbs-service/Pages/ContactDetails/Menu.cshtml
ntbs-service/Pages/Logout.cshtml.cs
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Properties/AdOptions.cs
ntbs-service/Properties/AdfsOptions.cs
ntbs-service/Properties/AzureAdOptions.cs
ntbs-service/Services/AdDirectoryService.cs
ntbs-service/Services/AdDirectoryServiceFactory.cs
ntbs-service/Services/AzureAdDirectoryService.cs
ntbs-service/Services/AzureAdDirectoryServiceFactory.cs
ntbs-service/Services/UserService.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.CI.json
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.json
ntbs-service/deployments/live.yml
ntbs-service/deployments/uat-phe.yml

Move the AD groups into their own section of the config
Update the deployment files for live and phe-uat to use Azure AD (they're already using it, but the deployment files don't reflect that).

NTBS-2059 Restructure AD config

---

ntbs-service-unit-tests/Services/DrugResistanceProfileServiceTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs

Fixed an issue introduced when upgrading to .NET 5 (well the change was
made in v2 -> v3), where owned entities cannot be queried without the
owner using a tracking query. This has been causing some errors on
Sentry, but should now be fixed.
Fix by adding a notification to the NotificationForDrugResistanceImport
class, instead of just its ID, because this object is owned by the
Notification object.

NTBS-NONE Fix EF ownership issue for drug resistance job

---

ntbs-service-unit-tests/DataMigration/CaseManagerImportServiceTests.cs
ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/DataMigration/CaseManagerImportService.cs
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/DataMigration/RawModels/MigrationLegacyUser.cs
ntbs-service/DataMigration/RawModels/MigrationLegacyUserHospital.cs
ntbs-service/Startup.cs

When migrating a notification, migrate the case manager if they are not already in NTBS. If they are in NTBS then update the name. As migrated "case managers" are not always classed as what we define a case manager to be we have changed the validation logic to check that the user exists in NTBS, if this user is not a case manager then we output a warning but the notification is migrated anyway.

NTBS-2110: Migrate case managers when migrating notifications

---

ntbs-service/Migrations/20191217111302_UpdateSampleTbServiceMappings.cs
ntbs-service/Migrations/20200422211917_AddPCTtoPostcodesTable.Designer.cs
ntbs-service/Migrations/20200422211917_AddPCTtoPostcodesTable.cs
ntbs-service/Migrations/20200604214722_AddAnchorLinkToFAQ.Designer.cs

I have confirmed that we can now run through all the migrations when setting up a new environment.

NTBS-NONE Fix issues with migrations caused by .NET 5 upgrade

---

ntbs-service/deployments/int.yml

Point `int` at a different migration database to the other environments
We will need to make a similar change to the other yml files when we move those environments across.

NTBS-NONE Point int at different migration DB

---

ntbs-service-unit-tests/Services/EnhancedSurveillanceAlertsServiceTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Services/EnhancedSurveillanceAlertsService.cs

This PR is primarily to fix NTBS-1997, but the changes to `CreateOrDismissAlert` should also fix NTBS-1958 for free.
Dismiss a notification's MDR alert when the user fills in its MDR questionnaire. Do this by running `EnhancedSurveillanceAlertsService.CreateOrDismissMdrAlert` after editing the MDR questionnaire.
Modify the `CreateOrDismissAlert` service method to check whether the questionnaire has been filled out when deciding whether to create or dismiss the alert. To do this, also add MDR data to the `NotificationForDrugResistanceImport` projection. This adds in a few fields but hopefully will not have a significant impact on the performance of the `DrugResistanceProfileUpdateJob`.
Amend the `EnhancedSurveillanceAlertsService` tests to cover this new logic.

NBTS-1997 and 1958 Add automatic MDR alert dismissal

---

ntbs-service/Pages/Health.cshtml.cs
ntbs-service/Startup.cs

Stop anonymous access to the Health page, and require Admin user policy, based on security audit advice.

NTBS-2100 Make Health status page for admins only

---

ntbs-service/Startup.cs
ntbs-service/deployments/int.yml

Stop ignoring antiforgery tokens for Hangfire requests. This may cause issues with multiple instances of the app behind a load balancer, if they do not share the same keys, but this should not be the case.
I believe this workaround was added because keys were not shared between instances of an app at the time, but this was added a few weeks later, so should just work now. I've not managed to test this locally, though I think I might be able to give it a go. Otherwise, maybe we could edit one of the running environments to have multiple replicas of the app behind the existing load balancer for testing? I believe the issue that was experienced in the past was that the page was being served by one replica, but the POST requests received by another, and they didn't know how to verify CSRF …

NTBS-2101 Use Antiforgery tokens in Hangfire dashboard

---

ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Services/SpecimenService.cs

Remove remaining Task.WhenAll calls which can cause concurrent database requests.
I don't think there's any reasonable tests that could be written here - the 'behaviour' hasn't really changed, although we now avoid a race condition. I'm also not sure that the bug this fixes would be possible to occur against the in-memory database used by our tests as it wouldn't surprise me if calls to the in-memory database are actually evaluated synchronously.

Ntbs 2146 remove task whenall

---

ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Helpers/SessionStateHelper.cs
ntbs-service/Startup.cs

I have fixed 3 warnings/errors we were getting on sentry due to the .NET upgrade.
Our heartbeat code wasn't checking for null, which meant if we hadn't set a "latest activity time" it would throw an error when trying to compare it. I have set this to default to true.
I have added query splitting where I had missed it previously.
I have fixed a warning about using skip/take without ordering. This one is a sort of "bug" in .NET, where using query splitting results in needing an orderby. (link to issue: https://github.com/dotnet/efcore/issues/23803).

NTBS-2074: Fix sentry warnings

---

ntbs-service-unit-tests/Services/AdImportServiceTest.cs
ntbs-service/DataAccess/UserRepository.cs
ntbs-service/Services/AdDirectoryService.cs
ntbs-service/Services/AdDirectoryServiceFactory.cs
ntbs-service/Services/AdImportService.cs
ntbs-service/Services/AdUserService.cs
ntbs-service/Services/AzureAdImportService.cs
ntbs-service/Startup.cs

If a user is not found in the AD during user sync we set the user as legacy (`isActive = false`) and remove their AD groups.

NTBS-2062: Set users as legacy during user sync job

---

ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

Use separate secrets for the migration database in the `test` and `uat` environments.
In practice their values will be the same most of the time, but the changing collation exercise has proved that it's good to have the flexibility to point them at different databases when we need to.

NTBS-2150 Update yml files for test and uat

---

ntbs-service/Properties/AdOptions.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.json

Use minutes for session cookie timeout config, instead of hours, as discussed today.

NTBS-2102 Use minutes for session cookie timeout config

---

ntbs-service/Startup.cs

Sliding cookie expiration means that an authentication cookie halfway through its life will get replaced automatically when you make a request to the server with this cookie.
This allows an attacker to maintain an authentication cookie forever if they were to steal one. Because of this, we need to turn this feature off.

NTBS-2102 Turn off authentication cookie sliding expiration

---

ntbs-service-unit-tests/Services/EnhancedSurveillanceAlertsServiceTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Helpers/DrugResistanceHelper.cs
ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs
ntbs-service/Pages/Notifications/Edit/MBovisAnimalExposures.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MBovisExposureToKnownCases.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MBovisOccupationExposures.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MBovisUnpasteurisedMilkConsumptions.cshtml.cs
ntbs-service/Services/EnhancedSurveillanceAlertsService.cs

* Check M. bovis questionnaire before raising alert: when raising M. bovis alerts as part of the `DrugResistanceProfileUpdateJob`, check whether the M. bovis questionnaire has been filled out or not. It may have been filled out if this is notification recently migrated from a legacy system, where the questionnaire was filled out there. Note that disease species is not transferred as part of notification migration; it is done by the `DrugResistanceProfileUpdateJob`.
* Check M. bovis questionnaire alert after editing: after editing an M. bovis questionnaire page, check the M. bovis alert status, and auto-remove it if editing this page means that the questionnaire has now been fully filled out.

NTBS-1999 Improve M. bovis alerts

---

ntbs-service-unit-tests/DataMigration/ImportValidatorTest.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/Migrations/20210317174112_ChangeMdrRelationshipMaxLength.Designer.cs
ntbs-service/Migrations/20210317174112_ChangeMdrRelationshipMaxLength.cs
ntbs-service/Migrations/README.md
ntbs-service/Models/Entities/MDRDetails.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/README.md

We were getting a strange error when our character limit was being hit on RelationToCase in MDR details when importing a notification. It turns out that no validation was occurring on MDR Details during import and so the uncaught error happened when we tried to save the notification.
I have now made validation happen on MDR details and increased the length limit of RelationToCase to 90. 
This area should be high priority in terms of adding tests I think, as this bug was meaning a whole section of all imported notifications was missing validation.
I could add tests as part of this ticket, but it will take some time to mock out the whole notification import service, so depends if we want to spend time at the moment on that or not. 
If the NTBS schema changes, that might affect the related …

NTBS-2161: Fix MDR issue when importing notification

---

ntbs-service/wwwroot/css/notification.scss
ntbs-service/wwwroot/css/search.scss

Now use columns for the headers of the notification banner if we zoom in further than the banner container can handle.
Also change the width of the tb service and country field in advanced search to avoid horizontal scrolling at 400%. 
Tested on IE11, Mozilla and Chrome.

NTBS-2086: Fix search page and notification overview banner issue

---

ntbs-service/Pages/Notifications/Edit/_TravelDetailsPartial.cshtml

Remove extra label that was accidentally committed.

NTBS-2174 Remove extra label

---

ntbs-integration-tests/NtbsWebApplicationFactory.cs
ntbs-integration-tests/TestRunnerBase.cs
ntbs-integration-tests/TransferPages/ActionTransferPageTests.cs
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20210323115845_RemoveSequence.Designer.cs
ntbs-service/Migrations/20210323115845_RemoveSequence.cs

This is a change that I think would be good for the project - using a Sqlite database instead of the in memory database we currently use.
The main advantages are:
* The implementation is closer to that of a MSSQL database
* It will support testing of the raw SQL queries that we use in some places
The main disadvantages are:
* It doesn't support sequences. However, I don't consider this to be a deal-breaker because we only had one, for the FAQs page, and it really isn't necessary.
* It may cause the tests to run more slowly. I've tested this locally and it doesn't make much difference, but there's definitely a possibility that it will make more difference on whatever server github uses. If this is the case, then I'll revert the change.

NTBS-NONE Use Sqlite instead of in memory database in tests

---

ntbs-ui-tests/Hooks/DriverSetup.cs
ntbs-ui-tests/Hooks/TestSettings.cs

Add an implicit wait timespan to Selenium tests; which tells Selenium to wait some time before claiming an element is not on the page. This gives some time for JS to modify the page from the previous step, making JS much more likely to win its race against Selenium.
I was having issues with the "Fill in M. bovis occupation exposure page" scenario even though no relevant changes had happened recently. The issue was as described above, Selenium was not giving JS enough chance to add the "add-new-button" to the page before failing the test, but they now all work.

NTBS-NONE Reduce the likelihood of a race in Selenium tests

---

ntbs-service-unit-tests/DataMigration/CaseManagerImportServiceTests.cs
ntbs-service/DataMigration/CaseManagerImportService.cs
ntbs-service/DataMigration/NotificationImportService.cs

When attempting to import legacy notifications we were sometimes getting foreign key errors. This was due to case managers for a notification's transfer events not being present in NTBS.
This issue was spotted by Nancy in live data - where some legacy notification contain transfer events with case managers. All the ntbs migration legacy data has null case managers for transfer events.
Now import all case mangers relating to a legacy notification's transfer events.

NTBS-2171: Import treatment event case managers during migration

---

.github/pull_request_template.md
ntbs-service/Migrations/README.md

Based on a conversation with Nancy:
When we change the NTBS schema, we need to update the specimen matching DACPAC as well as the reporting DACPAC. Add this fact to the PR template and EF migration README.

Add specimen matching DACPAC to PR template

---

ntbs-service/Migrations/20210323082014_ReseedNotificationTable.cs

I realised that the previous migration would not have worked for an empty database, because `last_value` would have been `NULL` and in SQL, `NULL < 300000` is `false`.
I've gone for a "revise history" approach, because this migration is equivalent to the previous one on all databases where it has been run. The only difference would be if we applied the migrations to a new database.

NTBS-2150 Correct the migration for an empty database

---

ntbs-integration-tests/NotificationPages/MBovisAnimalExposurePageTests.cs
ntbs-integration-tests/NotificationPages/MBovisExposureToKnownCasesPageTests.cs
ntbs-integration-tests/NotificationPages/MBovisOccupationExposurePageTests.cs
ntbs-integration-tests/NotificationPages/MBovisUnpasteurisedMilkConsumptionPageTests.cs
ntbs-service/Services/NotificationService.cs

* Fix _M. bovis_ questionnaire saving: this was broken in NTBS-2168, #1135, and is now fixed.
* Regression tests for saving _M. bovis_ questionnaire forms. When a regression test saves an _M. bovis_ form, the pages are then checked to see that the submitted changes have actually been saved.

NTBS-2168 Saving M bovis questionnaire bugfix

---

ntbs-service/README.md
ntbs-service/appsettings.Development.json

I have set up the local databases and done a quick regression test, including all hangfire jobs. Everything appeared to be working except for the `ReportDataProcessingJob` which requires the `ReportServer` database, hence why I have disabled that job in the `appSettings`. (That job relates to the SSRS reports, and so may be removed soon anyway).

NTBS-2196 Point development environment at local dbs by default

---

ntbs-service-unit-tests/Services/EnhancedSurveillanceAlertsServiceTest.cs
ntbs-service/Helpers/DrugResistanceHelper.cs
ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs

Show _M. bovis_ questions if the notification has `Species = 'M. bovis'`, or if any of the _M. bovis_ questions have already been filled out.
This reverts the change made in 0be9dc06.

NTBS-2170 Show M bovis questions if data has been entered

---

ntbs-service/Pages/Admin/Migration.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/ServiceDirectory/Index.cshtml
ntbs-service/wwwroot/css/caseManager.scss

* Fix the fieldsets and labels of a few pages, to improve site accessibility. Changes were made to:
* M. bovis exposure to known cases - add case form
* MDR details form
* Import Legacy Notifications form
* Search box and button for Service Directory Search
* Fix search button for narrow screens: the search button style for narrow screens is different to what we need, it is larger and green. We are not really using the button in the context that is written for. Instead, make our own search button style based on the NHS search button style, without the unwanted style change for narrow screens.

NTBS-2184 fieldsets and labels fixes

---

ntbs-service/wwwroot/source/app.ts

We should add the NHS polyfills, else components will break in IE11. This is part of the [instructions for setting up the NHS frontend](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/installation/installing-with-npm.md#option-2-import-javascript-using-modules) but this had been missed until now.

NTBS-2216 Add the NHS polyfills

---

ntbs-service-unit-tests/Helpers/EpisodesHelperTest.cs
ntbs-service/Helpers/EpisodesExtensionMethods.cs
ntbs-service/Models/PaginationParametersBase.cs
ntbs-service/Models/TreatmentPeriod.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml

Visually separate transfer out events from the other treatment events in their period. To this end, make a TreatmentPeriod class that contains a list of events, corresponding to each period on the website. These TreatmentPeriod objects are numbered, and a flag to denote a transfer-out-only period, to be displayed separately but without a number.
Amend unit tests to reflect the new way treatment episodes are grouped.

NTBS-1987 Split transfer events into own period

---

ntbs-service/Helpers/UsernameHelper.cs
ntbs-service/Middleware/AuditGetRequestMiddleware.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Services/AuditService.cs
ntbs-service/wwwroot/source/Components/PrintButton.ts

Now audit when a user prints the notification overview. Added a form wrapping the print button (so that the request verification token exists) and also changed the nhs-button to a link tag which is styled as a button (which is documented in the nhs frontend button readme) so that the button didn't submit the form - all the nhs buttons are submit.

NTBS-2180: Audit when users print notification overview

---

ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

Use the route helper for more robust linking between the notification actions overview and the overview page.
Also, improve the way latest linked notification IDs are determined, cover a case for possible nulls and bring the data manipulation out of the view.

NTBS-2199 Improve linked notification hyperlinking

---

ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/DataMigration/NotificationImportService.cs

When migrating in notifications we were logging sensitive information - the notification patient name and potentially the case manager username. I have removed the username from the log message and changed the patient name to initials - I thought that it may be useful to know this if for example you're checking the notification in the database.

NTBS-2099: Anonymise notification data in migration logs

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20210408092956_AddReleaseVersion.Designer.cs
ntbs-service/Migrations/20210408092956_AddReleaseVersion.cs
ntbs-service/Models/ReleaseVersion.cs
ntbs-service/Pages/Shared/_Footer.cshtml
ntbs-service/Services/VersionService.cs
ntbs-service/Startup.cs
ntbs-service/wwwroot/css/footer.scss

Added release version table and service. The release version and date is then displayed in the footer.
This PR is linked to these pull requests in other repos:
https://github.com/publichealthengland/ntbs-reporting/pull/29
https://github.com/publichealthengland/ntbs-data-migration/pull/98
https://github.com/publichealthengland/ntbs-specimen-matching/pull/6
I didn't want to update the DACPACs if there were changes to be made, so I'll do that after approval.

NTBS-2125: Show release version in the footer

---

ntbs-service-unit-tests/Services/AuditServiceTest.cs
ntbs-service/Models/SeedData/AuditEventType.cs
ntbs-service/Services/AuditService.cs

Filter out print events from notification changes section of notification. Also added a test which tests that they are filtered out.

NTBS-2180: No longer show print audit in notification changes and add test

---

ntbs-service/appsettings.Staging.json
ntbs-service/deployments/int.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

I have disabled attaching stack trace (which does not affect stack traces sent with exceptions - these are always sent) and debug (in the documentation it says that it is generally advised that this is off in production). I have also created a new version of app settings for "staging" environments - which we will use for our azure environments. This has the old production settings, sending everything to sentry that it can so we can have all the available information during development of any issues.

NTBS-2098: Use staging environment for azure environments to enable detailed sentry logs

---

ntbs-service/appsettings.json

Based on our conversation on Monday: Timeout the authentication cookies after 12 hours, which should reduce the likelihood that users are logged out during their working days, and instead just need to log in at the start of each day.
I've tested that I can run the app (ie the JSON is not malformed) but nothing more than that, given how small the change is

NTBS-NONE Change authentication cookie timeout to 12 hours

---

ntbs-service/Pages/ServiceDirectory/Index.cshtml
ntbs-service/wwwroot/css/serviceDirectory.scss

The div that was holding the regions had a height of 0 as it was being populated just by the foreach. Giving it the display style gives it the correct height and the footer no longer overlays any regions.

NTBS-2225: Fix regions on service directory page

---

ntbs-service-unit-tests/Helpers/EpisodesHelperTest.cs
ntbs-service/Helpers/EpisodesExtensionMethods.cs

Change the way treatment events are grouped into periods: only produce a special "Transfer" period if transfer occurs when the previous period has finished. Otherwise, fold the transfer into the existing period.
Update the unit tests to reflect these changes.

NTBS-1987 Modify treatment period grouping criteria

---

ntbs-service/Startup.cs
ntbs-service/appsettings.CI.json
ntbs-service/appsettings.json

Previously, dummy auth (which is used by the integration tests) still had some weird dependencies on the type of AD authentication being used. I've removed these so that dummy auth is truly standalone - when it is used no config for either AdfsOptions or AzureAdOptions is required.

NTBS-2243 When using dummy auth don't require any other AD settings

---

ntbs-service/Services/CultureAndResistanceService.cs
ntbs-service/Services/SpecimenQueryHelper.cs
ntbs-service/Services/SpecimenService.cs

Get specimen details from specimen matching DB: previously these stored procedures lived in the reporting DB, but are being moved over as part of NTBS-2236, here: publichealthengland/ntbs-specimen-matching#13. For this to be merged and deployed the changes to the specimen matching DB also need to be merged and deployed.

NTBS-2236 Get specimen details from specimen matching DB

---

ntbs-service/DataAccess/DrugResistanceProfileRepository.cs

Get DRP summary changes view from specimen DB: previously this view lived in the reporting DB, but is being moved over
as part of NTBS-2240, here: publichealthengland/ntbs-specimen-matching#14. For this to be merged and deployed the changes to the specimen matching DB also need to be merged and deployed.

NTBS-2240 Get DRP summary changes view from specimen DB

---

ntbs-ui-tests/README.md
ntbs-ui-tests/testSettings.json

Update README and default local database connection string.
This should now provide a full description of how to run the UI tests against any of the environments.

NTBS-2116 Update readme with instructions for running UI tests

---

ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/wwwroot/css/_colors.scss
ntbs-service/wwwroot/css/buttons.scss
ntbs-service/wwwroot/css/caseManager.scss
ntbs-service/wwwroot/css/flashMessage.scss
ntbs-service/wwwroot/css/header.scss
ntbs-service/wwwroot/css/home.scss
ntbs-service/wwwroot/css/labResults.scss
ntbs-service/wwwroot/css/notification.scss
ntbs-service/wwwroot/css/notificationView.scss
ntbs-service/wwwroot/css/site.scss

- Extract CSS colours out into variables: name all colours used in CSS and define them in the `_colours.scss` file.
- Use a CSS colour variable instead of hard coded colours for the manage notification plus/minus expander symbol.
This will make any rebranding done later this year more straightforward. I have left references to PHE in the `_colours.scss`, because we are using PHE brand colours. When we come to rebrand, this means it will be clear which colours are from PHE and need to be replaced, and which colours are just helpful colours that are not tied to PHE branding. This should be quite easy, because all of the references to PHE have now been contained to this single file.

NTBS-2218 Update CSS colour variables

---

ntbs-service/Pages/Notifications/OverviewPartials/_ClusterInformationOverviewPartial.cshtml
ntbs-service/Pages/Reports/Index.cshtml
ntbs-service/Pages/Reports/Index.cshtml.cs
ntbs-service/Pages/Shared/_ClusterInformation.cshtml
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Properties/ExternalLinks.cs
ntbs-service/Services/ReportingLinksService.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/deployments/dev.yml
ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat-phe.yml
ntbs-service/deployments/uat.yml

* Link to a Sharepoint site to give the various report links in a way that is easy to maintain. The `/Reports` route redirects you to the Sharepoint site, and the `Reports` link in the navbar opens the Sharepoint site in a new tab.
* Add Sharepoint sites for the three Azure environments
The Sharepoint site has a few accessibility errors raised by WAVE but they don't look too serious and they are well out of our ability to control. Some screenshots:

NTBS-2066 Report links

---

ntbs-service/Pages/Alerts/TransferRequestAction.cshtml

Transfer Alerts implicitly have 2 TB Services: the TB Service of the Notification (this is the "source" because while the alert is open the Notification has not yet been transferred) and the TB Service on the Alert itself (which is the "destination"). However, on the `TransferAction` page the wrong one was being used as the "Sending TB Service".

NTBS-2272 Get sending TB Service from Notification not Transfer Alert

---

ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service/DataAccess/NotificationClusterRepository.cs
ntbs-service/Jobs/DataQualityAlertsJob.cs
ntbs-service/Services/NotificationService.cs

* The cluster matches are being moved into the specimen matching DB, not reporting, so get the changes from there. This is being moved here: publichealthengland/ntbs-specimen-matching#15.
* Change how the Cluster Data Quality alert is generated: don't generate it using the `DataQualityAlerts` job, instead create or dismiss the alert when changes to the cluster ID are being applied by the `NotificationClusterUpdate` job.
* Amend the `NotificationService` tests to cover this create or dismiss behaviour.

NTBS-2238 Get cluster match changes from specimen DB

---

ntbs-service-unit-tests/Services/DrugResistanceProfileServiceTest.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Jobs/DrugResistanceProfileUpdateJob.cs
ntbs-service/Services/CultureAndResistanceService.cs
ntbs-service/Services/DrugResistanceProfileService.cs
ntbs-service/Services/MockCultureAndResistanceService.cs
ntbs-service/Startup.cs

- Make the interface of `DrugResistanceProfileService` consistent with its own name (rename from `IDrugResistanceProfilesService` to `IDrugResistanceProfileService`).
- When migrating a legacy notification, migrate its culture and drug resistance summaries. To do this:
1. Copy the legacy notifications `NotificationCultureResistanceSummary` row in the specimen-matching DB to a new row for the new notification. This gives the reference lab summary on the Test results page. This uses a stored procedure being added here: publichealthengland/ntbs-specimen-matching#16.
2. Run the `DrugResistanceProfile` update on the newly imported notification, copying in the DRP and species from this newly made summary record.

NTBS-2241 Migrate DRP and species

---

ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

Just a trivial config change: change `Reports/` URLs to PowerBI apps for Azure test and PHE Live, and remove URLs for the other two Azure environments (the other two PHE environments didn't have report URLs before this change).

NTBS-2066 Change report URLs to PowerBI app

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20210429162156_DefaultDrugResistanceProfile.Designer.cs
ntbs-service/Migrations/20210429162156_DefaultDrugResistanceProfile.cs
ntbs-service/Migrations/20210430121906_DrugResistanceProfileNotNull.Designer.cs
ntbs-service/Migrations/20210430121906_DrugResistanceProfileNotNull.cs

Use a default value constraint (via EF's HasDefaultValue(...)) to add
the default value "No result" for species and DRPs of a new draft
notification.
Also reduce the length of these two fields to match the maximum length in its source table: specimen-matching's `NotificationCultureAndResistanceSummary`.

NTBS-2242 Add default DrugResistanceProfile values

---

ntbs-service/Jobs/ReportingDataRefreshJob.cs

The functionality of reporting's `uspLabSpecimen` has been moved to the specimen-matching DB, in `uspGenerate`. This SP in reporting doesn't do anything useful and is being removed as part of this ticket, NTBS-2231, so we should stop calling it from NTBS.

NTBS-2231 Stop calling reporting's uspLabSpecimen

---

ntbs-service/Startup.cs

Forgot to register treatment event mapper in the startup.

NTBS-2264: Add treatment event mapper to registered services

---

ntbs-service/deployments/int.yml
ntbs-service/deployments/load-test.yml
ntbs-service/deployments/training.yml
ntbs-service/deployments/uat.yml
ntbs-service/kubernetes/cert-manager/load-test-certificate.yaml
ntbs-service/kubernetes/cert-manager/load-test-cluster-issuer.yaml
ntbs-service/kubernetes/cert-manager/training-certificate.yaml
ntbs-service/kubernetes/cert-manager/training-cluster-issuer.yaml

Add yaml files for new environments. I have tested this by deploying these environments and they appear to be working (although the `training` environment requires PHE ICT to update the app registration in their Azure.

NTBS-2276 Setup load-test and training environments

---

ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Services/MockSpecimenService.cs
ntbs-service/Services/SpecimenQueryHelper.cs
ntbs-service/Services/SpecimenService.cs

When migrating specimen matches from ETS to NTBS, use the list of ETS specimen matches stored in the specimen matching DB, rather than the one stored in the migration DB, which is being removed as part of this ticket NTBS-2279.

NTBS-2279 Use specimen matching DB for specimen migration

---

ntbs-integration-tests/NotificationPages/CreatePageTests.cs
ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service/Helpers/RouteHelper.cs

* Add integration tests for the redirect behaviour of the `Create` route, and check that the drug resistance profile has been set to a default value (this is done by the database, configured in `NtbsContext`, so we need an integration test for that).
* Add a unit test to check that new notifications are created in the notifying user's TB service, and has their case manager ID, so that they are able to edit their newly created notification draft.
I'm not sure if this is the best way to be doing this, especially the fairly clunky integration tests, but I thought the best way to get feedback would just be to show you what I've got so far using a PR.

NTBS-2277 Add tests for the notification creation process

---

ntbs-service-unit-tests/DataMigration/NotificationImportServiceTest.cs
ntbs-service-unit-tests/DataMigration/SpecimenImportTest.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/DataMigration/SpecimenImportService.cs

* Refactor the specimen importing logic out of `NotificationImportService` and into a new `SpecimenImportService`.
* Add tests for this new `SpecimenImportService`
* Add tests for `NotificationImportService`
I'm happy to refactor the `NotificationImportService` service some more if you would like, separating out the grouping step, and the specimen and cluster dependencies as we discussed, if you think it is needed.

NTBS-2274 test NotificationImportService

---

ntbs-service/Models/OptionValue.cs
ntbs-service/Pages/Notifications/Edit/Items/ManualTestResult.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs

Fix a bug where the manual test result, result value would be lost from the edit page, because the select list used was not of the format that the Vue Filtered-Dropdown component was being told by the page. This led to the Vue component messing up the select box's options, and it getting set to the first value by default. This error was not present when JS was off.
The approach used by treatment event outcome subtype was correct; text as the enum name and the value as the enum integer. Extract out this calculation to `OptionValue.FromEnum`, and call it from both places.

NTBS-2316 Make select list values consistent

---

ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service-unit-tests/Models/Entities/Alerts/ClinicalDetailsTest.cs
ntbs-service-unit-tests/Services/AlertServiceTest.cs
ntbs-service-unit-tests/Services/EnhancedSurveillanceAlertsServiceTest.cs
ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service-unit-tests/TestData/MigrationDatabaseMock/outcomeEvents.csv
ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Models/Entities/Alerts/DataQualityBirthCountryAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityClinicalDatesAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityClusterAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityDotVotAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome12.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome24.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome36.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Enums/NotificationStatus.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs
ntbs-service/Services/AlertService.cs
ntbs-service/Services/EnhancedSurveillanceAlertsService.cs
ntbs-service/Services/NotificationService.cs

* Close old notifications during legacy import: 
* Refactor out the logic to determine whether a notification is inactive and should be closed to the Notification model.
* When importing a notification, set its status to be closed if it meets the inactive criteria, instead of waiting to get closed by Hangfire the following evening.
* Amend `NotificationMapper` tests to ensure that notifications are closed or left open depending on their treatment events during import.
* Dismiss alerts if notification is closed: 
* Don't open data quality alerts for notifications that are closed, and when a notification is being closed all of the alerts for it should also be closed.
* The only exception to this is that the duplicate notification alert should only be closed if both notifications are closed. …

NTBS-2299 No alerts on closed notifications

---

ntbs-service/Constants.cs
ntbs-service/Pages/Health.cshtml
ntbs-service/Pages/Health.cshtml.cs
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Properties/EnvironmentDescription.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.Staging.json
ntbs-service/deployments/dev.yml
ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/load-test.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/training.yml
ntbs-service/deployments/uat-phe.yml
ntbs-service/deployments/uat.yml
ntbs-service/wwwroot/css/_colors.scss
ntbs-service/wwwroot/css/header.scss

* Describe environment in phase banner
* Modify the phase banner so it only displays when live data should not be in the system, and have it describe the environment (eg. "Training" or "Development").
* Adjust the phase banner styles to make it more eye-catching, and move it to below the app name in accordance with GOV.UK design system recommendations.
* Show environment name in Health page
* Add user-facing environment names to config files

NTBS-2298 Phase banners per environment

---

ntbs-service/deployments/training.yml

Correcting the environment variables for the training environment. Although deployed on our Azure, it uses PHE's Azure AD for authentication, so needs the PHE names for the AD groups

NTBS-2298: correct variables for training

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20210517103719_ExpandTreatmentEventNotes.Designer.cs
ntbs-service/Migrations/20210517103719_ExpandTreatmentEventNotes.cs

Expand the treatment event notes field from 150 chars long to 1000. This is being made longer in migration as part of this ticket, and that change is up for review [here](https://github.com/publichealthengland/ntbs-data-migration/pull/107).

NTBS-2317 Expand treatment event notes

---

ntbs-service-unit-tests/DataMigration/CaseManagerImportServiceTests.cs
ntbs-service-unit-tests/DataMigration/ImportValidatorTest.cs
ntbs-service-unit-tests/DataMigration/NotificationImportServiceTest.cs
ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service-unit-tests/DataMigration/SpecimenImportTest.cs
ntbs-service-unit-tests/DataMigration/TreatmentEventMapperTest.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataMigration/CaseManagerImportService.cs
ntbs-service/DataMigration/ImportLogger.cs
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/DataMigration/NotificationImportRepository.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/DataMigration/SpecimenImportService.cs
ntbs-service/Migrations/20210521094459_AddLegacyImportMigrationRunTables.Designer.cs
ntbs-service/Migrations/20210521094459_AddLegacyImportMigrationRunTables.cs
ntbs-service/Models/Entities/Alerts/LegacyImportNotificationOutcome.cs
ntbs-service/Models/Entities/LegacyImportMigrationRun.cs
ntbs-service/Models/Entities/LegacyImportNotificationLogMessage.cs
ntbs-service/Models/Enums/LogMessageLevel.cs
ntbs-service/Pages/Admin/Migration.cshtml
ntbs-service/Pages/Admin/Migration.cshtml.cs
ntbs-service/Pages/LegacyNotifications/Index.cshtml
ntbs-service/Pages/LegacyNotifications/Index.cshtml.cs

* Add tables to track the results of a legacy migration import batch. Add:
* `LegacyImportBatchGroup`: metadata about a migration import run, which may be broken up into multiple batches.
* `LegacyImportBatch`: metadata about the batch importing a subset of the notifications
* `LegacyImportNotificationLogMessage`: warning and error messages for a specific notification during a batch.
* `LegacyImportNotificationOutcome`: tracking success or failure when migrating a notification during a batch.
* Write import logs out to database:
* Refactor `ImportLogger` to collect notification IDs, and write messages about a notification or group out to the new `LegacyImportBatch` tables.
* Refactor services that call this logger to support this change, primarily to make sure notification IDs are passed …

NTBS-2322 log migration events to db

---

ntbs-service/Models/Entities/TreatmentEvent.cs

We recently expanded the treatment outcome notes width in the DB due to changes in the migration DB. Expand the width of the field in validation as well.

NTBS-2317 Fix validation for treatment outcome notes

---

EFAuditer-tests/EFAuditer-tests.csproj
EFAuditer/EFAuditer.csproj
coming-soon/coming-soon.csproj
load-test-data-generation/load-test-data-generation.csproj
ntbs-bulk-insert/ntbs-bulk-insert.csproj
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service-unit-tests/Services/EnhancedSurveillanceAlertsServiceTest.cs
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/ntbs-service.csproj
ntbs-ui-tests/ntbs-ui-tests.csproj

* A few of the `async` `ImportLogger` methods were not being properly awaited in the `ImportValidator`, leading to multiple threads accessing the `NtbsContext` and thus concurrency bugs. Await them properly now.
* Add `MissingAwaitWarning` analyser; this should catch some of the issues we were having with NTBS-2322.
* Fix minor `async`/`await` issue in a unit test caught be the newly added analyser

NTBS-2322 Notification import concurrency fix

---

ntbs-service/Models/Entities/TreatmentEvent.cs

Allow basic special characters like punctuation in the notes for treatment events, which are imported from the legacy systems.

NTBS-2317 Loosen validation for treatment event notes

---

.github/workflows/run-ui-tests.yml
ntbs-ui-tests/Features/ImportLegacyNotification.feature
ntbs-ui-tests/Hooks/DriverSetup.cs
ntbs-ui-tests/Hooks/TestConfig.cs
ntbs-ui-tests/testSettings.json

Now delete only the record from the imported notifications table with the correct environment. 
Unmatch any specimens that are connected to the imported notification.

NTBS-NONE-UI-TEST-FIX: delete legacy specimens and from new imported notification table

---

ntbs-service/DataMigration/Models/ImportResult.cs

When failing to import a specimen, this is noted in the `ImportResult` object. However, because that object will have recently been marked as successful, previously denoted by a `null` error list for that notification, then adding this error to the null list will cause a `NullPointerException`. Instead, we now encode success as an empty list of errors, instead of a `null` list of errors, so this list can be added to after the notification has been imported to track warnings.

NTBS-NONE Fix a specimen import result bug

---

ntbs-service/Services/AdDirectoryService.cs
ntbs-service/Services/AdImportService.cs
ntbs-service/Services/AdUserService.cs
ntbs-service/Services/AzureAdDirectoryService.cs
ntbs-service/Services/AzureAdDirectoryServiceFactory.cs
ntbs-service/Services/AzureAdImportService.cs

We were having issues running `UserSync` because there were too many different groups under the BaseUserGroup. This is because the request returns the results in pages of 100 results, and there were ~250 results, so ~60% of the groups were being ignored.
By using `NextPageRequest` we can read all of the pages in sequence.
Also, tidy up some of the graph client queries, such as the base group query to use an equality check on `displayname` instead of a weird prefix and filter search.

NTBS-2347 Use Graph Client pagination during UserSync

---

ntbs-service/DataMigration/NotificationImportHelper.cs

Insert imported notification entry when same notification has already been imported in another environment
Tested this locally by hacking around with my local db

NTBS-2369 Fix bug in mark imported notifications job

---

ntbs-service/Services/LegacySearchService.cs

Me and Nancy have no idea why we were using the Source column from the Address table, and there's no mention of why in the original ticket NTBS-263. (I'm guessing it was overlooked as the field is called Source, which is also the name we map to in the banner).
The issue came about as some legacy notification don't have corresponding addresses (about 995 of them).

NTBS-2375: Use source from merged notifications for legacy banner source

---

ntbs-service/wwwroot/css/notification.scss

A minor bug I spotted during show and tell:
Some changes to the NHS CSS made the expander plus and minus symbols blue again. Tweak our CSS selectors to fix this.

NTBS-2373 Fix manage notification expander colours

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20210603104536_ExpandUserContactDetailsFields.Designer.cs
ntbs-service/Migrations/20210603104536_ExpandUserContactDetailsFields.cs
ntbs-service/Models/Entities/User.cs

* Add validation to User entity to reflect the contact details widths in the database. ASP.NET will then add width limiting HTML and validation
* Extend the `JobTitle` field to 100 characters, and extend the `EmaiSecondary` field to 100 from 50, like `EmailPrimary` at 100.
The ticket also asked for a warning when the user is up to the character limit for that input box. This is not something we have for any of the other width-limited text boxes in `PatientDetails`, `ClinicalDetails`, etc. and looks pretty tricky to implement given our current validation process (we don't really have a notion of a warning, only errors). We could make a follow on tech debt ticket for this, but I suppose it depends on how much we actually want that feature.

Fix user contact details field lengths

---

ntbs-service/Pages/Notifications/TestResults.cshtml.cs

Fixed a small bug where a user couldn't view test results of a notification linked to a notification in their TB service.

NTBS-2330: Get linked notifications before checking permissions

---

.github/workflows/run-ui-tests.yml

Instead of downloading our own Chrome driver and needing to keep the version in sync with the Chrome installed in the GitHub `ubuntu-latest` image, just use both components.
Use the original Selenium server which can detect the web drivers installed, instead of the NPM packaged one.

NTBS-2382 Use Chrome driver on GitHub action image

---

ntbs-ui-tests/Steps/AssertSteps.cs
ntbs-ui-tests/ntbs-ui-tests.csproj

Spotted this whilst debugging the package updates
Use a `WebDriverWait` to wait for a URL to change after pressing a `POST` button in the Transfer Notification UI tests, instead of failing if the `POST` doesn't redirect quickly enough.

Wait until URL has changed for transfer UI tests

---

ntbs-service/Pages/Notifications/TestResults.cshtml

The inline-template tag on in the html was making the manually entered test results flicker - it would show them on initial page load and then immediately hide them.

NTBS-2330: Remove inline template tag

---

ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/wwwroot/source/Components/CascadingDropdown.ts

The javascript for the cascading dropdown was removing any value inputted when it filtered the select, this has been changed so that if the option still exists it doesn't remove it. 
Also I fixed a bug where if you selected a PHEC and then selected "Please select" the TB services dropdown would be empty. I thought it would make sense to still have all the TB services as it does when loading the page initially.
This is being fixed as part of 2360 as the reason the tests were failing was due to a race condition with the TB services being filtered (and therefore removing the inputted value) and the value being inputted.

NTBS-2360: Cascading dropdown doesn't remove inputted value

---

ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/EditNotifications.feature
ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/Steps/ActSteps.cs
ntbs-ui-tests/Steps/AssertSteps.cs

Use implicit wait when checking for the warning messages and also check for an overview element on the transfer request tests so that we know we're on the overview page.

NTBS-2360: Wait for warning messages with implicit wait

---

ntbs-service/package-lock.json

Updated nested packages so that `glob-parent` updates to a safe version.
I've done a quick smoke test and didn't identify any issues.

NTBS-2435 Update version of nested glob-parent to safe 5.1.2

---

.github/workflows/ntbs-test-and-deploy.yml

Build a docker image whenever code is pushed to the `future-work` branch.
This is untested so far, but I'm feeling confident. (We'll get confirmation when this branch is merged).

NTBS-NONE Build future work images on push

---

load-test-data-generation/NotificationGenerator.cs
load-test-data-generation/Notifications/TreatmentEventsGenerator.cs

Change the load test generation program so that it sets notifications to be Closed when appropriate.
I have tested this by clearing out the load-test database and re-generating the data.

NTBS-2441 Set up notifications with consistent status

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/DraftEditPageTests.cs
ntbs-integration-tests/NotificationPages/TreatmentEventsEditPageTests.cs
ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_TreatmentEvent.cshtml
ntbs-service/Pages/Notifications/Edit/TreatmentEvents.cshtml
ntbs-service/Pages/Notifications/Edit/TreatmentEvents.cshtml.cs

Show a temporary treatment event for treatment start or diagnosis made on treatment event editing pages, to show the treatment event that will be created when the notification is submitted.
Add integration tests to check that a starting event is displayed on the treatment events page even though it won't be made until the treatment event is submitted.
Fix integration test seeding bug: add an explicit ID for a draft data quality alert, to fix a weird integration test bug that would prevent adding another notification to the in-memory test database.

NTBS-1339 Add temporary starting events

---

ntbs-integration-tests/ContactDetailsPages/EditContactDetailsTests.cs
ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service-unit-tests/DataMigration/ImportValidatorTest.cs
ntbs-service-unit-tests/Models/ContainsNoTabsValidatingTest.cs
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/Models/Entities/Alerts/TransferRejectedAlert.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/MBovisAnimalExposure.cs
ntbs-service/Models/Entities/MBovisExposureToKnownCase.cs
ntbs-service/Models/Entities/MBovisOccupationExposure.cs
ntbs-service/Models/Entities/MBovisUnpasteurisedMilkConsumption.cs
ntbs-service/Models/Entities/SocialContextBase.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Models/Entities/User.cs
ntbs-service/Models/Validations/ContainsNoTabsAttribute.cs
ntbs-service/Models/Validations/ValidationHelper.cs

* Add a custom `ContainsNoTabs` attribute: This is caught by our regexes already but a custom attribute gives us the ability to have a custom error message for this issue. Add some unit tests for this class as well.
* Add `ContainsNoTabs` to all long-form notes fields: specifically the fields using our most generous text validation `CharacterValidationWithNumbersForwardSlashExtendedWithNewLine`, giving a more helpful message when there are illegal `\t` characters in the field. This can't be typed in easily, but could be copied and pasted or migrated in, causing this more helpful error to trigger.
* Add integration tests to two of the pages using ContainsNoTabs.
* Trim and replace `\t` with a space during import, for long form notes field. Add a unit test for this, and fix the …

NTBS-2463 better notes validation

---

EFAuditer-tests/UnitTests/Services/EFAuditServiceExtensionsTest.cs
EFAuditer/CustomFields.cs
EFAuditer/EFAuditServiceExtensions.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataAccess/UserRepository.cs
ntbs-service/DataMigration/NotificationImportRepository.cs
ntbs-service/Jobs/HangfireJobContext.cs

Not as easy a change as I thought, until I realised that our custom field for user was getting overwritten with nulls in this case so I've updated that to only set a custom field if we actually find a non null username.

NTBS-2438: Set correct audit user on login

---

ntbs-service/Pages/Health.cshtml
ntbs-service/Pages/Health.cshtml.cs
ntbs-service/Pages/Shared/_Layout.cshtml
ntbs-service/Pages/_ViewImports.cshtml
ntbs-service/Properties/ApplicationInsightsOptions.cs
ntbs-service/Services/BlankJavaScriptSnippet.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.json
ntbs-service/deployments/load-test.yml
ntbs-service/ntbs-service.csproj

* Add Application Insights monitoring: 
* Do this for both the C# backend, and the web frontend (via Razor).
* Only add this monitoring based on a configuration flag.
* Flag when this is enabled on the health page.
* Add AppInsights configuration: have this disabled by default, only enable it `load-test`
* A secret has been added to the `load-test-connection-strings` for the load test Application Insights connection string
* On Azure, an Azure Application Insights resource `NTBS_LoadTest_Insights` has been added.

NTBS-2459 add application insights

---

ntbs-service/Pages/LegacyNotifications/Index.cshtml.cs
ntbs-service/Services/AuthorizationService.cs

The padlock was always showing on the legacy notification page, this was because we actually weren't checking for the users permissions at all like we do on the search page.

NTBS-2477: Set show padlock on legacy notification page

---

ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/Steps/AssertSteps.cs

I have determined that the alert is definitely not being created during the failed transfer test. This commit concentrates on improving the test so that we get a better indication as to why it fails. In particular:
- Fix a bug with the "alert has been created" assertion
- Make sure that the notification overview has loaded after clicking the confirm transfer button. If the confirm fails, we should then see an error page, which will be logged.

NTBS-2446 Ensure transfer request created before logging out

---

ntbs-service-unit-tests/Models/Entities/NotificationTest.cs
ntbs-service/DataMigration/TreatmentEventMapper.cs
ntbs-service/Models/Entities/Notification.cs

Move the fetching of treatment outcome to the ShouldBeClosed method.
Removed the exception, changed the test to check that the method is fetching the outcome and then properly setting ShouldBeClosed.

NTBS-2478: No longer add seed treatment outcome to notification

---

ntbs-service-unit-tests/DataMigration/ImportValidatorTest.cs
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/Models/Entities/MBovisDetails.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/SocialRiskFactors.cs
ntbs-service/Models/Entities/TestData.cs
ntbs-service/Models/Validations/ValidationChildAttribute.cs

First draft of trimming whitespace of all free-text fields. I thought I would get this up for review before I went on holiday, and ask a few questions. 
The general approach is to modify the code used to clean all the `[ContainsNoTabs]` fields to hit every `string` in a notification. I have asked Nancy on the ticket whether this will cause any issues, and put a full list of fields that will get cleaned on there. I still need to amend the tests to cover the new strings being clean.

NTBS-2461 trim text fields on import

---

ntbs-integration-tests/Helpers/TestUser.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/HospitalDetailsPageTests.cs
ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Services/NotificationService.cs

Filter case manager dropdowns so that they only show active case managers. 
For hospital details in the case that the current case manager is inactive (either due to it being a legacy case manager OR the user sync has made the user inactive) the dropdown contains this case manager as an option.

NTBS-2455: No longer show inactive users in case manager dropdowns

---

ntbs-service/deployments/int.yml
ntbs-service/deployments/load-test.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/training.yml
ntbs-service/deployments/uat.yml

Fix a weird issue where IE11 was not able to go through the OIDC authentication flow and let the users sign in, probably because the cookies were too big.
This has been tested on `test` using a hotfix image already.
Some links that helped me track this issue down:
* [An Identity Server issue](https://github.com/IdentityServer/IdentityServer4/issues/3101)
* [A kubernetes-nginx issue](https://github.com/kubernetes/ingress-nginx/issues/3499)
* [StackOverflow, to write the Kubernetes YAML](https://stackoverflow.com/a/63195215)
* Our nginx logs for one of these during one of these failures

NTBS-NONE Increase header buffer sizes in Azure nginx

---

ntbs-service/Migrations/20210629101707_ExpandMBovisExposuresOtherDetails.Designer.cs
ntbs-service/Migrations/20210629101707_ExpandMBovisExposuresOtherDetails.cs
ntbs-service/Models/Entities/MBovisAnimalExposure.cs
ntbs-service/Models/Entities/MBovisExposureToKnownCase.cs
ntbs-service/Models/Entities/MBovisOccupationExposure.cs
ntbs-service/Models/Entities/MBovisUnpasteurisedMilkConsumption.cs

Expand the OtherDetails fields for MBovis Animal Exposure, Exposure to Known Cases, Occupation Exposure and Unpasteurised Milk Consumption from 150 nvarchars to 250.

NTBS-2494 Expand the MBovis OtherDetails fields

---

ntbs-service/Properties/ApplicationInsightsOptions.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.json
ntbs-service/deployments/load-test.yml
ntbs-service/ntbs-service.csproj

Add Application Insights Profiler, and relevant options to config. 
I've tested this locally and this works, but I don't know how useful the profiling will actually be (most of the stuff seems to be calls to Sentry, so the Application Insights might not be playing nicely with Sentry).

NTBS-2459 Add Application Insights Profiler

---

ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/EditNotifications.feature
ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/Steps/ActSteps.cs

Update UI tests to prefer selecting elements from dropdowns, rather than entering text.
Update the transfer tests so that we wait for prior API calls to complete before making the next selection. I wasn't able to identify a specific bug that this fixed, but I'm optimistic that it will make the test less flaky.

Ntbs 2446 transfer UI test

---

ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/EditNotifications.feature
ntbs-ui-tests/Steps/ActSteps.cs

Fix the social context venue tests, to be able to select values from select groups.
Also, use option text to make selections from option group selects, instead of ID numbers.

NTBS-2446 Fix option group select UI tests

---

ntbs-integration-tests/ServiceDirectory/ServiceDirectoryRegionPageTest.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Pages/ServiceDirectory/Region.cshtml.cs

Previous tickets dealt with searches but not the region pages. Now filter by isActive on those pages too.

NTBS-2514: Don't show inactive users in service directory

---

ntbs-service/DataAccess/DataQualityRepository.cs

Remove waiting period from duplicate check alert
This for Release-1.0.2 so is being merged into `live`
There are no tests for this, so none needed to be amended. It would be nice to have some, but all of the duplicate checking logic is in handwritten SQL which precludes unit testing. I think the integration testing setup might work for this, but I'm not sure how I would trigger the Hangfire job as part of the integration test.

NTBS-2510 Remove waiting period from duplicate check alert

---

ntbs-service/Pages/Help/Menu.cshtml
ntbs-service/Pages/Reports/Index.cshtml.cs
ntbs-service/Pages/Shared/_ClusterIdLink.cshtml
ntbs-service/Pages/Shared/_Footer.cshtml
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Properties/ExternalLinks.cs
ntbs-service/Services/ExternalLinksService.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.json

Rename `ReportingLinksService` to `ExternalLinksService`, due to adding a link that wasn't related to reporting for the header.
Add a NTBS Resources header link, and link to the release notes from the version number in the footer.

NTBS-2518 Add SharePoint links to app

---

ntbs-service/Constants.cs
ntbs-service/Pages/Health.cshtml
ntbs-service/Pages/Health.cshtml.cs
ntbs-service/appsettings.json
ntbs-service/deployments/training.yml

* Add read-only user group name to the health page
* Use correct ReadOnlyUser group name, `App.Auth.NIS.NTBS.Read_Only`
* But use a deliberately incorrect one in training, to allow read-only users in other environments to do training.

NTBS-2517 Fix read-only AD groups

---

ntbs-service-unit-tests/DataAccess/DataQualityRepositoryFixture.cs
ntbs-service-unit-tests/DataAccess/DataQualityRepositoryTests.cs
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/DataAccess/DataQualityRepository.cs

The duplicate matching step that is failing on load-test is the one checking for duplicate NHS numbers, and the data in question is the nicely seeded random set of NHS numbers, ~40k of them, and is an ideal simulation of running this job on live.
This old query was defined using Entity Framework, and takes at least 12 minutes (and then we run out of tempdb space….) to run on 40k records. This is a bad query, in particular the WHERE clause is a complicated mess, in particular it does a poor job of translating comparators given the different ways NULLs are compared in C# and SQL. This messy query bamboozles the query optimiser, causing it to choose a hopelessly slow, bad plan (it appears to take the cartesian product of `(Notification, Patients) × (Notification, Patients)` and then filter, …

NTBS-2497 Improve duplicate NHS number query performance

---

ntbs-service-unit-tests/Services/AlertServiceTest.cs
ntbs-service/Services/AlertService.cs

Previously, some alerts were created with a date only, while others included the date and time. Here we make the behaviour consistent - all alerts should be added with the time included.

NTBS-2529 Create all alerts with current timestamp

---

ntbs-service/Jobs/HangfireJobScheduler.cs
ntbs-service/ntbs-service.csproj

I've deployed this change to `int` this morning (from a feature branch) and it seems to be working - although really we need to let it run for a day to check that the jobs are happening at the right times.

NTBS-2565 Make timezone cross-platform

---

ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome12.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome24.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome36.cs

Another round of improving the performance of the `data-quality-alerts` job.
Filter by notification status as well as date range for the first pass of filtering for treatment outcome DQ alerts. The more complex treatment outcome analysis is done in memory for each possibly eligible notification, so the more precisely we define that set the less notifications the job has to consider each night.

NTBS-2563 Refactor filters for treatment outcome alerts

---

ntbs-service-unit-tests/DataAccess/AlertRepositoryTests.cs
ntbs-service-unit-tests/DataAccess/DataQualityRepositoryTests.cs
ntbs-service-unit-tests/DataAccess/RepositoryFixture.cs
ntbs-service/DataAccess/AlertRepository.cs

When we were projecting the alerts to AlertWithTbServiceForDisplay we were actually never getting the TB service's name/code or the case manager's name - as it was trying to pull them from HospitalDetailsDisplay. Now we actually go to the entity we want the name/code from. I've added tests so this isn't reintroduced.

NTBS-2571: Fix alert case manager and tb service names

---

ntbs-service-unit-tests/DataMigration/ImportValidatorContactTracingTest.cs
ntbs-service-unit-tests/DataMigration/ImportValidatorTest.cs
ntbs-service/DataMigration/ImportValidator.cs
ntbs-service/Models/Entities/ContactTracing.cs
ntbs-service/Models/Validations/ValidationHelper.cs

Previously we would clean contact tracing data by checking whether it was entirely valid or not, and discarding it all if not. Now, try to preserve data from the outer rings of the Venn diagram (cases identified, screened etc.) even when inner rings (like  treatment info) are invalid.
For example, if there were 3 adult contacts identified, but 5 cases of adult latent TB identified after contact tracing: before we would just discard all info, and now we retain the 3 identified cases, but drop the invalid latent TB case count.
Add a set of tests for this new behaviour.

NTBS-2533 improve contact tracing import

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/LabResultsPage/LabResultsPageTests.cs
ntbs-service/Pages/LabResults/Index.cshtml.cs
ntbs-service/wwwroot/source/Components/FetchSpecimenPotentialMatch.ts

When fetching a notification ID for a manual match, if it is null or empty just clear the notification details, and notification ID validation errors, instead of 500'ing.
Add a new field to the response JSON, to say that there was no notification ID in the request.

NTBS-2573 Fix validation bug on lab results page

---

ntbs-service/DataMigration/ImportValidator.cs

Tweak notes text from contact tracing, to not append a full stop if the current last character is one.

NTBS-2533 Tweak notes text from contact tracing

---

ntbs-service-unit-tests/DataMigration/CaseManagerImportServiceTests.cs
ntbs-service-unit-tests/DataMigration/NotificationImportServiceTest.cs
ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service-unit-tests/DataMigration/TreatmentEventMapperTest.cs
ntbs-service/DataMigration/CaseManagerImportService.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/DataMigration/TreatmentEventMapper.cs

While I was investigating 2553 I realised that during the import of a notification we were importing/updating the case manager of the notification twice. I think this was added when we switched to using a user ID - as we needed the ID to add to the hospital details we were importing the case manager in the mapper, but we never removed the call to the import later on in the notification importer/validator step.

NTBS-2553: No longer import case manager twice during migration

---

ntbs-service/Jobs/UserSyncJob.cs
ntbs-service/deployments/dev.yml

* Shift `phe-dev` user sync to 21:00: this is evenly spaced between UAT (19:00) and Live (23:00) though the job should only take a couple of seconds anyway.
* Add automatic retries to User Sync job: allow up to 5 attempts per job, with the first attempt happening after two minutes of the failure, and all subsequent ones after 10 minutes.

NTBS-2581 User sync tweaks

---

ntbs-service-unit-tests/Models/NhsNumberValidatingTest.cs
ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service/Helpers/NotificationHelper.cs
ntbs-service/Models/Validations/NhsNumberValidationAttribute.cs
ntbs-service/Services/NotificationService.cs

NHS number validation allows spaces, and before the NHS number is saved format it without spaces.
Both call a helper, just incase in the future we allow other formatting of them.
Added tests for the update, and for the validation.

NTBS-2530: NHS number validation allows spaces

---

ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml.cs
ntbs-service/wwwroot/source/Components/NhsNumberDuplicateWarning.ts

Fixed the duplicate check to format nhs number before checking - slipped through as the space-removing ticket and this were done at the same time.
Also added links to the legacy notification NHS number duplicate warnings.

NTBS-2520: Add links to legacy notifications on nhs number duplicate

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Migrations/20210802135016_ChangeDidNotStartTreatmentToStartedTreatment.Designer.cs
ntbs-service/Migrations/20210802135016_ChangeDidNotStartTreatmentToStartedTreatment.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-ui-tests/Helpers/Utilities.cs

Changed the DidNotStartTreatment column to StartedTreatment.
In the migration I have inverted the boolean column, I will also need to go update DACPACs and make a change in reporting.

NTBS-2335: Change did not start treatment to started treatment

---

ntbs-integration-tests/Helpers/TestUser.cs
ntbs-service/appsettings.CI.json
ntbs-service/appsettings.Development.json
ntbs-ui-tests/Helpers/WebDriverExtensions.cs
ntbs-ui-tests/Steps/ActSteps.cs

Fix a flake that I was reproducing consistently locally, that was also the cause of the "Edit notification test results fields" failure [here](https://github.com/publichealthengland/ntbs_Beta/runs/3165821469?check_suite_focus=true). The `WaitUntilElementIsClickable`, a Selenium function sometimes throws `StaleElementExceptions`. My fix is to catch the first one of these and try waiting again, following the pattern used elsewhere to tolerate the exceptions
Of the four recent failures:
* [Run 182](https://github.com/publichealthengland/ntbs_Beta/runs/3165821469?check_suite_focus=true) the issue described above and fixed in this PR
* [Run 183](https://github.com/publichealthengland/ntbs_Beta/runs/3176013222?check_suite_focus=true) Azure login fell over for over 30s (slightly surprising but …

NTBS-2596 Add stale element retry to wait for select element

---

ntbs-service-unit-tests/Jobs/UpdateTableCountsJobTest.cs
ntbs-service/Jobs/UpdateTableCountsJob.cs

Only fail the job when a table count decreases by more than 0.5%.

NTBS-2613 Update table count job failure criteria

---

ntbs-service/wwwroot/css/notification.scss

* Make the focus yellow fill the whole button, instead of just around the text. 
* Fix some issues with borders, especially the interaction between round and sharp corners between the button and the box it expands. 
* Fix an issue with a plus being shown instead of a minus when the box is expanded but not in focus.

NTBS-1280 Fix manage notifications button styling

---

ntbs-integration-tests/TransferPages/ActionTransferPageTests.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Services/NotificationService.cs
ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/Helpers/Utilities.cs
ntbs-ui-tests/Steps/AssertSteps.cs

* Remove local patient ID and consultant name when a case is transferred from one TB service to another.
* Tweak integration tests to cover this.
* Add UI test checks for dropping details on accepted transfer (and keeping on rejected transfer). 
* Fix a small UI test bug that was overwriting seed `HospitalDetails` on setting case manager and TB service.

NTBS-1559 remove local details after transfer

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Helpers/NotificationExtensionMethods.cs
ntbs-service/Models/NotificationBannerModel.cs
ntbs-service/Models/Projections/NotificationForBannerModel.cs
ntbs-service/Pages/LegacyNotifications/Index.cshtml.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Services/AuthorizationService.cs
ntbs-service/Services/LegacySearchService.cs

Only show a padlock if you have no read permissions for a notification. Never show a padlock on a legacy notification.

NTBS-2495: Change padlock functionality 

---

ntbs-service-unit-tests/DataMigration/ImportValidatorTest.cs
ntbs-service/DataMigration/ImportValidator.cs

Added the type of the object we're validating to the validation error messages it produces. This means you can now see which postcode field is wrong (patient details vs social context address) for example

NTBS-2468: Add type name to migration error messages

---

ntbs-service-unit-tests/Services/UserServiceTest.cs
ntbs-service/Services/UserService.cs

* Fix a null reference exception in `UserService`.
* Whilst I was here, I wrote a bunch of unit tests for the method in question.
I was not able to reproduce the error. It seems to have occurred when a user logged in without any details about them in Azure AD, and the header `null` ref'ed when trying to display their name. This means the user probably was shown our "Service unavailable" error 500 page, instead of the access denied page they should have got. Rider was able to point out the source of the `null` reference exception on the line in question so I just fixed it.
Just one question: currently it's still possible to get a `null` out of `UserService.GetUserDisplayName`, which is used by the header partial to make this text:
And if the user does get in somehow without a name (even to …

NTBS-2652 Fix GetUserDisplayName null ref exception

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/Helpers/EpisodesExtensionMethods.cs
ntbs-service/Models/Enums/TreatmentEventType.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml

Add a display-only denotification event if the notification is denotified. This will be used for the period's end date if it's the last event, but will not be used for any outcome calculations. This event is appended to the last period and then ordered by date (and a custom ordering, where denotification is last).

NTBS-2650: Add display-only denotified treatment event

---

ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Models/Validations/ValidationHelper.cs

Add the type to the "Personal details" postcode warning. Update the validation message so that it is consistent for legacy and NTBS notifications.

Ntbs 2687 postcode errors

---

ntbs-service/webpack.common.js

I've checked locally that the issue loading the fonts is fixed. We should do a bit of regression testing on `int` to make sure this hasn't broken anything else.

NTBS-2674 Update webpack settings to be consistent with new css-loader

---

ntbs-service/Pages/Alerts/TransferRequest.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisAnimalExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisUnpasteurisedMilkConsumption.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/_TravelDetailsPartial.cshtml
ntbs-service/Pages/Notifications/Edit/_VisitorDetailsPartial.cshtml
ntbs-service/wwwroot/source/Components/AutocompleteSelect.ts

Removed the PHEC dropdown on transfers, as it was being used as a way to filter down the TB service list which is now searchable.
The cadcading-dropdown component is no longer needed as we don't need multiple filtering, so I'm just using the filtered-dropdown with an autocomplete-select. I've added a filtering property to this, as it means we can emit an event and filter when a choice is chosen instead of on blur, which is when validation happens.
Also I've changed the ref it's looking for for the select element so it lines up with filtered-dropdown - "selectField" instead of "selectElement".

NTBS-1420: Add TB service search during transfer

---

ntbs-service-unit-tests/DataMigration/TreatmentEventMapperTest.cs
ntbs-service-unit-tests/TestData/MigrationDatabaseMock/transferEvents.csv
ntbs-service/DataMigration/RawModels/MigrationDbTransferEvent.cs
ntbs-service/DataMigration/TreatmentEventMapper.cs

Migrate in notes from treatment events in the migration database. There is some boilerplate text that is added to pretty much every note, so I've written a regex to match that so we don't import those parts. 
If the note doesn't match at all then it will just add the whole note into the notes field.
The longest note in ETS (before any removal) is 800 characters and our notes field is 1000, so I'm confident we won't see that error.
The corresponding migration PR: https://github.com/publichealthengland/ntbs-data-migration/pull/167

NTBS-2685: Take treatment event notes from migration database

---

ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/testSettings.json

Update UI tests to use new Yorkshire TB services: put the Leeds UI tester in West Yorkshire

NTBS-2717 Update UI tests to use new Yorkshire TB services

---

load-tests/gradle/result-parser/result-parser.js

Produce more specific error messages, and extract out the threshold constants in the load tests result parser. When the load tests failed yesterday it took me a little while to work out which threshold was missed and this change should make it a little easier

Tidy load test results parser

---

ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/webpack.common.js

Fix a misconfigured part of webpack that was highlighted by the recent `axios` security upgrade.

NTBS-NONE Update Axios package and fix webpack build

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Models/Projections/NotificationForBannerModel.cs

Split out the collection queries for previous TB services and linked notifications. This is quite a lot uglier, but does lead EF to produce smaller and more straightforward SQL, which gives the query optimiser a better chance at picking a good plan. If you can think of neater ways of doing this whilst also keeping the EF queries separate I'm all ears.

NTBS-2734 Split banner model query

---

ntbs-service-unit-tests/DataMigration/TreatmentEventMapperTest.cs
ntbs-service/DataMigration/TreatmentEventMapper.cs

I was helping Nancy find notifications to import to test this and realised that it was only taking the appended part of the comment every time. Turns out that this is because the "You have been identified as the new case manager for the case below." is present pretty much all the time, and the regex wasn't looking to make sure that this was the ONLY text in the string. 
Eg. "You have been identified as the new case manager for the case below. They moved from London, this is important" was counting as a match, and it was moving on.
Now the "They moved from London, this is important" will get picked up, as intended.

NTBS-2685: Fix transfer comment regex

---

ntbs-service/Pages/Logout.cshtml.cs
ntbs-service/Pages/PostLogout.cshtml
ntbs-service/Pages/PostLogout.cshtml.cs
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Startup.cs

Add a page telling the user the have been logged out, with a button to log back in. This page can be accessed anonymously (by users who have not been authenticated). Before we would redirect to a log in page with a correlation cookie that would time out after 15 minutes, so the user would need to log in twice (with the first causing a warning in Sentry). Now, by redirecting to this post-logout page the user can choose when they get sent to Azure AD with that cookie.
This won't prevent the correlation cookie issue, if the user visits the log in page and leaves it for 15 mins it will still happen, but
now the user needs to do something to visit the login page, instead of getting redirected after timing out.

NTBS-2666 Add a PostLogout page

---

ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/webpack.common.js

Revert the changes made for the `axios` security patch. The webpack config change made to fix the previous issue broke the menu bar in IE11. Some webpack settings will need tweaking but it's going to be safer to do this next release and with the next round of package updates, when there is more time to test it.

NTBS-NONE npm security update revert

---

ntbs-service/Startup.cs

User-sync makes user names using UPNs for internal users and emails
for external users. Authentication used to use "name", a form of
unique name for external users, which often was the email, but is not
for EOTP users. Use email in authentication to make the two consistent.

NTBS-2723 Make authentication and user-sync consistent

---

ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Jobs/DataQualityAlertsJob.cs
ntbs-service/Migrations/NtbsContextModelSnapshot.cs
ntbs-service/Models/Entities/Alerts/DataQualityChildECMLevel.cs
ntbs-service/Models/Enums/AlertType.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml
ntbs-service/Services/AlertService.cs

Added a new DQ alert: Child ECM level. This alert with show up if the patient is <16y/o at time of notification and if their ECM level is not set (= 0 as default).
Age at notification is worked out the same way it is in NotificationDisplay, I was going to commonise but LINQ shouted at me when I tried to put a call to a helper in the qualifies expression.
Added this to the creation job, and to the auto-dismissal job.

NTBS-2709: Add new child ECM level dq alert

---

ntbs-service/Models/Entities/Alerts/DataQualityChildECMLevel.cs

Accidentally using creation date instead of notification date.

NTBS-2709: Use notification date instead of creation date in logic

---

ntbs-service/Services/NotificationService.cs

Now auto-dismiss the child ECM alert if the change has meant the alert should no longer exist. Found a DQ alerts bug while testing this, details in slack - haven't made a ticket for it yet.

NTBS-2709: Auto-dismiss ECM alerts when details updated

---

ntbs-service-unit-tests/DataAccess/RepositoryFixture.cs
ntbs-service-unit-tests/DataAccess/UserRepositoryTests.cs
ntbs-service/DataAccess/UserRepository.cs

Change the way we delete CaseManagerTbService relations in EF, so that the changes actually get saved.
Add some unit tests for this.

NTBS-2720 Fix case manager TB service user-sync

---

ntbs-service/wwwroot/source/Components/NhsNumberDuplicateWarning.ts

Includes does not work in IE - oops! 
Tested and working in IE again.

NTBS-2768: No longer use includes in duplicate component

---

ntbs-service-unit-tests/Services/AlertServiceTest.cs
ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/Jobs/UnmatchedLabResultAlertsJob.cs
ntbs-service/Services/AlertService.cs

The unmatched lab result alert job was only checking for existing open alerts when determining whether a new alert needs to be created. Consequently, if an alert was manually closed, it was just being recreated on the next run. Here we fix this bug.

NTBS-2837 Do not create unmatched lab result alerts if duplicates exist

---

ntbs-service-unit-tests/DataAccess/AlertRepositoryTests.cs
ntbs-service/DataAccess/AlertRepository.cs

Display the names of legacy case managers on all alerts with a case manager

NTBS-2843 Show legacy case manager names on alerts on dashboard

---

ntbs-service/Models/Entities/TestData.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml

We validate manual test results on the edit manual test result page. This page makes it impossible to add new invalid test results, or to edit existing invalid results without correcting them.
On the test results page, when the user presses Save, the manual test results were being validated again, leading to the save failing and an error being shown. This fix is to bypass this validation, so that only the "Has a TB test been carried out?" question is validated when saving that page.

NTBS-2796 Do not show error on test results page for invalid manual test

---

ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service-unit-tests/Models/Entities/ClinicalDetailsTest.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Migrations/20211104164435_MoveMDRFieldsToMDRModel.Designer.cs
ntbs-service/Migrations/20211104164435_MoveMDRFieldsToMDRModel.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/ClinicalDetailsDisplay.cs
ntbs-service/Models/Entities/MDRDetails.cs
ntbs-service/Models/Entities/MDRDetailsDisplay.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MDRDetailsOverviewPartial.cshtml

Moved the 2 MDR conditional fields to the MDR model/page. I think there may still be some cleaning up to do, but wanted to get a review to make sure it looks okay otherwise. 

NTBS-2839: Move MDR fields

---

.github/workflows/backup-live-image.yml
.github/workflows/build-docker-image.yml
.github/workflows/ntbs-test-and-deploy.yml
ntbs-service/README.md
ntbs-service/deployments/dev.yml
ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/load-test.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/training.yml
ntbs-service/deployments/uat-phe.yml
ntbs-service/deployments/uat.yml
ntbs-service/kubernetes/README.md
scripts/release.sh

Update all the places where we currently use the Azure container registry to use the Github container registry instead
I _think_ I've found all of the places that need to be updated, but I'm not 100% certain.

NTBS-2663 Use github container registry

---

ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/Services/SpecimenService.cs

Now close the alert when a potential specimen is rejected. Caught while testing before QA

NTBS-2840: Remove alert when potential match is rejected

---

ntbs-service/Models/Entities/ClinicalDetails.cs

Allow a wider character set for the healthcare description field

NTBS-2878 Allow printable ASCII chars in healthcare description

---

ntbs-service/Program.cs
ntbs-service/Startup.cs

Make 3 config changes to make the site slightly more secure:
1. Increase the max-age of the strict-transport-security (HSTS) header to 2 years
2. Make the session cookie "secure"
3. Remove the Server header from the response
I've tested these changes by deploying to the azure `test` and PHE `dev` environments. Weirdly the strict-transport-security header is being overwritten in azure, but you can see that it has been set correctly on `dev`

NTBS-2891 Make config changes following pen test

---

ntbs-service-unit-tests/Helpers/UrlHelperTest.cs
ntbs-service/Helpers/UrlHelper.cs
ntbs-service/Pages/ContactDetails/Index.cshtml.cs

Sanitise the referer header value before putting it in a web page.
Do this using a new helper method, and add some unit tests for this

NTBS-2883 Fix XSS attack via referer header

---

ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml

Order by sample and test type, and result as well as test date when displaying manual tests.
---
<details>
<summary>Screenshot</summary>
</details>

NTBS-2871 Improve manual test ordering

---

ntbs-service/DataAccess/NotificationRepository.cs

Added a check that the notification has a treatment event that is over a year old

NTBS-2851: Add check for year old outcome to close inactive

---

ntbs-service/Migrations/20211124140116_AddResultReasonToTestResult.Designer.cs
ntbs-service/Migrations/20211124140116_AddResultReasonToTestResult.cs
ntbs-service/Models/Entities/ManualTestResult.cs
ntbs-service/Models/Enums/Result.cs
ntbs-service/Pages/Notifications/Edit/Items/ManualTestResult.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_ManualTestResult.cshtml
ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml
ntbs-service/wwwroot/css/testResults.scss
ntbs-service/wwwroot/source/Components/FilteredDropdown.ts

Added new NoResultReason field to manual test result.
This is only visible when the "No result" result is chosen.
Changed filteredDropdown to search for the "selectField" ref element recursively through the Vue component's children, so that we can use a `conditional-select-wrapper` inside a `filtered-dropdown`

NTBS-2813: New "No result reason" field

---

.github/workflows/run-load-tests.yml
load-tests/README.md
load-tests/gradle/build.gradle
load-tests/gradle/src/gatling/scala/Config.scala
load-tests/gradle/src/gatling/scala/ScenarioBuilders/CreateOrEditScenarioBuilder.scala
ntbs-service/deployments/load-test.yml

Update the load-test environment so that it is authenticated by Azure AD.
Update the load tests so they are able to test against an authenticated environment. This involves a manual step where the user needs to authenticate with the site under test and then provide their "cookie" header to the tests.
Update the github action so that it no longer runs on a schedule (it can't because of the manual step involved) and allows the user to upload the cookie header as a parameter.

Ntbs 2855 auth for load test

---

ntbs-service/Models/Entities/ManualTestResult.cs
ntbs-service/Models/Enums/Result.cs
ntbs-service/Pages/Notifications/Edit/Items/ManualTestResult.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_ManualTestResult.cshtml
ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml

Realised the line wasn't breaking with \n, so now using a `<br/>` tag

NTBS-2813: Add line break before no result reason

---

ntbs-service/Pages/Alerts/TransferRequest.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_ManualTestResult.cshtml
ntbs-service/wwwroot/source/Components/FilteredDropdown.ts

Set `waitForChildMount` to false for the TbService/CaseManager dropdown on the transfer request creation page, meaning that the case manager list will not be populated before the TbService is selected.

NTBS-2838 TransferRequest FilteredDropdown fix

---

ntbs-service/Pages/Notifications/NotificationChanges.cshtml.cs

Generate breadcrumbs on the `NotificationChanges` page, we weren't before for some reaon.

NTBS-2904 Fix breadcrumbs for NotificationChanges

---

ntbs-service/DataAccess/ReferenceDataRepository.cs

From QA: order the case managers on the transfer request page when JavaScript is disabled by ordering it server-side.

NBTS-2838 Order Case Managers on no-JS transfer request page

---

ntbs-service/wwwroot/source/Components/NavigationWithSubmenu.ts

Fix an issue where we close submenu dropdowns straight after opening them if we click on the arrow, because this is not the `<a>` tag and we treated it like clicking off the menu, because the `<i>` arrow is a child of the `<a>` tag instead of being the tag itself.
Note that the click box for this "image" is rotated because the image is defined entirely in CSS:

NTBS-2940 Fix dropdown click area

---

EFAuditer/CustomFields.cs
EFAuditer/EFAuditServiceExtensions.cs
ntbs-service/Services/NotificationService.cs

After thinking about it I think this is the nicest way we have to do this. The other option would be to override the EntityType with the name of the risk factor (eg. RiskFactorSmoking instead of RiskFactorDetails) but this seems strange as the object itself isn't named "RiskFactorSmoking" so it would not play nicely with our frontend. The logs now will look like this:
Where previously it would not have had the type at all.

NTBS-2936: Add custom field which will add type to audit changes

---

ntbs-service-unit-tests/Services/AuthorizationServiceTest.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Services/AuthorizationService.cs

It turns out regional users are able to accept transfers, we just weren't showing the alerts to them. So the only thing that needed to change in the end was which alerts we were filtering for regional users. I've added tests for the auth service, and fixed a tiny bug to do with what the banner shows when you accept a transfer.

NTBS-2941: Allow regional user to accept transfer

---

EFAuditer/EFAuditServiceExtensions.cs

This was happening for the SocialRiskFactor audits, as the flag was set but the RiskFactorDetails audits are the ones which we are adding "type" for.

NTBS-2936: Only add type if exists in dictionary

---

ntbs-service-unit-tests/Services/NotificationChangesServiceTest.cs
ntbs-service-unit-tests/TestData/auditLogsWithMultipleMatches.csv
ntbs-service/Services/NotificationChangesService.cs

Allow multiple simultaneous specimen matches to each appear on the notification changes page, without warning Sentry.

NTBS-2854 Allow multiple specimen matches

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/HospitalDetailsPageTests.cs
ntbs-service-unit-tests/DataMigration/CaseManagerImportServiceTests.cs
ntbs-service/DataMigration/CaseManagerImportService.cs
ntbs-service/Models/Entities/HospitalDetails.cs
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Services/AdUserService.cs

To satisfy the condition of "Any case manager that is already assigned to a notification should be allowed" I have gone with the approach of removing the case manager ID from the model state if the case manager ID matches. Let me know if you think this isn't the right approach. 
Removed the case manager dropdown JS validation, all this checks is if the user is in the TB service and actually you can never pick a user that isn't in the dropdown so this isn't needed. The error span is still there for any errors after submitting, which still works.
During user sync we now remove all case manager TB services from inactive users. 
During case manager import we never add any case manager TB services, and never set inactive users as IsCaseManager.
I haven't done anything about setting …

NTBS-2907: Case Manager changes

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service-unit-tests/Helpers/EpisodesHelperTest.cs
ntbs-service-unit-tests/Models/Entities/NotificationTest.cs
ntbs-service-unit-tests/Services/TreatmentOutcomesHelperTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Helpers/EpisodesExtensionMethods.cs
ntbs-service/Helpers/NotificationErrorGenerator.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Models/NotificationBannerModel.cs
ntbs-service/Models/Projections/NotificationForBannerModel.cs
ntbs-service/Models/TreatmentPeriod.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml
ntbs-service/Services/TreatmentOutcomesHelper.cs
ntbs-ui-tests/Steps/AssertSteps.cs

Main change is removing "HasDeathEventForPostMortemCase" as a notification property and replacing it with "IsPostMortemAndHasCorrectEvents".
This is used in a few places:
- Getting treatment events for display - only passes the death event out if true
- Getting the banner outcome - displays "Died" if true
- Getting yearly outcome - will pass only the death outcome if true, so the outcome will be died (only for the 1st year).
The validation on this property means you can't save data now which isn't consistent with post mortem data - this means the clinical details page on some notifications won't be able to be saved but [NTBS-2861](https://airelogic-nis.atlassian.net/browse/NTBS-2861) has been made to tackle this.

NTBS-2905: Post mortem changes

---

.github/workflows/build-docker-image.yml
.github/workflows/ntbs-test-and-deploy.yml
.github/workflows/ntbs-test.yml
.github/workflows/run-ui-tests.yml
Dockerfile
EFAuditer-tests/EFAuditer-tests.csproj
EFAuditer/EFAuditer.csproj
load-test-data-generation/load-test-data-generation.csproj
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service-unit-tests/Pages/HomePageTests.cs
ntbs-service-unit-tests/Services/NtbsSearchBuilderTest.cs
ntbs-service-unit-tests/Services/UserServiceTest.cs
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Migrations/20211223145732_UpgradeToDotNet6.Designer.cs
ntbs-service/Migrations/20211223145732_UpgradeToDotNet6.cs
ntbs-service/Models/Entities/HospitalDetails.cs
ntbs-service/Models/Entities/PatientDetails.cs
ntbs-service/Models/Entities/PatientDetailsDisplay.cs
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/UserService.cs
ntbs-service/ntbs-service.csproj
ntbs-ui-tests/ntbs-ui-tests.csproj

Upgrade to .NET 6. The most difficult thing here is that EF Core 6 did not play nicely with our data model (I'm about ~99% sure this is a bug in EF Core, rather than documented behaviour). The problem involved navigation properties on owned entities. Consequently, I've updated the context we're using so that the Hospital and Patient details are no longer owned by the Notification.
(We've experienced problems with ownership before, and it's something we want to move away from in general - see NTBS-2525 - so this is a step in the right direction).

Ntbs 2567 net 6 upgrade

---

ntbs-integration-tests/ContactDetailsPages/ContactDetailsPageTests.cs
ntbs-integration-tests/ContactDetailsPages/EditContactDetailsTests.cs
ntbs-integration-tests/Helpers/TestUser.cs
ntbs-integration-tests/HomePage/HomePageTests.cs
ntbs-integration-tests/LabResultsPage/LabResultsPageTests.cs
ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/NotificationPages/ChangesPageTests.cs
ntbs-integration-tests/NotificationPages/CreatePageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service-unit-tests/Pages/HomePageTests.cs
ntbs-service-unit-tests/Services/AuthorizationServiceTest.cs
ntbs-service-unit-tests/Services/UserServiceTest.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Models/Enums/UserType.cs
ntbs-service/Models/UserPermissionsFilter.cs
ntbs-service/Pages/Index.cshtml.cs
ntbs-service/Pages/LabResults/Index.cshtml.cs
ntbs-service/Services/AuthorizationService.cs
ntbs-service/Services/HomepageKpiService.cs
ntbs-service/Services/UserService.cs

I think there are probably some tests still to be written for when a user is both a TB service member and a regional user.
The main changes are that in GetUserPermissionsFilter we now no longer check if they have a service and then just get all the services - we get all services and regions regardless. Then there were a few changes to make with what used this permissions filter - eg in lab results we now concatenate together the lab results from TB service and regional membership. In the other places like homepage notifications, we could just bring 2 linq where statements together.

NTBS-2858: No longer split permissions into NHS/PHE (TB Service/Region)

---

ntbs-service-unit-tests/Helpers/EpisodesHelperTest.cs
ntbs-service/Helpers/EpisodesExtensionMethods.cs

Make not evaluated events ending if they are transferred abroad or other. Added tests.

NTBS-2982: Make some not evaluated outcomes ending events

---

ntbs-service-unit-tests/DataMigration/NotificationMapperTest.cs
ntbs-service-unit-tests/Models/Entities/NotificationTest.cs
ntbs-service/DataAccess/TreatmentEventRepository.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Helpers/EpisodesExtensionMethods.cs
ntbs-service/Helpers/NotificationHelper.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Services/NotificationService.cs

Always generate the starting event when a notification is submitted. 
Always generate the starting event when a notification is imported.
Fixed a bug with `ShouldBeClosed` where a post mortem notification wasn't being seen as having an outcome (as the diagnosis made event would be the last recorded event)

NTBS-3000: Add diagnosis made event for post mortem cases

---

load-tests/README.md
load-tests/gradle/src/gatling/scala/Config.scala
load-tests/gradle/src/gatling/scala/NtbsLoadTest.scala
ntbs-build/openshift-pipelines/image-streams/ntbs-image-stream.yml
ntbs-build/openshift-pipelines/pipelines/run-load-tests.yml
ntbs-build/openshift-pipelines/tasks/parse-gradle-results.yml
ntbs-build/openshift-pipelines/tasks/run-gradle.yml

Allow the load tests to configure the range of existing notifications

NTBS-2919 Add config for notification range in load tests

---

ntbs-integration-tests/Alerts/DismissAlertTests.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/Pages/Alerts/Dismiss.cshtml.cs
ntbs-service/Pages/Errors/400.cshtml
ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

When a request is made to dismiss an alert which is already closed, we allow the request to succeed, with a redirect to the notification overview page. (This is the same behaviour as if the alert was previously open).
The previous behaviour was that a null reference exception occurred and an Internal Server Error response was given. We believe that this was happening if the user clicked on the "Dismiss" link twice in quick succession.

NTBS-3008 Redirect to notification overview when dismissing closed alert

---

ntbs-build/openshift-pipelines/cron-jobs/publish-uat-databases-cron.yml
ntbs-build/openshift-pipelines/triggers/ntbs-publish-database-listener.yml
ntbs-build/openshift-pipelines/triggers/ntbs-publish-database-trigger.yml

As with all our openshift files, these are just here for reference, and in case we need to restore them to the cluster at some point.

NTBS-2918 Cron job for redeploying UAT databases at 12 on Sunday

---

scripts/publishTemporarilyUnavailablePageImage.ps1
temporarily-unavailable/README.md

Move temporarily unavailable image to github container registry
I have also updated the image source in the coming-soon deployment YAML file on openshift from 'ntbscontainerregistry.azurecr.io/temporarily-unavailable' to 'ghcr.io/publichealthengland/ntbs-service:temporarily-unavailable'

NTBS-3039 Move temporarily unavailable image to github container registry

---

ntbs-service/Services/AzureAdDirectoryService.cs

Only set AD groups, IsActive and any case manager TB services for enabled users. 
Do you think it's worth logging a warning that there's a user with AD group perms that isn't enabled when we find one? If we're going to have a report then it isn't hugely necessary, but it means we'd know sooner.

NTBS-3061: Only set AD groups and CMTBS for enabled users

---

ntbs-service/Pages/Alerts/TransferRejected.cshtml
ntbs-service/Pages/Search/Index.cshtml

Another button which needed to disable multiple clicks - the dismiss button on the page which tells you about a rejected transfer.

NTBS-3051: Allow dismiss on transfer rejection to only be clicked once

---

ntbs-service/Pages/Notifications/Edit/_SaveButton.cshtml

Change back link text when page has no editable content (social context - addresses, social context - venues and treatment events pages)

NTBS-1417 change back link text when page has no editable content

---

ntbs-build/openshift-pipelines/cron-jobs/cleanup-run-cron.yml
ntbs-build/openshift-pipelines/triggers/cleanup-runs.yml
ntbs-build/openshift-pipelines/triggers/ntbs-publish-database-trigger.yml
ntbs-build/openshift-pipelines/triggers/tekton-cleaner-listener.yml
ntbs-service/ntbs-service.csproj

The initial change here was to use a volume claim template, rather than an explicit PVC, in the cron job to publish databases. This is so that the cron job will continue to work even if our PVC is retired, and a new one created.
However, while testing I discovered that used PVCs will only be deleted when all pipeline/task runs referencing them have been deleted. Therefore, in order to stop the number of PVCs that are hanging around in OpenShift from getting out of control, I've added a cleanup cron job so that pipeline/task runs older than 1 week will be deleted.

NTBS-3090 Move publish cron job onto volume claim template

---

ntbs-service/Pages/Notifications/Edit/SocialContextVenues.cshtml

The original designs have the exact wording as "help pin identifying transmissions settings" here https://ntbs-uk.atlassian.net/browse/NTBS-427 so I am only 90% sure it's definitely wrong. But it must be!

NTBS-3095: Fix wording on social context venue page

---

ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Shared/_NotificationOverviewLayout.cshtml

Something that came back from QA

NTBS-2832: Don't show overview share message to users with no permissions

---

ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Shared/_NotificationOverviewLayout.cshtml
ntbs-service/wwwroot/css/notificationView.scss

Example screenshot:
At the moment, it will show the message to all users, whenever there is a pending transfer. This means that the information can be duplicated with the alert (as in the example above) but I think this looks ok.

NTBS-3088 Show message when a transfer is pending

---

.github/workflows/build-publish-dacpac-image.yml
ntbs-build/openshift-pipelines/image-streams/ntbs-image-stream.yml
ntbs-build/openshift-pipelines/tasks/deploy-image.yml
ntbs-build/publish-dacpac-image/Dockerfile
ntbs-build/publish-dacpac-image/README.md

Remove all refereneces to the now defunct `ntbscontainerregistry`.
Add an action to build the `publish-dacpac` image and push it to the github container registry.
Update the image stream in OpenShift so that it sources the `publish-dacpac` image from the correct location.

NTBS-3112 Use github container registry for publish-dacpac image

---

ntbs-service/package.json
ntbs-service/webpack.prod.js
ntbs-service/wwwroot/source/app.ts

The build was failing because the Sentry project no longer exists
Removed references to Sentry from build code
Tested by deploying to dev and then performing action which would have previously resulted in a Sentry alert - no issues observed.

NTBS 3123 - remove references to Sentry
