ntbs-service/Data/Legacy/LTBRSearcher.cs

NTBS-257: Switch to using new LTBR schema.

---

ntbs-service-tests/UnitTests/Services/NotificationServiceTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Migrations/20190916094035_ChangeRiskFactorMentalHealthToStatus.Designer.cs
ntbs-service/Migrations/20190916094035_ChangeRiskFactorMentalHealthToStatus.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Models/RiskFactorMentalHealth.cs
ntbs-service/Models/SocialRiskFactors.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/Edit/_RiskFactorPartial.cshtml
ntbs-service/Services/NotificationService.cs

NTBS-89: Fix Typos and Remove checkboxes from Mental Health Issues question on Social Risk Factors Page
- Fix Typos
- Delete Mental Health Risk Factor Table and depict mental health as a status on Social Risk Factors class
- Remove time period options form mental health issues question

NTBS-89: Fix Typos and Remove checkboxes from Mental Health Issues

---

ntbs-service/Migrations/20190916100452_AddUnknownToSitesOfDisease.Designer.cs
ntbs-service/Migrations/20190916100452_AddUnknownToSitesOfDisease.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Models/Site.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Startup.cs
ntbs-service/wwwroot/css/site.css
ntbs-service/wwwroot/source/Components/DateComparison.ts
ntbs-service/wwwroot/source/Components/ValidateDate.ts

Some markups after Nancy's comments on https://airelogic-nis.atlassian.net/browse/NTBS-143
Mostly minor, but bigger change for DateComparison.ts - there was a bug that meant that clearing the date didn't clear the warning and only one warning at a time was ever shown; this is now fixed.

NTBS-143: Fix date comparison warnings and other small fixes.

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml

There is a git hook setup that prevents me from just pushing to master without review (didn't even know that was possible) so you'll need to review these very exciting changes :)

NTBS-143: Final fixes.

---

ntbs-service/Helpers/NotificationErrorGenerator.cs
ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Models/ContactTracing.cs
ntbs-service/Models/Episode.cs
ntbs-service/Models/ModelBase.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/NotificationSite.cs
ntbs-service/Models/PatientDetails.cs
ntbs-service/Models/PatientTBHistory.cs
ntbs-service/Models/SocialRiskFactors.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Create.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Patient.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml.cs
ntbs-service/Pages/Notifications/NotificationErrorSummary.cshtml
ntbs-service/Pages/Notifications/NotificationsBase.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Shared/_NotificationLayout.cshtml
ntbs-service/ntbs-service.csproj

Perform Full Validation when form is submitted and display validation errors if necessary
- Add Library that provides conditional Required attribute
- Added base class that contains flag that other required fields will be validated based on
- Display errors and navigate to page
- Page Displays errors when navigated from error page

Ntbs 207 Submission verification step

---

ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/wwwroot/source/app.ts

NTBS-386: Inlcude promise polyfill for compatibility with IE.

---

ntbs-service/Pages/Shared/_Footer.cshtml
ntbs-service/wwwroot/css/site.scss

Make links open in new tab and change margin to padding (for background color reasons) and give a bit more space for footer for smaller screens where it gets squashed

NTBS-316-qa

---

ntbs-service/Migrations/20190930105532_MakeTreatmentFlagsNullable.Designer.cs
ntbs-service/Migrations/20190930105532_MakeTreatmentFlagsNullable.cs
ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/Validations/ValidationAttributes.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/ValidationModel.cs
ntbs-service/wwwroot/source/Components/ValidateMultiple.ts

See Nancy's QA comments: https://airelogic-nis.atlassian.net/browse/NTBS-145

NTBS-145: QA markups.

---

ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Immunosupression.cshtml
ntbs-service/Pages/Notifications/Edit/Immunosupression.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs

Add placeholder view controllers to avoid losing data when submitted from unimplemented pages
When submit button is clicked on unimplemented page then Patient model is submitted without a data and therefore losing existing data

NTBS-437: Add placeholder view controllers to avoid losing data

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Immunosupression.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Patient.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs
ntbs-service/Pages/Notifications/NotificationsBase.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs

Ntbs 213: Fixing the compilation error

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Immunosupression.cshtml
ntbs-service/Pages/Notifications/Edit/Immunosupression.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_PaginationPartial.cshtml
ntbs-service/Pages/Notifications/NotificationsBase.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs

Navigate to Overview page when editing Notified notification
- When editing the notified notification applying stricter validation will be available when 213 is merged.
- Rename button to "Save" and navigate to Overview page when editing Notified notification

NTBS-185: Navigate to Overview page when editing Notified notification

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/Pages/Notifications/Edit/_PaginationPartial.cshtml
ntbs-service/Pages/Notifications/NotificationsBase.cshtml.cs
ntbs-service/Pages/Shared/_NotificationLayout.cshtml

Use values for submit and save buttons
Use "name" and "value" for submit and save button in order to distinguish them on submit. This will avoid having handler in url and therefore causing other validation errors not getting updated after save button is clicked.

NTBS-439: Use values for submit and save buttons

---

ntbs-service/Models/ContactTracing.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ContactTracingOverviewPartial.cshtml

All total to be null and display 0 if null on Contact Tracing page
Fixing some bugs on Overview page (Contact Tracing bit)

NTBS-438: All total to be null and display 0 if null on Contact Tracing

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml

Ntbs 438 Move validate-date tag into conditional div

---

.gitignore
EFAuditer/.gitignore
ntbs-service/.gitignore
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs
ntbs-service/wwwroot/source/Components/YearComparison.ts
ntbs.sln

Add files necessary for solution to be easily worked on in visual studios.
Assorted code quality improvements such as formatting, closing tags, etc. The code cleanup wasn't done extensively only in the areas of code I have touched so far. 
Will endeavor to boy scout this as much as possible over the coming couple of weeks.
- [X ] Automated tests are passing locally.
- [ X] Check the feature looks and works correctly in IE11

Ntbs visual studio

---

ntbs-service/Models/ModelBase.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Episode.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Patient.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml.cs
ntbs-service/Pages/Notifications/NotificationsBase.cshtml.cs
ntbs-service/Services/NotificationService.cs

Full Validation was not done when clicking "save" on notified notifications

NTBS-213: Fix validation errors on notified notifications

---

ntbs-service/Migrations/NtbsContextModelSnapshot.cs
ntbs-service/Models/NotificationSite.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs

Fix validation errors for Notification Sites on Clinical Details page
- Having Notification referenced in NotificationSite was causing circular nesting
- Other site description should be validated properly now

NTBS-185: Fix validation errors for Notification Sites on Clinical Details page

---

ntbs-service/Migrations/20191010090322_MakeClinicalDetailRadiosNullable.Designer.cs
ntbs-service/Migrations/20191010090322_MakeClinicalDetailRadiosNullable.cs
ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Search/Index.cshtml

Make Clinical Details buttons nullable. Add "treatment started"
Have discussed with Nancy and we decided to change wording in "Patient started treatment" radios

Ntbs 213 : Make Clinical Details buttons nullable. Add "treatment started" legend

---

ntbs-service/Migrations/20191010153554_AddHivTestStatus.Designer.cs
ntbs-service/Migrations/20191010153554_AddHivTestStatus.cs
ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Models/Enums/HIVTestStatus.cs
ntbs-service/Models/Notification.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

NTBS-188 Add HIV test status

---

ntbs-service/Services/NotificationSearchBuilder.cs

This change got lost when merging in in NotificationSearchBuilder from Farman's changes so adding it back in

fix for searching by nhs number

---

ntbs-integration-tests/ClinicalDetailsPageTests.cs
ntbs-integration-tests/NtbsWebApplicationFactory.cs
ntbs-service/Authentication/DummyAuthHandler.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Test.json

Added test environment so wouldn't use webpack and require node for integration tests.

NTBS-153: Make integration tests run on docker.

---

ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs

NTBS-251: Fix tests

---

ntbs-service/wwwroot/source/Components/ValidatePostcode.ts

NTBS-128: Fix error accesing index 0 of a non-array

---

.gitignore
ntbs-integration-tests/.gitignore
ntbs-integration-tests/Helpers/Constants.cs
ntbs-integration-tests/Helpers/HttpClientExtensions.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-integration-tests/TestRunnerBase.cs
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service/Models/ModelBase.cs
ntbs-service/Models/Notification.cs
ntbs-service/Pages/Notifications/Denotify.cshtml
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_PaginationPartial.cshtml
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Pages/Shared/_NotificationBanner.cshtml
ntbs-service/Pages/Shared/_NotificationLayout.cshtml

Adjust a number of NotificationStatus checks to treat Denotified status equivalently to Notified (apart from with regard to allowing user to 'Denotify' notification.
Add integration testing, and small improvements to adjacent tests.

NTBS-251: QA Fixes and Integration testing 

---

ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_TravelDetailsPartial.cshtml
ntbs-service/Pages/Notifications/Edit/_VisitorDetailsPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TravelOverviewPartial.cshtml
ntbs-service/Services/NotificationService.cs
ntbs-service/wwwroot/source/Components/ValidateTravelOrVisit.ts

Handle full validation for visitor/travel details for both dynamic validation and for post-submitted notifications.
Additionally include the SR-accessibility improvements for validation tags.
Have not ticked Automated tests passing, as intend to expand coverage of integration testing to this page, but keen to get the fix in and QAed before end of sprint.
- [] Automated tests are passing locally.

NTBS-135: Handle full validation for travel/visitors

---

ntbs-integration-tests/Helpers/TestDocumentExtensions.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/TravelPageTests.cs
ntbs-service/Models/TravelDetails.cs

Add integration testing for travel/visitor screen

NTBS-135: Add integration testing for Travel/Visitor

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml

NTBS-445: Add required keyword to required fields

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml.cs

NTBS-126: Fix integration test errors

---

ntbs-service/Models/Notification.cs
ntbs-service/Models/NotificationBannerModel.cs
ntbs-service/Pages/Notifications/OverviewPartials/_PatientOverviewPartial.cshtml
ntbs-service/Pages/Shared/_NotificationBanner.cshtml

NTBS-126: Show notification date on banner and overview page

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs

Ntbs 126: Unskip skipped denotify page test

---

ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml

NTBS-445: Use nhs-fieldset. Add required to Notification date

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service/Migrations/20191024145734_AddDOTAndEnhancedCaseManagement.Designer.cs
ntbs-service/Migrations/20191024145734_AddDOTAndEnhancedCaseManagement.cs
ntbs-service/Models/ClinicalDetails.cs
ntbs-service/Models/Notification.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

Add boolean flags using radios to clinical details page for DOT and enhanced case management
- [] Check the feature looks and works correctly in IE11

NTBS-527 add dot/vot and enhanced case management fields

---

ntbs-service/Migrations/20191024165952_AdjustEthnicityMappingsAndOrderings.cs

Adjust migration to map deleted values to new single white ethnicity.

NTBS-498: Set unused white ethnicities to single white entry

---

ntbs-integration-tests/BasicTests.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/Helpers/WebApplicationExtensions.cs
ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/ComorbidityPageTests.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/EpisodesPageTests.cs
ntbs-integration-tests/NotificationPages/ImmunosuppressionPageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-integration-tests/NotificationPages/PatientPageTests.cs
ntbs-integration-tests/NotificationPages/TravelPageTests.cs
ntbs-integration-tests/SearchPage/SearchPageTests.cs
ntbs-integration-tests/TestRunnerBase.cs
ntbs-integration-tests/TestServices/TestUserService.cs
ntbs-service-unit-tests/Services/UserServiceTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Models/TBService.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Messages.cs
ntbs-service/Pages/Notifications/NotEditableWarning.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_PatientOverviewPartial.cshtml
ntbs-service/Pages/Notifications/UnauthorizedWarning.cshtml
ntbs-service/Pages/Shared/_NotificationLayout.cshtml
ntbs-service/Services/AuthorizationService.cs
ntbs-service/Services/UserService.cs

Integration tests now added for permissions.
I decided it was easiest to mock out the response from the user service for this, rather than playing around with different config files for example.
I just realised we should add a unit test for UserService too to ensure this behaviour is tested - I want to carry on with the e2e test setup ticket for now though, should I just add a TODO so we don't forget?

NTBS-202: Integration tests.

---

ntbs-integration-tests/NotificationPages/DeletePageTests.cs

typo in delete page tests which needs to be fixed (client to Client)

NTBS-162 fix tests from merge 

---

ntbs-service/deployments/int.yml

NTBS-505: Remove softwire adfs endpoint for int

---

ntbs-service/appsettings.json
ntbs-service/deployments/research.yml
ntbs-service/deployments/test.yml

NTBS-505: Change test and research env to point to new Adfs

---

ntbs-service/appsettings.json

NTBS-505: Revert Adfs Url to ntbs.uksouth.cloudapp.azure.com

---

ntbs-service/Startup.cs

NTBS-578: Remove BackchannelHttpHandler as SSL is set up

---

ntbs-service-unit-tests/README.md
ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Pages/Notifications/Delete.cshtml.cs
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Services/NotificationService.cs

NTBS-192: Changes to the testing approach for notificationService

---

ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/README.md
ntbs-service/TagHelpers/GovUkWarningTextHelper.cs

Add taghelper for govuk-warning-text
Add further help for ui tests in the readme

NTBS-451: Gov uk warning text tagHelper

---

ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/CreateNotifications.feature.cs

Fix e2e test for new tb service to hospital mapping

NTBS-262 fix selenium test for new TB service to hospital mapping

---

ntbs-service/README.md
ntbs-service/deployments/README.md

NTBS-509 Document SSL changes

---

ntbs-service/appsettings.json

NTBS-652: Use new ADFS endpoint

---

ntbs-service/Pages/Shared/_Header.cshtml

NTBS-604: Add phase banner

---

ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_EpisodeOverviewPartial.cshtml

Correct case manager display in the notification overview.
Additional small change for WAVE check, and screen reader improvement

NTBS-660: Add case manager display in overview

---

ntbs-service/Pages/Search/Index.cshtml
ntbs-service/Pages/Shared/_Form_Layout.cshtml
ntbs-service/Pages/Shared/_Layout.cshtml
ntbs-service/Pages/Shared/_NoForm_Layout.cshtml
ntbs-service/wwwroot/css/_breakpoints.scss
ntbs-service/wwwroot/css/notification.scss
ntbs-service/wwwroot/css/notificationBanner.scss
ntbs-service/wwwroot/css/search.scss
ntbs-service/wwwroot/source/app.ts
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/CreateNotifications.feature.cs

Improve UI of search page
Make it responsive
Change background of search results part of the page
Add Create notification buttons at top and bottom of search results section

Ntbs 583 search design improvements

---

ntbs-service/Pages/Search/Index.cshtml
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/CreateNotifications.feature.cs

Changed a couple of ids which broke creating notifications on ui tests, also realised I had done unnecessary id mapping on inputs and labels instead of using asp-for

NTBS-583 fix tests for new ids 

---

ntbs-service/Pages/Search/Index.cshtml
ntbs-service/wwwroot/css/search.scss

Had a QA mark ups from some issues with merges that should be fixed now.
Added correct alignment for labels
2nd create notification button only displays when over 3 results are returned
Make errors appear on new lines (they were appearing on the same line in the flexbox previously and pushing the content over)

NTBS-583 qa mark ups

---

ntbs-service/ntbs-service.csproj

Does this warrant a whole PR? Only because this might be the best thing I've done as TL all project 😎😁

Remove ExpressiveAnnotations warning

---

ntbs-service/Pages/Notifications/Denotify.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Pages/Shared/_NotificationLayout.cshtml
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/CreateNotifications.feature.cs
ntbs-ui-tests/Steps/Steps.cs

Sad amount of workarounds, but i've raised a tech debt ticket too. At the very least, it does cover the journey, which was missed out before.

Add ui test for notification denotify

---

ntbs-service/Pages/Notifications/Delete.cshtml
ntbs-service/Pages/Notifications/Denotify.cshtml
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/Comorbidities.cshtml
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml
ntbs-service/Pages/Notifications/Edit/Episode.cshtml
ntbs-service/Pages/Notifications/Edit/Immunosuppression.cshtml
ntbs-service/Pages/Notifications/Edit/Patient.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/Edit/Travel.cshtml
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Pages/Notifications/NotificationErrorSummary.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Pages/Shared/_NotificationLayout.cshtml
ntbs-service/Pages/Shared/_NotificationLayoutWithAlertsAndSideMenu.cshtml
ntbs-ui-tests/Features/CreateNotifications.feature.cs

Will cover checkist on monday, raising now to get eyes on it if anybody wants changes.

NTBS-NONE: Restructure layout 'inheritance'

---

ntbs-service/Models/Alert.cs
ntbs-service/Models/Notification.cs
ntbs-service/Pages/Index.cshtml

Update table formatting based off feedback from QA

NTBS-366 table formatting for QA

---

ntbs-service-unit-tests/Models/NotificationTest.cs

I thought I was better than the tests last time, turns out I wasn't 😢

NTBS-366 fix tests for new date format

---

ntbs-service/Pages/Index.cshtml

NTBS-366 put case manager and TB service on new lines in table header

---

ntbs-service/Authentication/DummyAuthHandler.cs
ntbs-service/Pages/Alerts/Dismiss.cshtml.cs

Add email to dummyAuth details and record user email when dismissing alert.

NTBS-366 record user email when dismissing alert

---

ntbs-service/Pages/Notifications/LinkedNotifications.cshtml.cs
ntbs-service/Services/NotificationService.cs

Made a new branch and forgot I'm still not on upsource, RIP PR 172

NTBS-662 remove group ID on delete

---

ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Helpers/RouteHelper.cs
ntbs-service/Migrations/20191127164638_AddMDRDetails.Designer.cs
ntbs-service/Migrations/20191127164638_AddMDRDetails.cs
ntbs-service/Migrations/20191127164739_CreateMDRDetailsForExistingNotifications.Designer.cs
ntbs-service/Migrations/20191127164739_CreateMDRDetailsForExistingNotifications.cs
ntbs-service/Models/MDRDetails.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/NotificationInfo.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Shared/_NotificationLayoutWithAlertsAndSideMenu.cshtml
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/ValidationService.cs
ntbs-service/wwwroot/source/Components/NotificationInfo.ts
ntbs-service/wwwroot/source/Components/ValidateRelatedNotification.ts
ntbs-service/wwwroot/source/app.ts

MDR details page, with a new component for fetching related notification and one for displaying notification details.
Still need to fix/add ui tests

NTBS-638: Add MDR Details page.

---

ntbs-integration-tests/SearchPage/SearchPageTests.cs
ntbs-service/Helpers/CssClassHelpers.cs
ntbs-service/Models/Enums/NotificationStatus.cs
ntbs-service/Models/Notification.cs
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Pages/Shared/_NotificationBanner.cshtml
ntbs-service/Pages/Shared/_NotificationLayout.cshtml
ntbs-service/Pages/Shared/_NotificationLayoutWithAlertsAndSideMenu.cshtml
ntbs-service/wwwroot/css/_colors.scss
ntbs-service/wwwroot/css/notification.scss
ntbs-service/wwwroot/css/notificationBanner.scss

Remove some unnecessary padding around banner
Adjust colouring under different notification statuses

Ntbs 603 banner colours

---

Dockerfile-uitests
ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/ComorbidityPageTests.cs
ntbs-integration-tests/NotificationPages/DeletePageTests.cs
ntbs-integration-tests/NotificationPages/DenotifyPageTests.cs
ntbs-integration-tests/NotificationPages/EpisodesPageTests.cs
ntbs-integration-tests/NotificationPages/ImmunosuppressionPageTests.cs
ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-integration-tests/NotificationPages/PatientPageTests.cs
ntbs-integration-tests/NotificationPages/TravelPageTests.cs
ntbs-integration-tests/TestRunnerBase.cs
ntbs-service/Migrations/NtbsContextModelSnapshot.cs
ntbs-service/README.md
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/CreateNotifications.feature.cs
ntbs-ui-tests/Hooks/DriverSetup.cs
ntbs-ui-tests/Hooks/TestSettings.cs
ntbs-ui-tests/Steps/Steps.cs

This includes some of the remaining test markups from my MDR Details review, as well as fixes to ui tests (which were failing before) - mainly we need to add a lot more waits to ensure everything on the page is loaded correctly... it's a bit clunky but I guess that's the nature of end-to-end testing..
They also still don't run the same way on jenkins as locally - I think you mentioned something about javascript files not being pulled in properly for testing? As the autocomplete feature has broken some tests locally (which are fixed here). I will look into it soon, but wanted to carry on with social context venues first

Integration test fixes and fix ui tests.

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Shared/_NotificationLayoutWithAlertsAndSideMenu.cshtml

NTBS-370 review mark ups (refactor a method and improve comments)

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Migrations/20191128192316_IndexNotificationStatusOnNotificationsTable.Designer.cs
ntbs-service/Migrations/20191128192316_IndexNotificationStatusOnNotificationsTable.cs
ntbs-service/Migrations/20191202142051_AddNotificationStatusAndSubmissionDateIndex.Designer.cs
ntbs-service/Migrations/20191202142051_AddNotificationStatusAndSubmissionDateIndex.cs
ntbs-service/Migrations/20191202175622_AddMultiIndexOnAlertsTable.Designer.cs
ntbs-service/Migrations/20191202175622_AddMultiIndexOnAlertsTable.cs
ntbs-service/Models/NtbsContext.cs
ntbs-service/Pages/Index.cshtml.cs
ntbs-service/Services/AuthorizationService.cs

NTBS-666: Get queryable notification for home page. Index notification table on notification status

NTBS-666: Get queryable notification for home page. Index on notification status

---

ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Models/Notification.cs
ntbs-service/Models/NotificationInfo.cs
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MDRDetailsOverviewPartial.cshtml
ntbs-service/wwwroot/css/notificationView.scss
ntbs-service/wwwroot/source/Components/NotificationInfo.ts

NTBS-638: QA markups.

---

ntbs-service/Pages/Notifications/Edit/TestResults.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml
ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml
ntbs-service/wwwroot/css/site.scss

Add class for reduced table font-size, and use it in test results overview table.

NTBS-NONE: Implement reduced table font-size

---

ntbs-service-unit-tests/Helpers/EnumExtensionsTest.cs
ntbs-service/Helpers/EnumExtensions.cs
ntbs-service/Models/Entities/Alert.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/DenotificationDetails.cs
ntbs-service/Models/Entities/Episode.cs
ntbs-service/Models/Entities/ImmunosuppressionDetails.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/NotificationSite.cs
ntbs-service/Models/Entities/PatientDetails.cs
ntbs-service/Models/Enums/AlertType.cs
ntbs-service/Models/Enums/DenotificationReason.cs
ntbs-service/Models/Enums/HIVTestStatus.cs
ntbs-service/Models/SearchParameters.cs
ntbs-service/Pages/Notifications/Delete.cshtml.cs
ntbs-service/Services/ValidationService.cs

Use DisplayName attribute exclusively, and configure anything looking for display attributes to look for display name attribute.

NTBS-NONE: Use DisplayName attribute exclusively

---

ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Models/Entities/Notification.cs

Ntbs 511: Add Notification Sites to imported notification

---

ntbs-service-unit-tests/Helpers/EnumExtensionsTest.cs
ntbs-service/Helpers/EnumExtensions.cs
ntbs-service/Models/Entities/Alert.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/DenotificationDetails.cs
ntbs-service/Models/Entities/Episode.cs
ntbs-service/Models/Entities/ImmunosuppressionDetails.cs
ntbs-service/Models/Entities/MDRDetails.cs
ntbs-service/Models/Entities/ManualTestResult.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/NotificationSite.cs
ntbs-service/Models/Entities/PatientDetails.cs
ntbs-service/Models/Entities/SocialContextVenue.cs
ntbs-service/Models/Entities/TestData.cs
ntbs-service/Models/Entities/TravelDetails.cs
ntbs-service/Models/Entities/VisitorDetails.cs
ntbs-service/Models/Enums/AlertType.cs
ntbs-service/Models/Enums/DenotificationReason.cs
ntbs-service/Models/Enums/HIVTestStatus.cs
ntbs-service/Models/SearchParameters.cs
ntbs-service/Pages/Notifications/Delete.cshtml.cs
ntbs-service/Services/ValidationService.cs

Exclusively use DisplayAttribute over DisplayNameAttribute

NTBS-NONE: Flip displayName attribute to display attribute

---

Jenkinsfile
ntbs-service/appsettings.Development.json
ntbs-service/wwwroot/source/Components/ValidateMultiple.ts

When attempted in replay https://jenkins2.softwire.com/job/phe-ntbs/job/master/495/
the speed-up seemed, real, though some if it will be due to replay using caching more.
Worth pushing out and seeing if it helps overall. I have a suspicion there might be some
inefficiency from using same build files though!
Also added an icon to the slack message to help make distinct from sql migrations

Return back to parallel test runs

---

ntbs-service/Pages/Notifications/UnauthorizedWarning.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

Hide alerts, show manage notification
All tests pass.
TODO: Conor asked Nancy whether we want to remove the audit link for now while it doesn't have any functionality - waiting on a reply.

NTBS-NONE fix unauthorised overview behaviour

---

ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service/Models/NtbsContext.cs
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/DenotifyNotifications.feature
ntbs-ui-tests/Helpers/Utilities.cs
ntbs-ui-tests/Hooks/DriverSetup.cs
ntbs-ui-tests/SeleniumServerFactory.cs
ntbs-ui-tests/ntbs-ui-tests.csproj
ntbs-ui-tests/xunit.runner.json

I didn't manage to get the db seeding to work :( Spent a few hours today trying to at least find the cause of the issue, but I couldn't get any useful information into the debug logs...
I've however written up my detailed findings in this tech debt ticket:
https://airelogic-nis.atlassian.net/browse/NTBS-725

Run UI tests sequentially in different features

---

ntbs-service/Pages/Notifications/Edit/SocialContextAddresses.cshtml
ntbs-service/Pages/Notifications/Edit/SocialContextVenues.cshtml
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml

Just add ViewData["CurrentPage"] to new pages to make sure side menu still highlights which page you are on

NTBS-NONE add current page to social context pages and test results

---

ntbs-service/Migrations/20191217134213_MakeDateToNullableForContextVenues.Designer.cs
ntbs-service/Migrations/20191217134213_MakeDateToNullableForContextVenues.cs
ntbs-service/Models/Entities/SocialContextAddress.cs
ntbs-service/Models/Entities/SocialContextBase.cs
ntbs-service/Models/Entities/SocialContextVenue.cs
ntbs-service/Models/Entities/VenueType.cs
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextAddress.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextVenue.cshtml
ntbs-service/Pages/Notifications/Edit/SocialContextAddresses.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialContextVenues.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_SocialContextAddressesOverviewPartial.cshtml
ntbs-service/Pages/Shared/_SocialContextAddressesTable.cshtml
ntbs-service/Pages/Shared/_SocialContextVenuesTable.cshtml

QA markups for Social context pages. Merging already as Nancy wants to close these tickets today, but opening a review for your records :)

NTBS-427/589: Social Context QA markups.

---

Jenkinsfile

NTBS-NONE: Add slack icon back in to build update

---

ntbs-service-unit-tests/Services/LegacySearchBuilderTest.cs
ntbs-service/Services/LegacySearchBuilder.cs
ntbs-service/Services/LegacySearchService.cs

Add searching by family name, given name and sex.
Indexes are irrelevant for strings wildcarded both at the front and end of a string so aren't applicable here.
Index for Sex Id is in progress - waiting on discussion from https://github.com/PublicHealthEngland/ntbs-data-migration/pull/24 to be resolved (hopefully tomorrow 17/12/2019)
No UI changes.

NTBS-165 Fix multi filtered queries and add tests

---

ntbs-service-unit-tests/Services/LegacySearchBuilderTest.cs
ntbs-service-unit-tests/Services/NtbsSearchBuilderTest.cs
ntbs-service/Helpers/DisplayExtensionMethods.cs
ntbs-service/Services/LegacySearchBuilder.cs
ntbs-service/Services/LegacySearchService.cs
ntbs-service/Services/NtbsSearchBuilder.cs

I've included all 3 on this ticket as relatively simple changes (apart from postcode which is soft blocked by a data stream ticket - NTBS-754).
I will be leaving DON/DOB searching ticket as in progress as a marker that indexing is still needed and will be implemented soon once https://github.com/PublicHealthEngland/ntbs-data-migration/pull/27#issuecomment-567055275 is merged.

Ntbs 168 legacy search by birth country, postcode, Date of birth and date of notification

---

ntbs-migration-tests/NotificationImportTest.cs
ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/DataMigration/NotificationMapper.cs

NTBS-512: Add Hospital Id and TB Service

---

EFAuditer-tests/UnitTests/Services/EFAuditServiceExtensionsTest.cs
ntbs.sln

Update tests to match the new audit data, and increase coverage to cover the new EFAuditer interfaces.

NTBS-723: Update EFAuditer tests

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/TreatmentEventsEditPageTests.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs

While adding error summaries, I introduced a bug that I failed to pick up in either manual testing or integration testing... Added an integration test for it.

NTBS-572: Fix behaviour for adding treatment outcomes

---

ntbs-integration-tests/MockServices/MockCultureAndResistanceService.cs
ntbs-integration-tests/MockServices/MockSpecimenService.cs
ntbs-integration-tests/NotificationPages/TestResultsPageTests.cs
ntbs-integration-tests/NtbsWebApplicationFactory.cs
ntbs-service/Models/Entities/CultureAndResistance.cs
ntbs-service/Models/Entities/Specimen.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_LabResults.cshtml
ntbs-service/Pages/Notifications/Edit/_SpecimenDetails.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml
ntbs-service/Services/CultureAndResistanceService.cs
ntbs-service/Services/SpecimenService.cs
ntbs-service/Startup.cs
ntbs-service/deployments/int.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml
ntbs-service/wwwroot/css/site.scss
ntbs-service/wwwroot/css/testResults.scss

Ntbs 382: Surface matched reference lab samples from Labs DB

---

ntbs-service/Models/Entities/Specimen.cs
ntbs-service/Services/SpecimenService.cs

Small changeset to rename reporting db fields to accompany a changeset in: https://github.com/PublicHealthEngland/ntbs-reporting
Intended to smooth development work for NTBS-380.

NTBS-NONE: Rename specimen fields

---

ntbs-service/Models/Entities/CultureAndResistance.cs
ntbs-service/Models/Entities/Specimen.cs
ntbs-service/Pages/Notifications/Edit/_LabResults.cshtml
ntbs-service/Pages/Notifications/Edit/_SpecimenDetails.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml
ntbs-service/Services/CultureAndResistanceService.cs
ntbs-service/Services/SpecimenService.cs

NTBS-NONE: Rename aminoglycocide to aminoglycoside

---

ntbs-service-unit-tests/Services/LegacySearchBuilderTest.cs
ntbs-service/Pages/Search/Index.cshtml.cs
ntbs-service/Services/LegacySearchBuilder.cs

Added legacy search by TB service, index for migration database found in PR here https://github.com/PublicHealthEngland/ntbs-data-migration/pull/39

NTBS-167 legacy search by TB service

---

ntbs-service/Helpers/NotificationFieldFormattingHelper.cs
ntbs-service/Models/Entities/CultureAndResistance.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/Specimen.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml
ntbs-service/Pages/Notifications/Edit/_LabResults.cshtml
ntbs-service/Pages/Notifications/Edit/_SpecimenDetails.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml
ntbs-service/Services/SpecimenService.cs
ntbs-service/wwwroot/css/testResults.scss

NTBS-382: Make ui changes on test results page

---

ntbs-service/Pages/Notifications/Edit/_VisitorDetailsPartial.cshtml

NTBS-749 use autocomplete dropdown component for visitor details partial

---

EFAuditer/RootEntities.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml.cs
ntbs-service/Services/AuditService.cs
ntbs-service/Services/MockSpecimenService.cs
ntbs-service/Services/SpecimenService.cs

NTBS-697: Audit log specimen unmatching

---

ntbs-service/DataMigration/NotificationImportHelper.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Program.cs
ntbs-service/Properties/MigrationConfig.cs
ntbs-service/deployments/int.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml
scripts/buildAndReleaseLive.ps1
scripts/migrationAnalysisSnippets.js

Last few remaining pieces for trial migration

Ntbs 431 trial migration

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Migrations/20200116005147_ConvertClusterIdToVarchar.Designer.cs
ntbs-service/Migrations/20200116005147_ConvertClusterIdToVarchar.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Notifications/Edit/SocialContextAddresses.cshtml.cs
ntbs-service/Pages/Notifications/Edit/SocialContextVenues.cshtml.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClusterInformationOverviewPartial.cshtml
ntbs-service/Pages/Shared/_ClusterInformation.cshtml

NTBS-378: Add Cluster count to Social context pages and cluster id to Overview

---

ntbs-ui-tests/Features/DenotifyNotifications.feature
ntbs-ui-tests/Hooks/TestSettings.cs
ntbs-ui-tests/Steps/Steps.cs

NTBS-NONE: Add headless, and remove test ambiguity

---

ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Enums/DotStatus.cs
ntbs-service/Models/Enums/Status.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

NTBS-557: Show formatted information on Overview page for additional items on Clinical Details

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Notifications/OverviewPartials/_EpisodeOverviewPartial.cshtml

NTBS-721 add denotification details overview page

---

ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml

NTBS-557: Validate order of first home visit

---

ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/Shared/_HomepageKpiRow.cshtml
ntbs-service/Pages/_HomepageKpiDetails.cshtml
ntbs-service/wwwroot/css/home.scss

NTBS-364: Add shadow to KPi boxes. Add heading

---

ntbs.sln.DotSettings

Result of telling rider to stop whining about some words' spelling - looks like it can be shared, so should be useful for making it give fewer false positives across the board!

Add team dictionary file

---

ntbs-service-unit-tests/Models/NotificationTest.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ComorbiditiesAndImmunosuppresionOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ContactTracingOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_EpisodeOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MDRDetailsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_PatientOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_PreviousHistoryOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_SocialContextAddressesOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_SocialContextVenuesOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_SocialRiskFactorsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TravelOverviewPartial.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Pages/Shared/_NotificationEditLayout.cshtml
ntbs-service/Pages/Shared/_NotificationLayoutWithSideMenu.cshtml
ntbs-service/Pages/Shared/_NotificationOverviewLayout.cshtml
ntbs-service/Pages/Shared/_NotificationUnderBannerNav.cshtml
ntbs-service/Pages/Shared/_SocialContextAddressesTable.cshtml
ntbs-service/Pages/Shared/_SocialContextVenuesTable.cshtml
ntbs-service/Services/MockCultureAndResistanceService.cs
ntbs-service/wwwroot/css/notificationView.scss

Part of the changes towards 864. Still outstanding some functional changes, but thought I would raise this in-case it can get in quicker than I can do the other stuff. To avoid conflicts with changes further down the way.

NTBS-864: Remove LHS menu on overview

---

ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsSites.cshtml

Move miliary site of disease into pulmonary sections

NTBS-823: Move miliary disease site into pulmonary section

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Models/Ethnicities.cs
ntbs-service/Models/Sexes.cs

Collective PR for changes to the mapper required as part of fixing migration issues (https://airelogic-nis.atlassian.net/browse/NTBS-792) - commits refer to individual sub-tasks

NTBS-792 Changes to the mapper

---

ntbs-migration-tests/NotificationImportTest.cs
ntbs-service/DataMigration/NotificationImportService.cs

Before these would cause exception on saving (due to Foreign Key violations), which are more difficult to parse when trying to understand reason for failure

NTBS-877 Check hospital exists on imported validation

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/PreviousHistoryPageTests.cs
ntbs-service/Models/Entities/PatientTBHistory.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs

Update validation and change some copy text

NTBS-720 apply new validation to the previous TB diagnosis year

---

ntbs-service-unit-tests/Services/LegacySearchBuilderTest.cs
ntbs-service/Services/LegacySearchBuilder.cs
ntbs-service/Services/LegacySearchService.cs
ntbs-service/appsettings.Development.json

Fix search for postcode moving to addresses from demographics

Ntbs 738 fix search

---

.github/pull_request_template.md
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClusterInformationOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TravelOverviewPartial.cshtml
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml
ntbs-service/Pages/Shared/_Footer.cshtml
ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Pages/Shared/_Layout.cshtml
ntbs-service/Pages/Shared/_NotificationOverviewLayout.cshtml
ntbs-service/Pages/Shared/_NotificationUnderBannerNav.cshtml
ntbs-service/wwwroot/css/footer.scss
ntbs-service/wwwroot/css/header.scss
ntbs-service/wwwroot/css/notification.scss
ntbs-service/wwwroot/css/notificationBanner.scss
ntbs-service/wwwroot/css/notificationView.scss
ntbs-service/wwwroot/css/site.scss
ntbs-service/wwwroot/source/Components/PrintButton.ts
ntbs-service/wwwroot/source/app.ts

Add stylings for making overview print nicely.
Add a print button (JS-only)
Remove some redundant links

NTBS-359: Add styling for printing a notification overview page

---

ntbs-service/Pages/Search/Index.cshtml

NTBS-738 add copy text

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Pages/LegacyNotifications/Index.cshtml.cs

NTBS-565: Find notification Id from legacyId

---

ntbs-integration-tests/NotificationPages/TreatmentEventsEditPageTests.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/Shared/_TreatmentEventTable.cshtml

Show edit links on editable treatment events
Add transfer alert note to transfer events

NTBS-400 only show edit links on editable treatment events

---

ntbs-integration-tests/NotificationPages/PreviousHistoryPageTests.cs
ntbs-service/Models/Entities/PatientTBHistory.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_PreviousHistoryOverviewPartial.cshtml

qa markups (make validations inclusive and copy text changes) as per https://airelogic-nis.atlassian.net/browse/NTBS-720

NTBS-720 qa markups

---

ntbs-service-unit-tests/Jobs/DataQualityAlertsJobTest.cs
ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Jobs/DataQualityAlertsJob.cs
ntbs-service/Migrations/NtbsContextModelSnapshot.cs
ntbs-service/Models/Entities/DataQualityTreatmentOutcome12.cs
ntbs-service/Models/Entities/DataQualityTreatmentOutcome24.cs
ntbs-service/Models/Entities/DataQualityTreatmentOutcome36.cs
ntbs-service/Models/Enums/AlertType.cs

NTBS-362: Treatment outcome data quality alerts

---

EFAuditer-tests/UnitTests/Services/EFAuditServiceExtensionsTest.cs
EFAuditer/EFAuditServiceExtensions.cs
EFAuditer/EFAuditer.csproj
EFAuditer/Interfaces/IHasRootEntityForAuditing.cs
EFAuditer/Interfaces/IOwnedEntityForAuditing.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/Comorbidity.cs
ntbs-service/Models/Entities/ContactTracing.cs
ntbs-service/Models/Entities/DenotificationDetails.cs
ntbs-service/Models/Entities/DrugResistanceProfile.cs
ntbs-service/Models/Entities/Episode.cs
ntbs-service/Models/Entities/ImmunosuppressionDetails.cs
ntbs-service/Models/Entities/MDRDetails.cs
ntbs-service/Models/Entities/ManualTestResult.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/NotificationSite.cs
ntbs-service/Models/Entities/PatientDetails.cs
ntbs-service/Models/Entities/PatientTBHistory.cs
ntbs-service/Models/Entities/RiskFactorDetails.cs
ntbs-service/Models/Entities/SocialContextBase.cs
ntbs-service/Models/Entities/SocialRiskFactors.cs
ntbs-service/Models/Entities/TestData.cs
ntbs-service/Models/Entities/TravelDetails.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Models/Entities/VisitorDetails.cs

Change auditing interface names to be more explicitly related to auditing.

NTBS-NONE: Adjust auditing interface names to be more specific

---

ntbs-service/DataAccess/UserRepository.cs
ntbs-service/Models/Entities/CaseManagerTbService.cs

Check for a change in CaseManagerTbServices before updating so that updating the same entities doesn't cause an insert.

NTBS-834 only update CaseManagerTbServices if they have changed

---

ntbs-service/Pages/Index.cshtml

NTBS-746 rename search button

---

ntbs-service/DataAccess/UserRepository.cs

Remove items after enumeration instead of during which breaks it

NTBS-834 don't remove items during enumeration

---

ntbs-service/Helpers/RouteHelper.cs
ntbs-service/Models/Entities/MBovisAlert.cs

Fix routing of mbovis and treatment outcome alerts

NTBS-659 fix routing of alerts

---

.dockerignore
Dockerfile
ntbs-service/deployments/live.yml
scripts/release.sh

This will allow the app to connect to the db cluster servers using kerberos
* The dockerfile change allows the app's container access to kerberos libraries, in particular to the `kinit` command
* The `live.yml` changes make us run a `krb5-authenticator` container based on a an image (created in https://digitaltools.phe.org.uk/browse/IH-156) and give the app container access to the credential cache that krb5-authenticator uses.
* I've updated secrets on openshift to new connection strings int he format of https://www.connectionstrings.com/microsoft-data-sqlclient/trusted-connection/. The `Trusted connection` argument makes it authenticate through kerberos

NTBS-811 Add kerberos authenticator container

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/BasicEditPageTests.cs
ntbs-integration-tests/NotificationPages/MBovisOccupationExposurePageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/DataAccess/MBovisOccupationExposureRepository.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Helpers/RouteHelper.cs
ntbs-service/Migrations/20200220153033_AddMBovisOccupationExposureTable.Designer.cs
ntbs-service/Migrations/20200220153033_AddMBovisOccupationExposureTable.cs
ntbs-service/Models/Entities/MBovisDetails.cs
ntbs-service/Models/Entities/MBovisOccupationExposure.cs
ntbs-service/Models/Enums/OccupationSetting.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/MBovisOccupationExposure.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/NewMBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/MBovisOccupationExposures.cshtml
ntbs-service/Pages/Notifications/Edit/MBovisOccupationExposures.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MBovisUnpasteurisedMilkConsumptions.cshtml.cs
ntbs-service/Pages/Notifications/Overview.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisOccupationExposureOverviewPartial.cshtml
ntbs-service/Pages/Shared/_MBovisExposureToKnownCaseTable.cshtml
ntbs-service/Pages/Shared/_MBovisOccupationExposureTable.cshtml
ntbs-service/Pages/Shared/_MBovisUnpasteurisedMilkConsumptionTable.cshtml
ntbs-service/Pages/Shared/_SideMenu.cshtml
ntbs-service/Services/NotificationService.cs
ntbs-service/Startup.cs

NTBS-933: Mbovis occupation exposure pages

---

ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Services/MockSpecimenService.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/SpecimenService.cs
ntbs.sln.DotSettings

Also fix the unmatch query (recent change made it more than a SP, but dapper was still being told it's meant to execute an SP).

NTBS-958 Unmatch all lab results on denotification

---

.dockerignore
.gitmodules
.idea/.idea.ntbs/.idea/vcs.xml
Dockerfile
Dockerfile-uitests
NuGet.Config
README.md
ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisAnimalExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisUnpasteurisedMilkConsumption.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsOther.cshtml
ntbs-service/README.md
ntbs-service/ntbs-service.csproj

Add forked version of library as a submodule of this repository. Fork has been modified to expose a `.nupkg` for consumption by this application.
Add `NuGet.Config` to point to the package at a solution level.
Modify docker scripts to move necessary files/folders around.

NTBS-964: Use forked taghelper library

---

ntbs-service/wwwroot/source/Components/AutocompleteSelect.ts
ntbs-service/wwwroot/source/Components/CascadingDropdown.ts
ntbs-service/wwwroot/source/Components/DateComparison.ts
ntbs-service/wwwroot/source/Components/NotificationInfo.ts
ntbs-service/wwwroot/source/Components/ValidateContactTracing.ts
ntbs-service/wwwroot/source/Components/ValidateDate.ts
ntbs-service/wwwroot/source/Components/ValidateInput.ts
ntbs-service/wwwroot/source/Components/ValidateMultiple.ts
ntbs-service/wwwroot/source/Components/ValidatePostcode.ts
ntbs-service/wwwroot/source/Components/ValidateRelatedNotification.ts
ntbs-service/wwwroot/source/Components/ValidateRequiredCheckboxes.ts
ntbs-service/wwwroot/source/Components/YearComparison.ts
ntbs-service/wwwroot/source/app.ts

NTBS-NONE: Use export default consistently in components

---

ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20200227144905_AddEnhancedCaseManagementLevelField.Designer.cs
ntbs-service/Migrations/20200227144905_AddEnhancedCaseManagementLevelField.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

NTBS-881: Add Enhanced Case Management levels to clinical details page

---

ntbs-service/Models/Entities/Notification.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml
ntbs-service/Services/TreatmentOutcomeService.cs

Rendering the treatment outcomes only when needed

NTBS-936 use same logic as other places for rendering treatment outcomes

---

ntbs-service/Jobs/HangfireJobScheduler.cs
ntbs-service/Properties/ScheduledJobConfig.cs
ntbs-service/Properties/ScheduledJobsConfig.cs
ntbs-service/Startup.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.json
ntbs-service/deployments/live.yml

I'm not entirely settled on the overriding structure I've laid out for the configs - but happy to have a better approach suggested.

NTBS-991: Add configuration for scheduled jobs

---

ntbs-service/Pages/Notifications/OverviewPartials/_MBovisAnimalExposureOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisExposureToKnownCasesOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisOccupationExposureOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisUnpasteurisedMilkConsumptionOverviewPartial.cshtml
ntbs-service/Pages/Shared/_MBovisAnimalExposureTable.cshtml
ntbs-service/Pages/Shared/_MBovisExposureToKnownCaseTable.cshtml
ntbs-service/Pages/Shared/_MBovisOccupationExposureTable.cshtml
ntbs-service/Pages/Shared/_MBovisUnpasteurisedMilkConsumptionTable.cshtml

Adjust overview content for M. bovis cases
Adjust ordering for milk products in table

NTBS-371 - QA markups

---

ntbs-service-unit-tests/Services/EnhancedSurveillanceAlertsServiceTest.cs
ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/Pages/Alerts/Dismiss.cshtml.cs
ntbs-service/Pages/Index.cshtml.cs
ntbs-service/Services/AlertService.cs
ntbs-service/Services/DrugResistanceProfileService.cs
ntbs-service/Services/EnhancedSurveillanceAlertsService.cs

Be more explicit in alert objects when alerts are in the open status or not
Rework scheduled jobs to explicitly fail if reporting database is feeding in bad data

NTBS-981: Scheduled jobs cleanup

---

ntbs-integration-tests/TestServices/TestUserService.cs
ntbs-service/Services/UserService.cs
ntbs-service/Startup.cs

An attempt to solve recurring MARS issues.

NTBS-990: Await async method for recording user login

---

ntbs-service/Services/AdDirectoryService.cs
ntbs-service/appsettings.Development.json

NTBS-1001: Follow LDAP referrals

---

ntbs-service/wwwroot/source/Components/ConfirmComponent.ts
ntbs-service/wwwroot/source/Components/FormLeaveChecker.ts
ntbs-service/wwwroot/source/Polyfills/ArrayFromPolyfill.js
ntbs-service/wwwroot/source/app.ts

Add Array.from polyfill for use by vue-acccessible-modal in IE11.
Adjust logic in FormLeaveChecker to handle promise rejection.

NTBS-1008: Sentry reported JS issues

---

.idea/.idea.ntbs/riderModule.iml
EFAuditer/EFAuditer.csproj
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/ntbs-service.csproj
ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-ui-tests/ntbs-ui-tests.csproj

Update dependencies. 
Skipped update of nhsuk-frontend because that will almost certainly introduce changes to UI elements that are going to be difficult to pinpoint.

NTBS-NONE: Update dependencies

---

ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/Services/TreatmentOutcomeService.cs

Fix treatment outcome logic -> add missing include and account for treatment events after a treatment ending event

NTBS-936 qa markups

---

ntbs-service/Pages/Logout.cshtml.cs
ntbs-service/Startup.cs
ntbs-service/deployments/int.yml
ntbs-service/deployments/test.yml
ntbs-service/deployments/uat.yml

NTBS-642: Redirect to login page when logging out

---

ntbs-service/DataAccess/DataQualityRepository.cs

I definitely checked the previous logic to see if it was able to run locally... but it seems that my testing was insufficient...

NTBS-1022: Refactor to allow LINQ to SQL to do its job

---

ntbs-service/DataMigration/NotificationMapper.cs

Have not tested this, as I do not currently know of a good route of doing so - but throwing the PR up for a review of the logic.

NTBS-1020: Add dummy value logic for immunosuppression import

---

ntbs-service/Pages/Notifications/Edit/Items/_SocialContextAddress.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextVenue.cshtml
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml
ntbs-service/Pages/Search/Index.cshtml

Autocomplete and autofill seem to be 2 distinct functionalities that overlap in weird ways in chrome:
https://stackoverflow.com/questions/57367813/2019-chrome-76-approach-to-autocomplete-off
Have turned off autocomplete on the search form, and have additionally disabled autofill on a select number of fields in the notification pages to secure against this potentially exposing data protection issues.

NTBS-1031: Fix autocomplete and autofill issues in chrome

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Services/TreatmentOutcomeService.cs

Only count still on treatment events as holding events

NTBS-936 change holding event logic

---

ntbs-service/Pages/Shared/_Layout.cshtml
ntbs-service/Pages/Shared/_NotificationLayout.cshtml
ntbs-service/Pages/Shared/_NotificationLayoutWithSideMenu.cshtml

Add skip links, including skip links for notification form pages.

NTBS-1037: Add skip links for keyboard navigation

---

ntbs-service/Pages/Notifications/Edit/ContactTracing.cshtml
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisAnimalExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisUnpasteurisedMilkConsumption.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextAddress.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextVenue.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_TreatmentEvent.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Travel.cshtml
ntbs-service/Pages/Notifications/Edit/TreatmentEvents.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ContactTracingOverviewPartial.cshtml

Updated copy text
Add cancel & go back button to social context pages
Made titles on treatment events + M. bovis pages only render when the table is rendered
Remove the double enhanced case management
Fix routing on drafts from previous TB -> treatment events

NTBS-868 modify copy text and add cancel go back to all pages missing it

---

ntbs-service/DataMigration/NotificationMapper.cs

Don't overwrite treatments events when adding transfer events

NTBS-1017 don't overwrite treatment events when adding transfer events

---

ntbs-ui-tests/Features/CreateNotifications.feature

Didn't account for new routing breaking ui tests in last PR - fix is here.

NTBS-838 fix ui tests for new routing

---

ntbs-service/Pages/Notifications/OverviewPartials/_MBovisAnimalExposureOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisExposureToKnownCasesOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisOccupationExposureOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_MBovisUnpasteurisedMilkConsumptionOverviewPartial.cshtml
ntbs-service/Pages/Shared/_MBovisAnimalExposureTable.cshtml
ntbs-service/Pages/Shared/_MBovisExposureToKnownCaseTable.cshtml
ntbs-service/Pages/Shared/_MBovisOccupationExposureTable.cshtml
ntbs-service/Pages/Shared/_MBovisUnpasteurisedMilkConsumptionTable.cshtml

Change of approach for mbovis on the overview.

NTBS-1040: Display current state of mbovis tables in all situations

---

ntbs-service/DataAccess/NotificationRepository.cs

fix includes for linked notifications

NTBS-NONE fix includes for linked notifications

---

ntbs-service/Pages/Notifications/OverviewPartials/_ContactTracingOverviewPartial.cshtml

Rename copy text on contact tracing page for overview page

NTBS-868 reflect copy text change on overview page

---

ntbs-integration-tests/AdminPages/CloneNotificationTests.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Models/Entities/MBovisExposureToKnownCase.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Admin/CloneNotification.cshtml
ntbs-service/Pages/Admin/CloneNotification.cshtml.cs
ntbs-service/Pages/Admin/Index.cshtml
ntbs-service/Pages/NotificationSummary.cshtml
ntbs-service/Pages/NotificationSummary.cshtml.cs
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisExposureToKnownCase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/NotificationEditModelBase.cs
ntbs-service/Services/NotificationCloningService.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/ValidationService.cs
ntbs-service/Startup.cs
ntbs-service/wwwroot/source/Components/ValidateInput.ts
ntbs-service/wwwroot/source/Components/ValidateRelatedNotification.ts
ntbs-service/wwwroot/source/helpers.ts

NTBS-1039 admin clone notification

---

ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Migrations/20200316123418_ChangeSmokingStatusToRiskFactor.Designer.cs
ntbs-service/Migrations/20200316123418_ChangeSmokingStatusToRiskFactor.cs
ntbs-service/Migrations/20200316165435_BackfillSocialRiskFactorsSmoking.Designer.cs
ntbs-service/Migrations/20200316165435_BackfillSocialRiskFactorsSmoking.cs
ntbs-service/Models/Entities/SocialRiskFactors.cs
ntbs-service/Models/Entities/SocialRiskFactorsDisplay.cs
ntbs-service/Models/Enums/RiskFactorType.cs
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_SocialRiskFactorsOverviewPartial.cshtml
ntbs-service/Services/NotificationService.cs

NTBS-887: Add social risk factors for smoking

---

ntbs-service/Pages/Notifications/Edit/_SpecimenDetails.cshtml
ntbs-service/Services/SpecimenQueryHelper.cs

NTBS-980: Show laboratory name on matched specimens

---

ntbs-service/Pages/Notifications/Overview.cshtml

NTBS-1044: Displayed notification is closed text on overview if it is closed

---

ntbs-service/Pages/Admin/Migration.cshtml
ntbs-service/Pages/Search/Index.cshtml
ntbs-service/wwwroot/source/Components/DateInput.ts
ntbs-service/wwwroot/source/Components/ValidateDate.ts
ntbs-service/wwwroot/source/app.ts

Mix date-input into date-validate to automatically apply it to all date inputs with validation.
Wrap other inputs in <date-input> directly.

NTBS-1063 Add date-input vue component with auto-focus shift

---

ntbs-service/DataAccess/AlertRepository.cs
ntbs-service/DataAccess/DataQualityRepository.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Jobs/DataQualityAlertsJob.cs
ntbs-service/Migrations/20200330190001_AddDuplicateNotificationAlert.Designer.cs
ntbs-service/Migrations/20200330190001_AddDuplicateNotificationAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityPotentialDuplicateAlert.cs
ntbs-service/Models/Enums/AlertType.cs
ntbs-service/Services/AlertService.cs

Add alerts for potential duplicate notifications and add alerts for the suspect notifications.

Ntbs 879 dq alert on potential duplicates

---

ntbs-service-unit-tests/Jobs/DataQualityAlertsJobTest.cs

NTBS-879 fix tests

---

ntbs-integration-tests/AdminPages/CloneNotificationTests.cs
ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/Migrations/20200331001758_ChangeCaseInUkStatusToNotifiedToPHEStatus.Designer.cs
ntbs-service/Migrations/20200331001758_ChangeCaseInUkStatusToNotifiedToPHEStatus.cs
ntbs-service/Migrations/20200331002156_AddNotifiedToPHEStatusToMbovis.Designer.cs
ntbs-service/Migrations/20200331002156_AddNotifiedToPHEStatusToMbovis.cs
ntbs-service/Migrations/20200331083437_MakeRelatedNotificationIdOptional.Designer.cs
ntbs-service/Migrations/20200331083437_MakeRelatedNotificationIdOptional.cs
ntbs-service/Migrations/20200331223058_MakeNotifiedToPheStatusRequired.Designer.cs
ntbs-service/Migrations/20200331223058_MakeNotifiedToPheStatusRequired.cs
ntbs-service/Models/Entities/MBovisExposureToKnownCase.cs
ntbs-service/Models/Entities/MDRDetails.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Items/MBovisExposureToKnownCase.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml.cs
ntbs-service/Pages/Notifications/OverviewPartials/_MDRDetailsOverviewPartial.cshtml
ntbs-service/Pages/Shared/_MBovisExposureToKnownCaseTable.cshtml

NTBS-1045: Make changes to Mdr details page and Mbovis Exposure to Known cases

---

ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-service/Models/Validations/ValidationHelper.cs

NTBS-1045: Fix Integration test

---

ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Services/MockSpecimenService.cs
ntbs-service/Services/SpecimenService.cs

NTBS-1073: Specify whether matching specimen on migrating legacy notification

---

ntbs-service/Models/Entities/NotificationDisplay.cs
ntbs-service/Pages/Notifications/NotificationModelBase.cs
ntbs-service/Pages/Notifications/Overview.cshtml.cs
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

NTBS-1062: Navigate to latest linked notification if notification is more than a year old

---

EFAuditer/EFAuditServiceExtensions.cs
ntbs-service/Authentication/DummyAuthHandler.cs
ntbs-service/Middleware/AuditGetRequestMiddleware.cs
ntbs-service/Pages/Alerts/Dismiss.cshtml.cs
ntbs-service/Pages/Alerts/TransferRejected.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/LabResults/Index.cshtml.cs
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Startup.cs

NTBS-1302 Use UPN claim, not email to transport username

---

ntbs-service/Models/Entities/Alerts/TransferAlert.cs

NTBS-1284 Add notification id to transfer alert audit records

---

ntbs-service/DataAccess/NotificationRepository.cs

NTBS-1325: Include Case Manager when querying for Linked Notifications

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-service-unit-tests/Services/AdDirectoryServiceTest.cs
ntbs-service-unit-tests/Services/UserServiceTest.cs
ntbs-service/appsettings.json

Ntbs 1306: Change NTA to NTS

---

ntbs-service/Migrations/20200507161032_AllowNullsInMbovisFields.Designer.cs
ntbs-service/Migrations/20200507161032_AllowNullsInMbovisFields.cs
ntbs-service/Models/Entities/MBovisAnimalExposure.cs
ntbs-service/Models/Entities/MBovisOccupationExposure.cs
ntbs-service/Models/Entities/MBovisUnpasteurisedMilkConsumption.cs
ntbs-service/Models/SearchParameters.cs
ntbs-service/Models/Validations/ValidationAttributes.cs
ntbs-service/Models/Validations/ValidationHelper.cs

NTBS-1366 relax M. bovis validation

---

ntbs-service/Pages/Shared/_TreatmentEventTable.cshtml

NTBS-1337: Sort treatment events in ascending order of event date

---

ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/Comorbidity.cs
ntbs-service/Models/Entities/ImmunosuppressionDetails.cs
ntbs-service/Models/Entities/MBovisDetails.cs
ntbs-service/Models/Entities/MDRDetails.cs
ntbs-service/Models/Entities/PatientTBHistory.cs
ntbs-service/Models/Entities/SocialRiskFactors.cs
ntbs-service/Models/Entities/TestData.cs
ntbs-service/Models/Entities/TravelDetails.cs
ntbs-service/Models/Entities/VisitorDetails.cs
ntbs-service/Pages/Admin/CloneNotification.cshtml
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/PreviousHistory.cshtml
ntbs-service/Pages/Notifications/Edit/SocialRiskFactors.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsDates.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsOther.cshtml
ntbs-service/Pages/Notifications/Edit/_ComorbidityImmunosuppression.cshtml
ntbs-service/Pages/Notifications/Edit/_ComorbidityStatuses.cshtml
ntbs-service/Pages/Notifications/Edit/_LabResults.cshtml
ntbs-service/Pages/Notifications/Edit/_TravelDetailsPartial.cshtml
ntbs-service/Pages/Notifications/Edit/_VisitorDetailsPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_ComorbiditiesAndImmunosuppresionOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_HospitalDetailsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_PatientOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TestResultsOverviewPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_TreatmentEventsOverviewPartial.cshtml

Ntbs 1353: Copy text changes

---

ntbs-service/Pages/Index.cshtml
ntbs-service/Pages/_HomepageKpiDetails.cshtml
ntbs-service/wwwroot/css/home.scss

NTBS-1403: Add date period under KPIs

---

ntbs-service/Pages/Notifications/CaseManagerDetails.cshtml
ntbs-service/Pages/Shared/_NotificationUnderBannerNav.cshtml

NTBS-1434: Display Case manager details on draft notifications

---

ntbs-service/Models/Entities/User.cs
ntbs-service/Pages/ContactDetails/Edit.cshtml
ntbs-service/Pages/ContactDetails/Edit.cshtml.cs

NTBS-1434: Display cancel link on contact details edit page. Do not validate that page on load.

---

ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome12.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome24.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome36.cs

Corresponding migration change in https://github.com/publichealthengland/ntbs-data-migration/pull/80

NTBS-1506 update migration of previous history page

---

ntbs-service/Pages/Notifications/CaseManagerDetails.cshtml.cs
ntbs-service/Pages/Notifications/LinkedNotifications.cshtml.cs
ntbs-service/Pages/Shared/_NotificationOverviewLayout.cshtml

NTBS-1434: Do not show permission on linked notification and contact details. Show breadcrumbs

---

ntbs-service/Models/NotificationBannerModel.cs
ntbs-service/Pages/ContactDetails/Edit.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_HospitalDetailsOverviewPartial.cshtml
ntbs-service/Pages/Search/Index.cshtml
ntbs-service/Pages/Shared/_NotificationBanner.cshtml
ntbs-service/wwwroot/css/notificationBanner.scss

NTBS-1515: Make Case Managers on banner and overview a link to contact details

---

ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Pages/ContactDetails/Index.cshtml
ntbs-service/Pages/ContactDetails/Index.cshtml.cs
ntbs-service/Pages/ServiceDirectory/Region.cshtml
ntbs-service/Pages/ServiceDirectory/Region.cshtml.cs

NTBS-1516: Add breadcrumbs on contact details to access service directory

---

ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/ClinicalDetailsDisplay.cs
ntbs-service/Models/Validations/ValidationAttributes.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

Two separate bugs tackled (by commit)

NTBS-1468, NTBS-1490 bug fixes

---

ntbs-service/Pages/ServiceDirectory/Index.cshtml
ntbs-service/Pages/ServiceDirectory/Region.cshtml
ntbs-service/Pages/ServiceDirectory/SearchResults.cshtml
ntbs-service/Pages/ServiceDirectory/SearchResults.cshtml.cs
ntbs-service/Services/CaseManagerSearchService.cs

NTBS-1517: Do not trigger search for empty string. Allow search multiple words

---

ntbs-service-unit-tests/Models/Entities/Alerts/ClinicalDetailsTest.cs
ntbs-service/DataAccess/NtbsContext.cs
ntbs-service/DataMigration/NotificationMapper.cs
ntbs-service/Migrations/20200626103119_ChangeDotFromBoolToStatus.Designer.cs
ntbs-service/Migrations/20200626103119_ChangeDotFromBoolToStatus.cs
ntbs-service/Models/Entities/Alerts/DataQualityDotVotAlert.cs
ntbs-service/Models/Entities/ClinicalDetails.cs
ntbs-service/Models/Entities/ClinicalDetailsDisplay.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml

Also set the isDotOffered value in the import mapper correctly (it wasn't being pulled in atm)
Migration repo changes: https://github.com/publichealthengland/ntbs-data-migration/pull/82

NTBS-1461 Move IsDotOffered from bool to Status

---

ntbs-integration-tests/Helpers/TestDocumentExtensions.cs
ntbs-integration-tests/NotificationPages/SocialContextAddressEditPageTests.cs
ntbs-integration-tests/NotificationPages/SocialContextVenueEditPageTests.cs
ntbs-migration-tests/NotificationImportTest.cs
ntbs-service/DataMigration/ImportLogger.cs
ntbs-service/DataMigration/NotificationImportService.cs
ntbs-service/Migrations/20200708114456_UpdateSocialContextValidationRules.Designer.cs
ntbs-service/Migrations/20200708114456_UpdateSocialContextValidationRules.cs
ntbs-service/Models/Entities/SocialContextAddress.cs
ntbs-service/Models/Entities/SocialContextBase.cs
ntbs-service/Models/Entities/SocialContextBaseDisplay.cs
ntbs-service/Models/Entities/SocialContextVenue.cs
ntbs-service/Models/Entities/SocialContextVenueDisplay.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextAddress.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextVenue.cshtml
ntbs-service/Pages/Shared/_SocialContextAddressesTable.cshtml
ntbs-service/Pages/Shared/_SocialContextVenuesTable.cshtml

Ntbs 1592 relax social context pages validation

---

.idea/.idea.ntbs/riderModule.iml
EFAuditer-tests/EFAuditer-tests.csproj
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-migration-tests/ntbs-migration-tests.csproj
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/Helpers/NotificationHelper.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Models/Enums/TreatmentEventType.cs
ntbs-service/Pages/Notifications/Edit/ClinicalDetails.cshtml.cs
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Services/TreatmentOutcomeService.cs
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Steps/Steps.cs
ntbs-ui-tests/ntbs-ui-tests.csproj

NTBS-1341 tweak treatment start event

---

ntbs-service/Models/Entities/PreviousTbHistory.cs
ntbs-service/Pages/Notifications/Edit/PatientDetails.cshtml

Updates to occurrence and added helper text for address

---

ntbs-service/Jobs/ExampleStoredProcedureJob.cs
ntbs-service/Jobs/GenerateReportingDataJob.cs
ntbs-service/Jobs/HangfireJobScheduler.cs
ntbs-service/Jobs/StoredProcedureJobBase.cs
ntbs-service/Properties/ScheduledJobsConfig.cs
ntbs-service/appsettings.json

Add Hangfire job to call Generate Reporting Data stored procedure via nightly job.

Adding Support to Generate Reporting Data with Hangfire Jobs.

---

ntbs-service/Services/AzureAdDirectoryService.cs

Updated the user sync job to use direct group membership rather than transitive membership.

Changed User sync to only retrieve groups that user is direct member of.

---

ntbs-service/DataAccess/DataQualityRepository.cs

ntbs-1993
Updating how the two lists of notifications that have been identified as duplicates are merged.

Fixed issue where notifications were not being added as expected.

---

ntbs-service-unit-tests/Services/DrugResistanceProfileServiceTest.cs
ntbs-service/DataAccess/NotificationRepository.cs
ntbs-service/Models/Entities/Notification.cs
ntbs-service/Models/Projections/NotificationForDrugResistanceImport.cs
ntbs-service/Services/DrugResistanceProfileService.cs
ntbs-service/Services/EnhancedSurveillanceAlertsService.cs
ntbs-service/Services/NotificationService.cs

Initial attempt at improving performance of the drug resistance import job.
I'm merging this now so that we can deploy to an environment with enough data to do a meaningful test.

NTBS-2034 Load only necessary data for notification

---

ntbs-service/appsettings.Development.json
ntbs-service/package-lock.json
ntbs-service/package.json

Update the development configuration to allow the code to run locally, and add a TypeScript type dependency to help VS to build the project.

Local development updates

---

ntbs-integration-tests/ContactDetailsPages/EditContactDetailsTests.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/TestServices/TestUserService.cs
ntbs-service/DataAccess/UserRepository.cs
ntbs-service/Helpers/ClaimsPrincipalExtensionMethods.cs
ntbs-service/Middleware/AuditGetRequestMiddleware.cs
ntbs-service/Models/Entities/User.cs
ntbs-service/Pages/Alerts/Dismiss.cshtml.cs
ntbs-service/Pages/Alerts/TransferRejected.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/ContactDetails/Edit.cshtml.cs
ntbs-service/Pages/ContactDetails/Index.cshtml.cs
ntbs-service/Pages/LabResults/Index.cshtml.cs
ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Notifications/Edit/TestResults.cshtml.cs
ntbs-service/Services/NotificationService.cs
ntbs-service/Services/UserService.cs
ntbs-service/Startup.cs

Restrict users from being able to edit other users' contact details.

NTBS-2096 Do not allow user to edit other users

---

ntbs-service/README.md
ntbs-ui-tests/README.md
ntbs-ui-tests/ntbs-ui-tests.csproj
ntbs-ui-tests/package-lock.json
ntbs-ui-tests/package.json
ntbs-ui-tests/start_selenium.ps1
ntbs-ui-tests/test.ps1

* Update Selenium and some C# packages for UI tests
* Change test script to work better in Powershell, check for updates
before testing, and use a more robust server-closing process.
* Add a start server script for those who would prefer to run their
Selenium server in the background and launch the tests from inside an
IDE (allowing for better CSharp debugging among other things).
* Add UI tests README

NTBS-NONE Fix UI tests

---

ntbs-service/package-lock.json
ntbs-service/package.json

Reverting the sentry package updates to try to get the action to work

Revert Sentry NPM packages

---

ntbs-service-unit-tests/Models/NhsNumberValidatingTest.cs
ntbs-service/Models/Validations/NhsNumberValidationAttribute.cs
ntbs-service/Models/Validations/ValidationHelper.cs

Added monodigit checks for NHS number validation with unit tests.

NTBS-2109: Add NHS number validation for monodigit numbers

---

ntbs-service/DataAccess/DataQualityRepository.cs

Replace the EF generated query for finding name duplicates with raw SQL. (In the previous PR for this, I accidentally changed the wrong method!)

NTBS-2107 Replace correct method!

---

ntbs-service/deployments/uat.yml

Added support for Azure AD and set enabled to true

NTBS-2123 update settings for uat

---

ntbs-service/Startup.cs

Register new service with the dependency injection

NTBS-2049 Register new service with DI

---

.github/workflows/build-docker-image.yml

Annoyingly, I can't test this until after it's merged, so that the new workflow appears on the Actions tab!

NTBS-2126 On demand build of docker image for feature branches

---

.github/workflows/build-docker-image.yml

Change prefix for feature branch builds

NTBS-2126 Change prefix for feature branch builds

---

ntbs-service/Pages/Admin/Index.cshtml
ntbs-service/Pages/Index.cshtml

Add title to Dashboard and Admin pages

NTBS-2131 Add title to Dashboard and Admin pages

---

ntbs-service/Models/Entities/Alerts/AlertWithTbServiceForDisplay.cs

Add display names to new alert model which are used for the alert table titles.

NTBS-2111: Fix titles on alert table

---

EFAuditer/EFAuditer.csproj
coming-soon/coming-soon.csproj
ntbs-integration-tests/ntbs-integration-tests.csproj

Remove unnecessary package references

NTBS-2074 Remove package which is now part of framework

---

.github/workflows/build-docker-image.yml

Notify slack with feature branch image IDs

NTBS-NONE Notify slack with feature branch image IDs

---

EFAuditer-tests/EFAuditer-tests.csproj
EFAuditer/EFAuditer.csproj
ntbs-bulk-insert/ntbs-bulk-insert.csproj
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/ntbs-service.csproj
ntbs-ui-tests/ntbs-ui-tests.csproj

Update all Nuget packages.
Very few of the packages had breaking changes, and those that did do not seem to have affected us, so this was a quick win.

NTBS-2159 Update Nuget packages

---

ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-service/wwwroot/css/home.scss

Most issues were already fixed in previous tickets (such as cutting off content at the bottom of the page). I have set a min-width on the filter dropdown, which now gives it the ability to scale down as the horizontal space lessens. I have also upgraded to NHS-frontend v5.0.0 which fixes our responsive table issue in IE11.

NTBS-2086: Fixes to using the website in 400% zoom

---

EFAuditer/EFAuditer.csproj
ntbs-bulk-insert/ntbs-bulk-insert.csproj
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/ntbs-service.csproj
ntbs-ui-tests/ntbs-ui-tests.csproj

NTBS-2159 Remainder of updates that somehow got missed out

---

ntbs-integration-tests/AdminPages/CloneNotificationPageTests.cs
ntbs-integration-tests/NotificationPages/TreatmentEventsEditPageTests.cs
ntbs-service/Pages/Admin/CloneNotification.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs
ntbs-service/Startup.cs
ntbs-service/wwwroot/source/Components/ValidateContactTracing.ts
ntbs-service/wwwroot/source/Components/ValidateTravelOrVisit.ts
ntbs-service/wwwroot/source/helpers.ts

Now use a helper function to send numbers in post requests. Also add JSON string enum serializer.
One of the areas that had errors was the clone notification page validation - which wasn't caught due to lack of tests so I quickly added some.

NTBS-2097: Fix validation errors caught in QA

---

ntbs-service/deployments/uat.yml
ntbs-service/kubernetes/README.md

This is mostly just documenting the process of creating a new AKS cluster, in case it needs to be done again at some point in the future.

NTBS-2163 Add instructions for setting up new AKS cluster

---

.github/workflows/ntbs-test-and-deploy.yml
.github/workflows/ntbs-test.yml

Looks like the run time is between 4-5 minutes, so not bad at all.

NTBS-2230: Run tests on all branch pushes

---

.github/workflows/ntbs-test-and-deploy.yml
.github/workflows/ntbs-test.yml

As the tests will have already been run before merging there's no need to run the tests again (especially not twice)

NTBS-2230: No longer run tests on master

---

ntbs-service/Jobs/ReportingDataProcessingJob.cs

I have removed the call to uspProcessMIData which no longer exists. Also cleaned up the code a bit.

NTBS-2245: Remove call to removed stored procedure in hangfire job

---

ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Pages/Notifications/CaseManagerDetails.cshtml
ntbs-service/Pages/Notifications/CaseManagerDetails.cshtml.cs
ntbs-service/Pages/ServiceDirectory/Index.cshtml
ntbs-service/Pages/ServiceDirectory/Partials/SearchFormPartial.cshtml
ntbs-service/Pages/ServiceDirectory/SearchResults.cshtml
ntbs-service/wwwroot/css/caseManager.scss

I realised the code I was changing was the same in both places, so I've made a partial that holds the search form. 
Benji also found a bug which had stopped the notification's contact detail page from working. I have now updated this with the same partials as found on a user's contact details page.

NTBS-2197: Update search form header and fix notification's contact details page

---

ntbs-service/Constants.cs
ntbs-service/Pages/Shared/_Footer.cshtml
ntbs-service/Properties/ExternalLinks.cs
ntbs-service/appsettings.json

Add accessibility statement link to footer. It links properly, but I get an access error with some PHE/Sharepoint system which I think is the right outcome given our current permissions. I've not really tested this aside from running it locally given how trivial it is.

NTBS-2228 Add accessibility statement link to footer

---

ntbs-ui-tests/Steps/Steps.cs

NTBS-NONE Add temporary debugging to login step in UI tests

---

ntbs-service/Pages/Logout.cshtml.cs

Previously the logout URI was being taken from the `Wtrealm` property in the ADFS options. When I removed this property recently (because we're not using ADFS anymore) I missed that this was being used in logout (because it really shouldn't be). Instead I've made the app redirect to the home page.
To make this work properly, I've added the home pages for `int`, `test` and `uat` in the new kubernetes cluster to the app registration's redirect URIs.

NTBS-2268 Redirect to homepage when logging out of app

---

ntbs-service/Pages/Health.cshtml

Just a couple of trivial typos that I spotted when using the health page the other day. It's not a major issue but it doesn't take much to fix them either!

NTBS-NONE Minor typo fixes in Health page

---

ntbs-ui-tests/Helpers/Utilities.cs
ntbs-ui-tests/Hooks/TestConfig.cs
ntbs-ui-tests/Steps/Steps.cs

Fixed a bug in the UI tests that came in as a result of the changes to the User model.

NTBS-NONE Fix bug in UI tests

---

ntbs-service/Pages/Notifications/OverviewPartials/_ClusterInformationOverviewPartial.cshtml
ntbs-service/Pages/Shared/_ClusterIdLink.cshtml
ntbs-service/Pages/Shared/_ClusterInformation.cshtml
ntbs-service/Properties/ExternalLinks.cs
ntbs-service/Services/ReportingLinksService.cs
ntbs-service/deployments/test.yml

* Get cluster links from config
* Open cluster report in new tab, if there is a cluster report present

NTBS-2249 individual cluster report links

---

ntbs-service/Pages/Notifications/OverviewPartials/_ClinicalDetailsOverviewPartial.cshtml

Rename overview field treatment start date.

NTBS-2235 Rename overview field treatment start date

---

.github/workflows/run-ui-tests.yml

Add secrets to github workflow

NTBS-2246: Add secrets to UI test workflow

---

ntbs-integration-tests/NotificationPages/MDRDetailsPageTests.cs
ntbs-service/Models/Entities/MDRDetails.cs

* Allow some more special characters like slashes in the case relationship for the MDR questionnaire.
* Tweak the MDR integration tests to reflect this change.

NTBS-2334 Loosen validation for MDR case relationship

---

ntbs-service/Pages/Shared/_Header.cshtml
ntbs-service/Properties/EnvironmentDescription.cs
ntbs-service/appsettings.Development.json
ntbs-service/appsettings.Staging.json
ntbs-service/deployments/dev.yml
ntbs-service/deployments/live.yml
ntbs-service/deployments/uat-phe.yml

* Modify header for better text for PHE UAT: explain that for PHE UAT the data is a copy of live, but additional data should not be entered into it.
* Modify configs to add `IsLiveSystem` flag: this flag is only true for PHE live, and is false for all other environments.

NTBS-2328 UAT banner

---

.github/workflows/run-ui-tests.yml
ntbs-ui-tests/Features/CreateNotifications.feature
ntbs-ui-tests/Features/EditNotifications.feature
ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/testSettings.json

Change the UI test usernames, and update their display names where they are being referenced.
The UI tests secrets have been updated.

NTBS-2379 Use dedicated UI test Azure AD users

---

ntbs-build/database-deploy-scripts/2_Deploy_Databases.sh

Updated the locations of the publish profiles to match the changes made in NTBS-2426.

NTBS-2426 Update deploy scripts with new locations of publish profiles

---

EFAuditer/README.md

Fix the link to the Audit.NET documentation. 
This is just a documentation change, no testing required.

NTBS-2466 EFAuditer README fix

---

ntbs-ui-tests/Features/TransferNotification.feature
ntbs-ui-tests/Hooks/TestConfig.cs
ntbs-ui-tests/Steps/ActSteps.cs
ntbs-ui-tests/Steps/ArrangeSteps.cs
ntbs-ui-tests/Steps/AssertSteps.cs

Unless this turns out to be useful, we should revert it at some point.

NTBS-2446 Add logging to UI test assertions and increase implicit wait

---

ntbs-integration-tests/ContactDetailsPages/ContactDetailsPageTests.cs
ntbs-integration-tests/NtbsWebApplicationFactory.cs
ntbs-service/Pages/ContactDetails/Index.cshtml.cs

NTBS-2454: breadcrumbs changes

---

ntbs-integration-tests/NotificationPages/SocialContextAddressEditPageTests.cs
ntbs-integration-tests/NotificationPages/SocialContextVenueEditPageTests.cs
ntbs-service-unit-tests/Helpers/ValidationHelper.cs
ntbs-service-unit-tests/Models/Entities/SocialContextBaseTest.cs
ntbs-service/Models/Entities/SocialContextBase.cs
ntbs-service/Models/Validations/ValidationHelper.cs

Allow social contexts to have same from and to day

NTBS-2487 Allow to and from dates to be equal for social contexts

---

ntbs-integration-tests/Helpers/TestUser.cs
ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/DraftEditPageTests.cs
ntbs-integration-tests/NotificationPages/HospitalDetailsPageTests.cs
ntbs-service-unit-tests/Services/NotificationServiceTest.cs
ntbs-service/DataAccess/ReferenceDataRepository.cs
ntbs-service/Pages/Alerts/TransferRequest.cshtml.cs
ntbs-service/Pages/Alerts/TransferRequestAction.cshtml.cs
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs
ntbs-service/Services/NotificationService.cs

Promoted NTBS-2455 and a commit from 1399 to the hotfix, and therefore merging into live.

NTBS-live: add hotfix commits to live

---

ntbs-service/deployments/live.yml
ntbs-service/deployments/uat-phe.yml

Updated the deployment files to the new (hopefully temporary) schedule.

NTBS-2578 Update hangfire schedule

---

EFAuditer/AuditDatabaseContext.cs
ntbs-service/Middleware/AuditGetRequestMiddleware.cs
ntbs-service/Models/SeedData/AuditEventType.cs
ntbs-service/Services/AuditService.cs

Audit searches through the GetRequestMiddleware.

NTBS-2521: Audit notification searches

---

ntbs-service/Jobs/DataQualityAlertsJob.cs

The change made here is described in a fair amount of detail in the comment. In my test run, this brought the time taken by the job down from ~19 minutes to ~2.5 minutes, for ~650 duplicates. I think this is good enough, so I don't think it's necessary to think about batching the saves at this point. (Though we do still need to make the other fix of improving the data quality of the data created by the load tests - that's NTBS-2576).

NTBS-2575 Improve performance of duplicate alert checking

---

ntbs-service/Pages/Notifications/Edit/TestResults.cshtml

Added disclaimer to the test results page

NTBS-2708: Add disclaimer to test results page

---

ntbs-service/Pages/Alerts/_TransferPendingPartial.cshtml
ntbs-service/Pages/Notifications/OverviewPartials/_PatientOverviewPartial.cshtml
ntbs-ui-tests/Features/TransferNotification.feature

Soon PHE won't exist, so PHEC won't be a good name. These were the only two instances I could find of this in the front end (using some fairly precise `grep`s)

NTBS-2710 Rename PHEC to Region in front end

---

ntbs-service/DataAccess/NotificationRepository.cs

Bug fixes for splitting the notification banner query

NTBS-2734 Fix notification banner query

---

ntbs-service-unit-tests/Jobs/ReportingDataRefreshJobTest.cs
ntbs-service/Jobs/ReportingDataRefreshJob.cs

NTBS-2716: Change order of reporting data refresh SPs

---

ntbs-service/Pages/Shared/_ClusterIdLink.cshtml

NTBS-2833: Set cluster link to not print

---

ntbs-ui-tests/Steps/AssertSteps.cs

NTBS-2810: Fix UI tests

---

ntbs-service/Models/Entities/User.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/ContactDetails/Edit.cshtml.cs

Removed the validation that disallowed saving the contact details page with details missing

NTBS-2629: Remove primary contact validation

---

ntbs-ui-tests/Features/EditNotifications.feature
ntbs-ui-tests/Helpers/Utilities.cs

NTBS-2839: Fix UI tests

---

ntbs-service/Pages/Notifications/Edit/MDRDetails.cshtml
ntbs-service/Pages/Notifications/Edit/_ClinicalDetailsTreatmentOptions.cshtml

Had removed the other option by mistake, oops!

NTBS-2839: Add back in other treatment option and rename mdr field

---

ntbs-integration-tests/ContactDetailsPages/EditContactDetailsTests.cs
ntbs-service/Pages/ContactDetails/Edit.cshtml
ntbs-service/Pages/ContactDetails/Edit.cshtml.cs

NTBS-2884: Check user ID in url matches contact details ID

---

ntbs-service/Pages/Notifications/Edit/Items/_MBovisAnimalExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisExposureToKnownCase.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisUnpasteurisedMilkConsumption.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_ManualTestResult.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextAddress.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_SocialContextVenue.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_TreatmentEvent.cshtml
ntbs-service/wwwroot/source/Components/SingleSubmitForm.ts
ntbs-service/wwwroot/source/app.ts

It looks like huge changes but the only changes to the forms are that I've added the new component, added a v-on:submit, added a ref to the button, and then indented it all correctly. 

NTBS-2829: Ensure submit button not clicked twice before reload

---

ntbs-service/Pages/Notifications/Edit/Items/_SocialContextVenue.cshtml

Missed a ref for the new vue component

NTBS-2829: Add missing ref

---

ntbs-service/Models/Validations/ValidationHelper.cs

Update transfer request error message

NTBS-2841 Update transfer request error message

---

ntbs-service/DataMigration/NotificationImportService.cs

Update the error handling in the notification import when errors occur after the notification has been saved.
The main concern here is to update the migration run report to make it clear that the import of these notifications did succeed. In the case of the migration we did yesterday, we just needed to run the drug resistance update job after the migration and all would have been well, but in the report it looked like ~400 notifications had failed to migrate.
There are some changes to functionality here that will need to be tested - e.g. we could potentially be logging several warnings for the same notification. I will do this in parallel with the review process for the sake of efficiency.

NTBS-2898 Improve error handling of notification imports

---

ntbs-service/Pages/Notifications/Edit/Items/MBovisUnpasteurisedMilkConsumption.cshtml.cs
ntbs-service/Pages/Notifications/Edit/Items/_MBovisAnimalExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisOccupationExposure.cshtml
ntbs-service/Pages/Notifications/Edit/Items/_MBovisUnpasteurisedMilkConsumption.cshtml

Fix some titles and redirect behaviour on M. Bovis pages to be correct for each page, instead of incorrectly talking about known cases.
<details>
<summary>here</summary>
</details>
<details>
<summary>here</summary>
</details>
<details>
<summary>here</summary>
</details>
<details>
<summary>here</summary>
</details>

NTBS-1643 Fix M Bovis page content

---

ntbs-service/wwwroot/css/header.scss

Make the hover and focus behaviours of the header submenus a bit nicer.

NTBS-1649 Tweak header submenu CSS

---

ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml

The ordering that Benji did is now reflected with the order of the columns of the table

NTBS-2937: Move sample type to before test type

---

ntbs-service/Pages/Shared/_ManualTestResultTable.cshtml

Forgot to change the header order!

NTBS-2937: Change heading order

---

ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml
ntbs-service/Pages/Notifications/Edit/HospitalDetails.cshtml.cs

Hadn't set the existing case manager ID on page load, so the validation was failing - even though on save it was passing.

NTBS-2907: Set case manager ID on hospital page load for validation

---

ntbs-service/Pages/ContactDetails/Index.cshtml

Reorder the memberships section on contact details page

NTBS-2858: Reorder memberships on contact details page

---

ntbs-service/Models/Entities/Alerts/DataQualityBirthCountryAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityChildECMLevel.cs
ntbs-service/Models/Entities/Alerts/DataQualityClinicalDatesAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityClusterAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityDotVotAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityDraftAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityPotentialDuplicateAlert.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome12.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome24.cs
ntbs-service/Models/Entities/Alerts/DataQualityTreatmentOutcome36.cs
ntbs-service/Models/Entities/Alerts/MBovisAlert.cs
ntbs-service/Models/Entities/Alerts/MdrAlert.cs
ntbs-service/Models/Entities/Alerts/UnmatchedLabResultAlert.cs

NTBS-2992: Add root entity to alerts

---

EFAuditer-tests/EFAuditer-tests.csproj
EFAuditer/EFAuditer.csproj
ntbs-integration-tests/ntbs-integration-tests.csproj
ntbs-service-unit-tests/ntbs-service-unit-tests.csproj
ntbs-service/ntbs-service.csproj

Update the language version to C# for all projects in the ntbs_Beta repository

NTBS-2957 Upgrade C# language version to 10.0

---

ntbs-service/Models/Entities/PreviousTbService.cs
ntbs-service/Models/Enums/AuditType.cs

Add SystemEdited to AuditDetails enum to fix notifications page bug for both this and NTBS-2986.
Also added a display name to PreviousTbService model to fix a bug on NTBS-2986.

NTBS-3000 add SystemAdded to audit types

---

ntbs-service/appsettings.json

NTBS-2985: Move the data quality alerts job

---

ntbs-service/deployments/live.yml

NTBS-2985: Change cron for data quality job in live deployment file

---

ntbs-service/Services/AzureAdDirectoryService.cs

Escape apostrophe in username when making Graph API request

NTBS-3037 Allow login for user with apostrophe in their username

---

ntbs-ui-tests/Features/TransferNotification.feature

Fix transfer decline UI test (just has an ID change)

NTBS-2711: Fix decline transfer UI test

---

ntbs-service/Pages/Alerts/_TransferPendingPartial.cshtml

Add transfer date to pending partial

NTBS-2711: Add transfer date to pending page

---

ntbs-service/deployments/live.yml
ntbs-service/deployments/uat-phe.yml

NTBS-3054: Disable close notification job in Live/UAT YAML

---

ntbs-service/Pages/Alerts/TransferRequestAction.cshtml

Change to showing the requested date on the transfer action screen

NTBS-2711: Show requested date on transfer action page

---

ntbs-service/Pages/LabResults/Index.cshtml

Forgot the all important `inline-template`

NTBS-3051: Add inline-template to lab results page

---

ntbs-service/Pages/Notifications/Denotify.cshtml.cs
ntbs-service/Pages/Shared/_AlertsAndActions.cshtml

A user who can edit a closed case can also now denotify and transfer a closed case.

NTBS-3075 add denotification and transfer of closed records

---

ntbs-service/appsettings.json

Update TB Strategy link to where old link redirects to

NTBS-3074 change tb strategy link

---

ntbs-integration-tests/Helpers/Utilities.cs
ntbs-integration-tests/NotificationPages/TreatmentEventsEditPageTests.cs
ntbs-service/Models/Entities/TreatmentEvent.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/Notifications/Edit/Items/TreatmentEvent.cshtml.cs

Allow treatment events to be before notification date IF they are after diagnosis date.

NTBS-3068: Change treatment event date validation

---

ntbs-integration-tests/NotificationPages/LinkedNotificationsPageTests.cs
ntbs-integration-tests/NotificationPages/OverviewPageTests.cs
ntbs-service/DataAccess/NotificationRepository.cs

Ensure that the linked notifications fetched by the repository have all the properties needed to display the banner correctly.

NTBS-3097 missing country

---

ntbs-service/Services/ExternalLinksService.cs

NTBS-2832: Add new permission level to faq with anchor method

---

ntbs-service/README.md

NTBS-READ_ME: Update README

---

ntbs-service/Program.cs
ntbs-service/deployments/dev.yml
ntbs-service/ntbs-service.csproj

Add Splunk sink to application.
This has been tested on `phe-dev` and appears to be working well.

NTBS-3096 Add splunk sink

---

ntbs-service/DataAccess/NotificationRepository.cs

This fixes a pretty serious performance issue in the release.

NTBS-3097 Only fetch linked notifications when there is a group

---

ntbs-service/deployments/test-phe.yml

NTBS-3118 updated test YAML file for Splunk monitoring

---

ntbs-service/deployments/dev.yml
ntbs-service/deployments/test-phe.yml
ntbs-service/deployments/uat-phe.yml

Updated YML files for Splunk monitoring for other environments

NTBS-3118 updated yml files

---

ntbs-service/Models/Entities/DenotificationDetails.cs

NTBS-3143 Change Denotification Class to add Display Tag

---

ntbs-service/Models/Entities/DenotificationDetails.cs
ntbs-service/VersionInfo.cs

Merge master into Live

---

ntbs-service/Pages/Notifications/OverviewPartials/_TravelOverviewPartial.cshtml

NTBS-3131 updates

---

ntbs-service/Pages/AlertsAndActions/TransferRequestAction.cshtml.cs

NTBS-3156 updates

---

ntbs-integration-tests/NotificationPages/ClinicalDetailsPageTests.cs
ntbs-service/Models/Validations/ValidationHelper.cs
ntbs-service/Pages/LabResults/Index.cshtml
ntbs-service/Pages/LegacyNotifications/Index.cshtml
ntbs-service/appsettings.Development.json

Change_PHE Email Addresses to UKHSA

---

ntbs-service-unit-tests/Models/Entities/Alerts/ClinicalDetailsTest.cs
ntbs-service/Models/Entities/Alerts/DataQualityDotVotAlert.cs

Changes_social_risk_factor_alert_condition

---

ntbs-service/DataAccess/DrugResistanceProfileRepository.cs
ntbs-service/DataAccess/NotificationClusterRepository.cs
ntbs-service/DataMigration/MigratedNotificationsMarker.cs
ntbs-service/DataMigration/MigrationRepository.cs
ntbs-service/Properties/launchSettings.json
ntbs-service/Services/CultureAndResistanceService.cs
ntbs-service/Services/HomepageKpiService.cs
ntbs-service/Services/LegacySearchService.cs
ntbs-service/Services/SpecimenService.cs
ntbs-service/appsettings.Development.json
ntbs-service/ntbs-service.csproj
ntbs-service/package-lock.json
ntbs-service/package.json
ntbs-ui-tests/Hooks/DriverSetup.cs

Outdated Javascript Libraries

---

ntbs-service/Pages/AlertsAndActions/TransferRequest.cshtml.cs

Add authorization check to Tranfer Request post
